// Code generated - DO NOT EDIT.
// This file is a generated protocol buffer definition and any manual changes will be lost.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: MCD_PSM_USDC_A.proto

package MCD_PSM_USDC_A

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BuyGem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Owner []byte                 `protobuf:"bytes,2,opt,name=Owner,proto3" json:"Owner,omitempty"` //	address
	Value []byte                 `protobuf:"bytes,3,opt,name=Value,proto3" json:"Value,omitempty"` //	uint256
	Fee   []byte                 `protobuf:"bytes,4,opt,name=Fee,proto3" json:"Fee,omitempty"`     //	uint256
}

func (x *BuyGem) Reset() {
	*x = BuyGem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MCD_PSM_USDC_A_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuyGem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyGem) ProtoMessage() {}

func (x *BuyGem) ProtoReflect() protoreflect.Message {
	mi := &file_MCD_PSM_USDC_A_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyGem.ProtoReflect.Descriptor instead.
func (*BuyGem) Descriptor() ([]byte, []int) {
	return file_MCD_PSM_USDC_A_proto_rawDescGZIP(), []int{0}
}

func (x *BuyGem) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *BuyGem) GetOwner() []byte {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *BuyGem) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *BuyGem) GetFee() []byte {
	if x != nil {
		return x.Fee
	}
	return nil
}

type Deny struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts   *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	User []byte                 `protobuf:"bytes,2,opt,name=User,proto3" json:"User,omitempty"` //	address
}

func (x *Deny) Reset() {
	*x = Deny{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MCD_PSM_USDC_A_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Deny) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deny) ProtoMessage() {}

func (x *Deny) ProtoReflect() protoreflect.Message {
	mi := &file_MCD_PSM_USDC_A_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deny.ProtoReflect.Descriptor instead.
func (*Deny) Descriptor() ([]byte, []int) {
	return file_MCD_PSM_USDC_A_proto_rawDescGZIP(), []int{1}
}

func (x *Deny) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *Deny) GetUser() []byte {
	if x != nil {
		return x.User
	}
	return nil
}

type File struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts   *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	What []byte                 `protobuf:"bytes,2,opt,name=What,proto3" json:"What,omitempty"` //	bytes32
	Data []byte                 `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"` //	uint256
}

func (x *File) Reset() {
	*x = File{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MCD_PSM_USDC_A_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_MCD_PSM_USDC_A_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_MCD_PSM_USDC_A_proto_rawDescGZIP(), []int{2}
}

func (x *File) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *File) GetWhat() []byte {
	if x != nil {
		return x.What
	}
	return nil
}

func (x *File) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Rely struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts   *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	User []byte                 `protobuf:"bytes,2,opt,name=User,proto3" json:"User,omitempty"` //	address
}

func (x *Rely) Reset() {
	*x = Rely{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MCD_PSM_USDC_A_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rely) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rely) ProtoMessage() {}

func (x *Rely) ProtoReflect() protoreflect.Message {
	mi := &file_MCD_PSM_USDC_A_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rely.ProtoReflect.Descriptor instead.
func (*Rely) Descriptor() ([]byte, []int) {
	return file_MCD_PSM_USDC_A_proto_rawDescGZIP(), []int{3}
}

func (x *Rely) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *Rely) GetUser() []byte {
	if x != nil {
		return x.User
	}
	return nil
}

type SellGem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Owner []byte                 `protobuf:"bytes,2,opt,name=Owner,proto3" json:"Owner,omitempty"` //	address
	Value []byte                 `protobuf:"bytes,3,opt,name=Value,proto3" json:"Value,omitempty"` //	uint256
	Fee   []byte                 `protobuf:"bytes,4,opt,name=Fee,proto3" json:"Fee,omitempty"`     //	uint256
}

func (x *SellGem) Reset() {
	*x = SellGem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MCD_PSM_USDC_A_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SellGem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellGem) ProtoMessage() {}

func (x *SellGem) ProtoReflect() protoreflect.Message {
	mi := &file_MCD_PSM_USDC_A_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellGem.ProtoReflect.Descriptor instead.
func (*SellGem) Descriptor() ([]byte, []int) {
	return file_MCD_PSM_USDC_A_proto_rawDescGZIP(), []int{4}
}

func (x *SellGem) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *SellGem) GetOwner() []byte {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *SellGem) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SellGem) GetFee() []byte {
	if x != nil {
		return x.Fee
	}
	return nil
}

var File_MCD_PSM_USDC_A_proto protoreflect.FileDescriptor

var file_MCD_PSM_USDC_A_proto_rawDesc = []byte{
	0x0a, 0x14, 0x4d, 0x43, 0x44, 0x5f, 0x50, 0x53, 0x4d, 0x5f, 0x55, 0x53, 0x44, 0x43, 0x5f, 0x41,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x4d, 0x43, 0x44, 0x5f, 0x50, 0x53, 0x4d, 0x5f,
	0x55, 0x53, 0x44, 0x43, 0x5f, 0x41, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x72, 0x0a, 0x06, 0x42, 0x75, 0x79, 0x47, 0x65,
	0x6d, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x4f, 0x77,
	0x6e, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x46, 0x65, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x46, 0x65, 0x65, 0x22, 0x46, 0x0a, 0x04, 0x44,
	0x65, 0x6e, 0x79, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x55,
	0x73, 0x65, 0x72, 0x22, 0x5a, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x2a, 0x0a, 0x02, 0x74,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x57, 0x68, 0x61, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x57, 0x68, 0x61, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x44,
	0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22,
	0x46, 0x0a, 0x04, 0x52, 0x65, 0x6c, 0x79, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x02, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x55, 0x73, 0x65, 0x72, 0x22, 0x73, 0x0a, 0x07, 0x53, 0x65, 0x6c, 0x6c, 0x47,
	0x65, 0x6d, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x4f,
	0x77, 0x6e, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x46, 0x65,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x46, 0x65, 0x65, 0x42, 0x41, 0x5a, 0x3f,
	0x62, 0x6c, 0x65, 0x70, 0x2e, 0x61, 0x69, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x63, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2f, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x64, 0x61, 0x6f,
	0x2f, 0x73, 0x6d, 0x61, 0x72, 0x74, 0x2d, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73,
	0x2f, 0x4d, 0x43, 0x44, 0x5f, 0x50, 0x53, 0x4d, 0x5f, 0x55, 0x53, 0x44, 0x43, 0x5f, 0x41, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_MCD_PSM_USDC_A_proto_rawDescOnce sync.Once
	file_MCD_PSM_USDC_A_proto_rawDescData = file_MCD_PSM_USDC_A_proto_rawDesc
)

func file_MCD_PSM_USDC_A_proto_rawDescGZIP() []byte {
	file_MCD_PSM_USDC_A_proto_rawDescOnce.Do(func() {
		file_MCD_PSM_USDC_A_proto_rawDescData = protoimpl.X.CompressGZIP(file_MCD_PSM_USDC_A_proto_rawDescData)
	})
	return file_MCD_PSM_USDC_A_proto_rawDescData
}

var file_MCD_PSM_USDC_A_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_MCD_PSM_USDC_A_proto_goTypes = []interface{}{
	(*BuyGem)(nil),                // 0: MCD_PSM_USDC_A.BuyGem
	(*Deny)(nil),                  // 1: MCD_PSM_USDC_A.Deny
	(*File)(nil),                  // 2: MCD_PSM_USDC_A.File
	(*Rely)(nil),                  // 3: MCD_PSM_USDC_A.Rely
	(*SellGem)(nil),               // 4: MCD_PSM_USDC_A.SellGem
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_MCD_PSM_USDC_A_proto_depIdxs = []int32{
	5, // 0: MCD_PSM_USDC_A.BuyGem.ts:type_name -> google.protobuf.Timestamp
	5, // 1: MCD_PSM_USDC_A.Deny.ts:type_name -> google.protobuf.Timestamp
	5, // 2: MCD_PSM_USDC_A.File.ts:type_name -> google.protobuf.Timestamp
	5, // 3: MCD_PSM_USDC_A.Rely.ts:type_name -> google.protobuf.Timestamp
	5, // 4: MCD_PSM_USDC_A.SellGem.ts:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_MCD_PSM_USDC_A_proto_init() }
func file_MCD_PSM_USDC_A_proto_init() {
	if File_MCD_PSM_USDC_A_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_MCD_PSM_USDC_A_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuyGem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MCD_PSM_USDC_A_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Deny); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MCD_PSM_USDC_A_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*File); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MCD_PSM_USDC_A_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rely); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MCD_PSM_USDC_A_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SellGem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_MCD_PSM_USDC_A_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_MCD_PSM_USDC_A_proto_goTypes,
		DependencyIndexes: file_MCD_PSM_USDC_A_proto_depIdxs,
		MessageInfos:      file_MCD_PSM_USDC_A_proto_msgTypes,
	}.Build()
	File_MCD_PSM_USDC_A_proto = out.File
	file_MCD_PSM_USDC_A_proto_rawDesc = nil
	file_MCD_PSM_USDC_A_proto_goTypes = nil
	file_MCD_PSM_USDC_A_proto_depIdxs = nil
}
