// Code generated - DO NOT EDIT.
// This file is a generated protocol buffer definition and any manual changes will be lost.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: ARBITRUM_L2_DAI_GATEWAY.proto

package ARBITRUM_L2_DAI_GATEWAY

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Approve struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts      *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Token   []byte                 `protobuf:"bytes,2,opt,name=Token,proto3" json:"Token,omitempty"`     //	address
	Spender []byte                 `protobuf:"bytes,3,opt,name=Spender,proto3" json:"Spender,omitempty"` //	address
	Value   []byte                 `protobuf:"bytes,4,opt,name=Value,proto3" json:"Value,omitempty"`     //	uint256
}

func (x *Approve) Reset() {
	*x = Approve{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ARBITRUM_L2_DAI_GATEWAY_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Approve) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Approve) ProtoMessage() {}

func (x *Approve) ProtoReflect() protoreflect.Message {
	mi := &file_ARBITRUM_L2_DAI_GATEWAY_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Approve.ProtoReflect.Descriptor instead.
func (*Approve) Descriptor() ([]byte, []int) {
	return file_ARBITRUM_L2_DAI_GATEWAY_proto_rawDescGZIP(), []int{0}
}

func (x *Approve) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *Approve) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *Approve) GetSpender() []byte {
	if x != nil {
		return x.Spender
	}
	return nil
}

func (x *Approve) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type Deny struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts  *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Usr []byte                 `protobuf:"bytes,2,opt,name=Usr,proto3" json:"Usr,omitempty"` //	address
}

func (x *Deny) Reset() {
	*x = Deny{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ARBITRUM_L2_DAI_GATEWAY_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Deny) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deny) ProtoMessage() {}

func (x *Deny) ProtoReflect() protoreflect.Message {
	mi := &file_ARBITRUM_L2_DAI_GATEWAY_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deny.ProtoReflect.Descriptor instead.
func (*Deny) Descriptor() ([]byte, []int) {
	return file_ARBITRUM_L2_DAI_GATEWAY_proto_rawDescGZIP(), []int{1}
}

func (x *Deny) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *Deny) GetUsr() []byte {
	if x != nil {
		return x.Usr
	}
	return nil
}

type Rely struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts  *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Usr []byte                 `protobuf:"bytes,2,opt,name=Usr,proto3" json:"Usr,omitempty"` //	address
}

func (x *Rely) Reset() {
	*x = Rely{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ARBITRUM_L2_DAI_GATEWAY_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rely) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rely) ProtoMessage() {}

func (x *Rely) ProtoReflect() protoreflect.Message {
	mi := &file_ARBITRUM_L2_DAI_GATEWAY_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rely.ProtoReflect.Descriptor instead.
func (*Rely) Descriptor() ([]byte, []int) {
	return file_ARBITRUM_L2_DAI_GATEWAY_proto_rawDescGZIP(), []int{2}
}

func (x *Rely) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *Rely) GetUsr() []byte {
	if x != nil {
		return x.Usr
	}
	return nil
}

var File_ARBITRUM_L2_DAI_GATEWAY_proto protoreflect.FileDescriptor

var file_ARBITRUM_L2_DAI_GATEWAY_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x41, 0x52, 0x42, 0x49, 0x54, 0x52, 0x55, 0x4d, 0x5f, 0x4c, 0x32, 0x5f, 0x44, 0x41,
	0x49, 0x5f, 0x47, 0x41, 0x54, 0x45, 0x57, 0x41, 0x59, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x17, 0x41, 0x52, 0x42, 0x49, 0x54, 0x52, 0x55, 0x4d, 0x5f, 0x4c, 0x32, 0x5f, 0x44, 0x41, 0x49,
	0x5f, 0x47, 0x41, 0x54, 0x45, 0x57, 0x41, 0x59, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7b, 0x0a, 0x07, 0x41, 0x70, 0x70,
	0x72, 0x6f, 0x76, 0x65, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x70, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x53, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x44, 0x0a, 0x04, 0x44, 0x65, 0x6e, 0x79, 0x12, 0x2a,
	0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x73,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x55, 0x73, 0x72, 0x22, 0x44, 0x0a, 0x04,
	0x52, 0x65, 0x6c, 0x79, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73,
	0x12, 0x10, 0x0a, 0x03, 0x55, 0x73, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x55,
	0x73, 0x72, 0x42, 0x4a, 0x5a, 0x48, 0x62, 0x6c, 0x65, 0x70, 0x2e, 0x61, 0x69, 0x2f, 0x64, 0x61,
	0x74, 0x61, 0x2f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2f, 0x6d, 0x61,
	0x6b, 0x65, 0x72, 0x64, 0x61, 0x6f, 0x2f, 0x73, 0x6d, 0x61, 0x72, 0x74, 0x2d, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x2f, 0x41, 0x52, 0x42, 0x49, 0x54, 0x52, 0x55, 0x4d, 0x5f,
	0x4c, 0x32, 0x5f, 0x44, 0x41, 0x49, 0x5f, 0x47, 0x41, 0x54, 0x45, 0x57, 0x41, 0x59, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ARBITRUM_L2_DAI_GATEWAY_proto_rawDescOnce sync.Once
	file_ARBITRUM_L2_DAI_GATEWAY_proto_rawDescData = file_ARBITRUM_L2_DAI_GATEWAY_proto_rawDesc
)

func file_ARBITRUM_L2_DAI_GATEWAY_proto_rawDescGZIP() []byte {
	file_ARBITRUM_L2_DAI_GATEWAY_proto_rawDescOnce.Do(func() {
		file_ARBITRUM_L2_DAI_GATEWAY_proto_rawDescData = protoimpl.X.CompressGZIP(file_ARBITRUM_L2_DAI_GATEWAY_proto_rawDescData)
	})
	return file_ARBITRUM_L2_DAI_GATEWAY_proto_rawDescData
}

var file_ARBITRUM_L2_DAI_GATEWAY_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ARBITRUM_L2_DAI_GATEWAY_proto_goTypes = []interface{}{
	(*Approve)(nil),               // 0: ARBITRUM_L2_DAI_GATEWAY.Approve
	(*Deny)(nil),                  // 1: ARBITRUM_L2_DAI_GATEWAY.Deny
	(*Rely)(nil),                  // 2: ARBITRUM_L2_DAI_GATEWAY.Rely
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_ARBITRUM_L2_DAI_GATEWAY_proto_depIdxs = []int32{
	3, // 0: ARBITRUM_L2_DAI_GATEWAY.Approve.ts:type_name -> google.protobuf.Timestamp
	3, // 1: ARBITRUM_L2_DAI_GATEWAY.Deny.ts:type_name -> google.protobuf.Timestamp
	3, // 2: ARBITRUM_L2_DAI_GATEWAY.Rely.ts:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_ARBITRUM_L2_DAI_GATEWAY_proto_init() }
func file_ARBITRUM_L2_DAI_GATEWAY_proto_init() {
	if File_ARBITRUM_L2_DAI_GATEWAY_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ARBITRUM_L2_DAI_GATEWAY_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Approve); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ARBITRUM_L2_DAI_GATEWAY_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Deny); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ARBITRUM_L2_DAI_GATEWAY_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rely); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ARBITRUM_L2_DAI_GATEWAY_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ARBITRUM_L2_DAI_GATEWAY_proto_goTypes,
		DependencyIndexes: file_ARBITRUM_L2_DAI_GATEWAY_proto_depIdxs,
		MessageInfos:      file_ARBITRUM_L2_DAI_GATEWAY_proto_msgTypes,
	}.Build()
	File_ARBITRUM_L2_DAI_GATEWAY_proto = out.File
	file_ARBITRUM_L2_DAI_GATEWAY_proto_rawDesc = nil
	file_ARBITRUM_L2_DAI_GATEWAY_proto_goTypes = nil
	file_ARBITRUM_L2_DAI_GATEWAY_proto_depIdxs = nil
}
