syntax = "proto3";

package evm;

import "google/protobuf/timestamp.proto";
import "lotus/lotus.proto";

option go_package = "github.com/trylotus/connectors/monad/evm";

message Block {
  google.protobuf.Timestamp ts = 1;
  bytes hash = 2 [
    (lotus.bytes) = {format: FORMAT_TYPE_HEX},
    (lotus.index) = {unique: true}
  ]; // Hash
  uint64 number = 3 [
    (lotus.numeric) = {},
    (lotus.index) = {}
  ];
  string difficulty = 4 [(lotus.numeric) = {}]; // bigint
  uint64 gas_limit = 5;
  uint64 gas_used = 6;
  uint64 nonce = 7;
}

message Transaction {
  google.protobuf.Timestamp ts = 1;
  bytes block_hash = 2 [
    (lotus.bytes) = {format: FORMAT_TYPE_HEX},
    (lotus.index) = {}
  ]; // Hash
  uint64 block_number = 3 [(lotus.index) = {}];
  bytes hash = 4 [
    (lotus.bytes) = {format: FORMAT_TYPE_HEX},
    (lotus.index) = {unique: true}
  ]; // Hash
  bytes from = 5 [
    (lotus.bytes) = {format: FORMAT_TYPE_HEX},
    (lotus.index) = {}
  ]; // Address
  bytes to = 6 [
    (lotus.bytes) = {format: FORMAT_TYPE_HEX},
    (lotus.index) = {}
  ]; // Address
  uint64 size = 7;
  uint64 nonce = 8;
  uint64 gas = 9;
  string gas_price = 10 [(lotus.numeric) = {}]; // bigint
  string value = 11 [(lotus.numeric) = {}]; // bigint
  bytes data = 12;
  string v = 13 [(lotus.numeric) = {}]; // bigint
  string r = 14 [(lotus.numeric) = {}]; // bigint
  string s = 15 [(lotus.numeric) = {}]; // bigint
}
