// Code generated - DO NOT EDIT.
// This file is a generated protocol buffer definition and any manual changes will be lost.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: PROXY_FACTORY.proto

package PROXY_FACTORY

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Created struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Sender []byte                 `protobuf:"bytes,2,opt,name=Sender,proto3" json:"Sender,omitempty"` //	address
	Owner  []byte                 `protobuf:"bytes,3,opt,name=Owner,proto3" json:"Owner,omitempty"`   //	address
	Proxy  []byte                 `protobuf:"bytes,4,opt,name=Proxy,proto3" json:"Proxy,omitempty"`   //	address
	Cache  []byte                 `protobuf:"bytes,5,opt,name=Cache,proto3" json:"Cache,omitempty"`   //	address
}

func (x *Created) Reset() {
	*x = Created{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PROXY_FACTORY_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Created) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Created) ProtoMessage() {}

func (x *Created) ProtoReflect() protoreflect.Message {
	mi := &file_PROXY_FACTORY_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Created.ProtoReflect.Descriptor instead.
func (*Created) Descriptor() ([]byte, []int) {
	return file_PROXY_FACTORY_proto_rawDescGZIP(), []int{0}
}

func (x *Created) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *Created) GetSender() []byte {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *Created) GetOwner() []byte {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *Created) GetProxy() []byte {
	if x != nil {
		return x.Proxy
	}
	return nil
}

func (x *Created) GetCache() []byte {
	if x != nil {
		return x.Cache
	}
	return nil
}

var File_PROXY_FACTORY_proto protoreflect.FileDescriptor

var file_PROXY_FACTORY_proto_rawDesc = []byte{
	0x0a, 0x13, 0x50, 0x52, 0x4f, 0x58, 0x59, 0x5f, 0x46, 0x41, 0x43, 0x54, 0x4f, 0x52, 0x59, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x50, 0x52, 0x4f, 0x58, 0x59, 0x5f, 0x46, 0x41, 0x43,
	0x54, 0x4f, 0x52, 0x59, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8f, 0x01, 0x0a, 0x07, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x53,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x50,
	0x72, 0x6f, 0x78, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x50, 0x72, 0x6f, 0x78,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x61, 0x63, 0x68, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x05, 0x43, 0x61, 0x63, 0x68, 0x65, 0x42, 0x40, 0x5a, 0x3e, 0x62, 0x6c, 0x65, 0x70, 0x2e,
	0x61, 0x69, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x73, 0x2f, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x64, 0x61, 0x6f, 0x2f, 0x73, 0x6d, 0x61, 0x72,
	0x74, 0x2d, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x2f, 0x50, 0x52, 0x4f, 0x58,
	0x59, 0x5f, 0x46, 0x41, 0x43, 0x54, 0x4f, 0x52, 0x59, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_PROXY_FACTORY_proto_rawDescOnce sync.Once
	file_PROXY_FACTORY_proto_rawDescData = file_PROXY_FACTORY_proto_rawDesc
)

func file_PROXY_FACTORY_proto_rawDescGZIP() []byte {
	file_PROXY_FACTORY_proto_rawDescOnce.Do(func() {
		file_PROXY_FACTORY_proto_rawDescData = protoimpl.X.CompressGZIP(file_PROXY_FACTORY_proto_rawDescData)
	})
	return file_PROXY_FACTORY_proto_rawDescData
}

var file_PROXY_FACTORY_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_PROXY_FACTORY_proto_goTypes = []interface{}{
	(*Created)(nil),               // 0: PROXY_FACTORY.Created
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_PROXY_FACTORY_proto_depIdxs = []int32{
	1, // 0: PROXY_FACTORY.Created.ts:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_PROXY_FACTORY_proto_init() }
func file_PROXY_FACTORY_proto_init() {
	if File_PROXY_FACTORY_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_PROXY_FACTORY_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Created); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_PROXY_FACTORY_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PROXY_FACTORY_proto_goTypes,
		DependencyIndexes: file_PROXY_FACTORY_proto_depIdxs,
		MessageInfos:      file_PROXY_FACTORY_proto_msgTypes,
	}.Build()
	File_PROXY_FACTORY_proto = out.File
	file_PROXY_FACTORY_proto_rawDesc = nil
	file_PROXY_FACTORY_proto_goTypes = nil
	file_PROXY_FACTORY_proto_depIdxs = nil
}
