package anon_bank_authority

import (
	"context"
	"strings"

	"github.com/ethereum/go-ethereum/accounts/abi"
	ethcommon "github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"
	"github.com/rs/zerolog/log"
	"github.com/starbloom-ai/go-connector/common"
	"github.com/starbloom-ai/go-connector/source/evm"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/known/timestamppb"
)

type SmartContract struct {
	Addr ethcommon.Address
	Abi  abi.ABI
}

var _ evm.SmartContract = (*SmartContract)(nil)

func NewContract(address ethcommon.Address) *SmartContract {
	contractAbi, err := abi.JSON(strings.NewReader(AnonBankAuthorityMetaData.ABI))
	if err != nil {
		log.Fatal().Err(err).Msg("failed to read contract ABI")
	}
	return &SmartContract{Addr: address, Abi: contractAbi}
}

func (c *SmartContract) Address() ethcommon.Address {
	return c.Addr
}

func (c *SmartContract) ParseLog(_ context.Context, vLog types.Log, ts *timestamppb.Timestamp) (proto.Message, error) {
	ev, err := c.Abi.EventByID(vLog.Topics[0])
	if err != nil {
		return nil, evm.InvalidLogError(err)
	}
	switch ev.Name {

/* Code generated by https://github.com/trylotus/connector-bot. DO NOT EDIT */



case "GuardianPushed":
	event := new(AnonBankAuthorityGuardianPushed)
	if err := common.UnpackLog(c.Abi, event, ev.Name, vLog); err != nil {
		return nil, evm.InvalidLogError(err)
	}
	protoMsg := &GuardianPushed{
		Ts:          ts,
		BlockNumber: vLog.BlockNumber,
		BlockHash:   vLog.BlockHash.Bytes(),
		TxHash:      vLog.TxHash.Bytes(),
		LogIndex:       uint64(vLog.Index),

		EffectiveImmediately: event.EffectiveImmediately,
		From: event.From.Bytes(),
		To: event.To.Bytes(),
	}


	return protoMsg, nil


case "PolicyPushed":
	event := new(AnonBankAuthorityPolicyPushed)
	if err := common.UnpackLog(c.Abi, event, ev.Name, vLog); err != nil {
		return nil, evm.InvalidLogError(err)
	}
	protoMsg := &PolicyPushed{
		Ts:          ts,
		BlockNumber: vLog.BlockNumber,
		BlockHash:   vLog.BlockHash.Bytes(),
		TxHash:      vLog.TxHash.Bytes(),
		LogIndex:       uint64(vLog.Index),

		EffectiveImmediately: event.EffectiveImmediately,
		From: event.From.Bytes(),
		To: event.To.Bytes(),
	}


	return protoMsg, nil


case "VaultPulled":
	event := new(AnonBankAuthorityVaultPulled)
	if err := common.UnpackLog(c.Abi, event, ev.Name, vLog); err != nil {
		return nil, evm.InvalidLogError(err)
	}
	protoMsg := &VaultPulled{
		Ts:          ts,
		BlockNumber: vLog.BlockNumber,
		BlockHash:   vLog.BlockHash.Bytes(),
		TxHash:      vLog.TxHash.Bytes(),
		LogIndex:       uint64(vLog.Index),

		From: event.From.Bytes(),
		To: event.To.Bytes(),
	}


	return protoMsg, nil


case "AuthorityUpdated":
	event := new(AnonBankAuthorityAuthorityUpdated)
	if err := common.UnpackLog(c.Abi, event, ev.Name, vLog); err != nil {
		return nil, evm.InvalidLogError(err)
	}
	protoMsg := &AuthorityUpdated{
		Ts:          ts,
		BlockNumber: vLog.BlockNumber,
		BlockHash:   vLog.BlockHash.Bytes(),
		TxHash:      vLog.TxHash.Bytes(),
		LogIndex:       uint64(vLog.Index),

		Authority: event.Authority.Bytes(),
	}


	return protoMsg, nil


case "GovernorPulled":
	event := new(AnonBankAuthorityGovernorPulled)
	if err := common.UnpackLog(c.Abi, event, ev.Name, vLog); err != nil {
		return nil, evm.InvalidLogError(err)
	}
	protoMsg := &GovernorPulled{
		Ts:          ts,
		BlockNumber: vLog.BlockNumber,
		BlockHash:   vLog.BlockHash.Bytes(),
		TxHash:      vLog.TxHash.Bytes(),
		LogIndex:       uint64(vLog.Index),

		From: event.From.Bytes(),
		To: event.To.Bytes(),
	}


	return protoMsg, nil


case "GovernorPushed":
	event := new(AnonBankAuthorityGovernorPushed)
	if err := common.UnpackLog(c.Abi, event, ev.Name, vLog); err != nil {
		return nil, evm.InvalidLogError(err)
	}
	protoMsg := &GovernorPushed{
		Ts:          ts,
		BlockNumber: vLog.BlockNumber,
		BlockHash:   vLog.BlockHash.Bytes(),
		TxHash:      vLog.TxHash.Bytes(),
		LogIndex:       uint64(vLog.Index),

		EffectiveImmediately: event.EffectiveImmediately,
		From: event.From.Bytes(),
		To: event.To.Bytes(),
	}


	return protoMsg, nil


case "GuardianPulled":
	event := new(AnonBankAuthorityGuardianPulled)
	if err := common.UnpackLog(c.Abi, event, ev.Name, vLog); err != nil {
		return nil, evm.InvalidLogError(err)
	}
	protoMsg := &GuardianPulled{
		Ts:          ts,
		BlockNumber: vLog.BlockNumber,
		BlockHash:   vLog.BlockHash.Bytes(),
		TxHash:      vLog.TxHash.Bytes(),
		LogIndex:       uint64(vLog.Index),

		From: event.From.Bytes(),
		To: event.To.Bytes(),
	}


	return protoMsg, nil


case "PolicyPulled":
	event := new(AnonBankAuthorityPolicyPulled)
	if err := common.UnpackLog(c.Abi, event, ev.Name, vLog); err != nil {
		return nil, evm.InvalidLogError(err)
	}
	protoMsg := &PolicyPulled{
		Ts:          ts,
		BlockNumber: vLog.BlockNumber,
		BlockHash:   vLog.BlockHash.Bytes(),
		TxHash:      vLog.TxHash.Bytes(),
		LogIndex:       uint64(vLog.Index),

		From: event.From.Bytes(),
		To: event.To.Bytes(),
	}


	return protoMsg, nil


case "VaultPushed":
	event := new(AnonBankAuthorityVaultPushed)
	if err := common.UnpackLog(c.Abi, event, ev.Name, vLog); err != nil {
		return nil, evm.InvalidLogError(err)
	}
	protoMsg := &VaultPushed{
		Ts:          ts,
		BlockNumber: vLog.BlockNumber,
		BlockHash:   vLog.BlockHash.Bytes(),
		TxHash:      vLog.TxHash.Bytes(),
		LogIndex:       uint64(vLog.Index),

		EffectiveImmediately: event.EffectiveImmediately,
		From: event.From.Bytes(),
		To: event.To.Bytes(),
	}


	return protoMsg, nil



/* Code generated by https://github.com/trylotus/connector-bot. DO NOT EDIT */

	default:
		return nil, evm.InvalidLogErrorf("unhandled event: %s", ev.Name)
	}
}
