// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file lotus/lotus.proto (package lotus, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { FieldOptions, MessageOptions } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_descriptor } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file lotus/lotus.proto.
 */
export const file_lotus_lotus: GenFile = /*@__PURE__*/
  fileDesc("ChFsb3R1cy9sb3R1cy5wcm90bxIFbG90dXMiPQoLSW5kZXhPcHRpb24SHgoEdHlwZRgBIAEoDjIQLmxvdHVzLkluZGV4VHlwZRIOCgZ1bmlxdWUYAiABKAgiRAoWQ29tcG9zaXRlSW5kZXhlc09wdGlvbhIqCgVpbmRleBgBIAMoCzIbLmxvdHVzLkNvbXBvc2l0ZUluZGV4T3B0aW9uIlYKFENvbXBvc2l0ZUluZGV4T3B0aW9uEh4KBHR5cGUYASABKA4yEC5sb3R1cy5JbmRleFR5cGUSDgoGdW5pcXVlGAIgASgIEg4KBmZpZWxkcxgDIAMoCSIwCgtCeXRlc09wdGlvbhIhCgZmb3JtYXQYASABKA4yES5sb3R1cy5Gb3JtYXRUeXBlIlMKDU51bWVyaWNPcHRpb24SFgoJcHJlY2lzaW9uGAEgASgNSACIAQESEgoFc2NhbGUYAiABKA1IAYgBAUIMCgpfcHJlY2lzaW9uQggKBl9zY2FsZSKfAQoKVmlld09wdGlvbhINCgV0b3BpYxgBIAEoCRIUCgxtYXRlcmlhbGl6ZWQYAiABKAgSEAoIcmVhbHRpbWUYAyABKAgSGAoQcmVmcmVzaF9pbnRlcnZhbBgEIAEoCRIPCgdvcHRpb25zGAUgAygJEhAKCGdyb3VwX2J5GAYgAygJEg0KBXdoZXJlGAcgASgJEg4KBmhhdmluZxgIIAEoCSo9CglJbmRleFR5cGUSFgoSSU5ERVhfVFlQRV9PUkRFUkVEEAASGAoUSU5ERVhfVFlQRV9VTk9SREVSRUQQASo5CgpGb3JtYXRUeXBlEhYKEkZPUk1BVF9UWVBFX0JBU0U2NBAAEhMKD0ZPUk1BVF9UWVBFX0hFWBABOmEKCWNvbXBvc2l0ZRIfLmdvb2dsZS5wcm90b2J1Zi5NZXNzYWdlT3B0aW9ucxi5hQYgASgLMh0ubG90dXMuQ29tcG9zaXRlSW5kZXhlc09wdGlvblIJY29tcG9zaXRliAEBOksKBHZpZXcSHy5nb29nbGUucHJvdG9idWYuTWVzc2FnZU9wdGlvbnMYuoUGIAEoCzIRLmxvdHVzLlZpZXdPcHRpb25SBHZpZXeIAQE6TAoFaW5kZXgSHS5nb29nbGUucHJvdG9idWYuRmllbGRPcHRpb25zGLmFBiABKAsyEi5sb3R1cy5JbmRleE9wdGlvblIFaW5kZXiIAQE6TAoFYnl0ZXMSHS5nb29nbGUucHJvdG9idWYuRmllbGRPcHRpb25zGLqFBiABKAsyEi5sb3R1cy5CeXRlc09wdGlvblIFYnl0ZXOIAQE6UgoHbnVtZXJpYxIdLmdvb2dsZS5wcm90b2J1Zi5GaWVsZE9wdGlvbnMYu4UGIAEoCzIULmxvdHVzLk51bWVyaWNPcHRpb25SB251bWVyaWOIAQE6QgoKcHJvamVjdGlvbhIdLmdvb2dsZS5wcm90b2J1Zi5GaWVsZE9wdGlvbnMYvIUGIAEoCVIKcHJvamVjdGlvbogBAUIqWihnaXRodWIuY29tL3RyeWxvdHVzL2dvLWxvdHVzLXByb3RvO2xvdHVzYgZwcm90bzM", [file_google_protobuf_descriptor]);

/**
 * Defines options for indexing a field.
 *
 * @generated from message lotus.IndexOption
 */
export type IndexOption = Message<"lotus.IndexOption"> & {
  /**
   * Type of index (default to ordered).
   *
   * @generated from field: lotus.IndexType type = 1;
   */
  type: IndexType;

  /**
   * Whether this is a unique index (default to false).
   *
   * @generated from field: bool unique = 2;
   */
  unique: boolean;
};

/**
 * Describes the message lotus.IndexOption.
 * Use `create(IndexOptionSchema)` to create a new message.
 */
export const IndexOptionSchema: GenMessage<IndexOption> = /*@__PURE__*/
  messageDesc(file_lotus_lotus, 0);

/**
 * Defines options for indexing multiple fields.
 *
 * @generated from message lotus.CompositeIndexesOption
 */
export type CompositeIndexesOption = Message<"lotus.CompositeIndexesOption"> & {
  /**
   * List of composite indexes.
   *
   * @generated from field: repeated lotus.CompositeIndexOption index = 1;
   */
  index: CompositeIndexOption[];
};

/**
 * Describes the message lotus.CompositeIndexesOption.
 * Use `create(CompositeIndexesOptionSchema)` to create a new message.
 */
export const CompositeIndexesOptionSchema: GenMessage<CompositeIndexesOption> = /*@__PURE__*/
  messageDesc(file_lotus_lotus, 1);

/**
 * Defines options for composite indexes involving multiple fields.
 *
 * @generated from message lotus.CompositeIndexOption
 */
export type CompositeIndexOption = Message<"lotus.CompositeIndexOption"> & {
  /**
   * Type of composite index (default to ordered).
   *
   * @generated from field: lotus.IndexType type = 1;
   */
  type: IndexType;

  /**
   * Whether this is a unique index (default to false).
   *
   * @generated from field: bool unique = 2;
   */
  unique: boolean;

  /**
   * List of field names involved in the composite index.
   *
   * @generated from field: repeated string fields = 3;
   */
  fields: string[];
};

/**
 * Describes the message lotus.CompositeIndexOption.
 * Use `create(CompositeIndexOptionSchema)` to create a new message.
 */
export const CompositeIndexOptionSchema: GenMessage<CompositeIndexOption> = /*@__PURE__*/
  messageDesc(file_lotus_lotus, 2);

/**
 * Defines options for how bytes fields are encoded/decoded.
 *
 * @generated from message lotus.BytesOption
 */
export type BytesOption = Message<"lotus.BytesOption"> & {
  /**
   * Format to use for displaying binary data (default to base64).
   *
   * @generated from field: lotus.FormatType format = 1;
   */
  format: FormatType;
};

/**
 * Describes the message lotus.BytesOption.
 * Use `create(BytesOptionSchema)` to create a new message.
 */
export const BytesOptionSchema: GenMessage<BytesOption> = /*@__PURE__*/
  messageDesc(file_lotus_lotus, 3);

/**
 * Defines options for how numeric fields are scaled/represented.
 *
 * @generated from message lotus.NumericOption
 */
export type NumericOption = Message<"lotus.NumericOption"> & {
  /**
   * Total number of significant digits (including decimals).
   *
   * @generated from field: optional uint32 precision = 1;
   */
  precision?: number;

  /**
   * Number of decimal places (0 for integers).
   *
   * @generated from field: optional uint32 scale = 2;
   */
  scale?: number;
};

/**
 * Describes the message lotus.NumericOption.
 * Use `create(NumericOptionSchema)` to create a new message.
 */
export const NumericOptionSchema: GenMessage<NumericOption> = /*@__PURE__*/
  messageDesc(file_lotus_lotus, 4);

/**
 * Defines options for aggregating data from another message.
 *
 * @generated from message lotus.ViewOption
 */
export type ViewOption = Message<"lotus.ViewOption"> & {
  /**
   * Topic that is aggregated from.
   *
   * @generated from field: string topic = 1;
   */
  topic: string;

  /**
   * Whether this is a materialized view (default to false).
   *
   * @generated from field: bool materialized = 2;
   */
  materialized: boolean;

  /**
   * Whether to enable realtime aggregation (default to false).
   *
   * @generated from field: bool realtime = 3;
   */
  realtime: boolean;

  /**
   * Time interval to refresh materialized view.
   *
   * @generated from field: string refresh_interval = 4;
   */
  refreshInterval: string;

  /**
   * View options.
   *
   * @generated from field: repeated string options = 5;
   */
  options: string[];

  /**
   * List of field names used for aggregation.
   *
   * @generated from field: repeated string group_by = 6;
   */
  groupBy: string[];

  /**
   * Where condition applied to the aggregation.
   *
   * @generated from field: string where = 7;
   */
  where: string;

  /**
   * Having condition applied to the aggregation.
   *
   * @generated from field: string having = 8;
   */
  having: string;
};

/**
 * Describes the message lotus.ViewOption.
 * Use `create(ViewOptionSchema)` to create a new message.
 */
export const ViewOptionSchema: GenMessage<ViewOption> = /*@__PURE__*/
  messageDesc(file_lotus_lotus, 5);

/**
 * Specifies the type of index.
 *
 * @generated from enum lotus.IndexType
 */
export enum IndexType {
  /**
   * Ordered index (maintains order).
   *
   * @generated from enum value: INDEX_TYPE_ORDERED = 0;
   */
  ORDERED = 0,

  /**
   * Unordered index (faster for lookups).
   *
   * @generated from enum value: INDEX_TYPE_UNORDERED = 1;
   */
  UNORDERED = 1,
}

/**
 * Describes the enum lotus.IndexType.
 */
export const IndexTypeSchema: GenEnum<IndexType> = /*@__PURE__*/
  enumDesc(file_lotus_lotus, 0);

/**
 * Specifies the format for encoding/decoding bytes data.
 *
 * @generated from enum lotus.FormatType
 */
export enum FormatType {
  /**
   * Standard base64 encoding.
   *
   * @generated from enum value: FORMAT_TYPE_BASE64 = 0;
   */
  BASE64 = 0,

  /**
   * Hexadecimal encoding.
   *
   * @generated from enum value: FORMAT_TYPE_HEX = 1;
   */
  HEX = 1,
}

/**
 * Describes the enum lotus.FormatType.
 */
export const FormatTypeSchema: GenEnum<FormatType> = /*@__PURE__*/
  enumDesc(file_lotus_lotus, 1);

/**
 * Option to specify composite indexes on multiple fields.
 *
 * @generated from extension: optional lotus.CompositeIndexesOption composite = 99001;
 */
export const composite: GenExtension<MessageOptions, CompositeIndexesOption> = /*@__PURE__*/
  extDesc(file_lotus_lotus, 0);

/**
 * Option to specify a view aggregated from another message.
 *
 * @generated from extension: optional lotus.ViewOption view = 99002;
 */
export const view: GenExtension<MessageOptions, ViewOption> = /*@__PURE__*/
  extDesc(file_lotus_lotus, 1);

/**
 * Option to mark a field as indexed.
 *
 * @generated from extension: optional lotus.IndexOption index = 99001;
 */
export const index: GenExtension<FieldOptions, IndexOption> = /*@__PURE__*/
  extDesc(file_lotus_lotus, 2);

/**
 * Option to specify how bytes fields are encoded/decoded.
 *
 * @generated from extension: optional lotus.BytesOption bytes = 99002;
 */
export const bytes: GenExtension<FieldOptions, BytesOption> = /*@__PURE__*/
  extDesc(file_lotus_lotus, 3);

/**
 * Option to specify how numeric fields are scaled/represented.
 *
 * @generated from extension: optional lotus.NumericOption numeric = 99003;
 */
export const numeric: GenExtension<FieldOptions, NumericOption> = /*@__PURE__*/
  extDesc(file_lotus_lotus, 4);

/**
 * Option to define a calculated field, computed from other fields.
 *
 * @generated from extension: optional string projection = 99004;
 */
export const projection: GenExtension<FieldOptions, string> = /*@__PURE__*/
  extDesc(file_lotus_lotus, 5);

