// Code generated - DO NOT EDIT.
// This file is a generated protocol buffer definition and any manual changes will be lost.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: TUSD.proto

package TUSD

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Upgraded struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts             *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Implementation []byte                 `protobuf:"bytes,2,opt,name=Implementation,proto3" json:"Implementation,omitempty"` //	address
}

func (x *Upgraded) Reset() {
	*x = Upgraded{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TUSD_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Upgraded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Upgraded) ProtoMessage() {}

func (x *Upgraded) ProtoReflect() protoreflect.Message {
	mi := &file_TUSD_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Upgraded.ProtoReflect.Descriptor instead.
func (*Upgraded) Descriptor() ([]byte, []int) {
	return file_TUSD_proto_rawDescGZIP(), []int{0}
}

func (x *Upgraded) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *Upgraded) GetImplementation() []byte {
	if x != nil {
		return x.Implementation
	}
	return nil
}

type ProxyOwnershipTransferred struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts            *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	PreviousOwner []byte                 `protobuf:"bytes,2,opt,name=PreviousOwner,proto3" json:"PreviousOwner,omitempty"` //	address
	NewOwner      []byte                 `protobuf:"bytes,3,opt,name=NewOwner,proto3" json:"NewOwner,omitempty"`           //	address
}

func (x *ProxyOwnershipTransferred) Reset() {
	*x = ProxyOwnershipTransferred{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TUSD_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProxyOwnershipTransferred) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyOwnershipTransferred) ProtoMessage() {}

func (x *ProxyOwnershipTransferred) ProtoReflect() protoreflect.Message {
	mi := &file_TUSD_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyOwnershipTransferred.ProtoReflect.Descriptor instead.
func (*ProxyOwnershipTransferred) Descriptor() ([]byte, []int) {
	return file_TUSD_proto_rawDescGZIP(), []int{1}
}

func (x *ProxyOwnershipTransferred) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *ProxyOwnershipTransferred) GetPreviousOwner() []byte {
	if x != nil {
		return x.PreviousOwner
	}
	return nil
}

func (x *ProxyOwnershipTransferred) GetNewOwner() []byte {
	if x != nil {
		return x.NewOwner
	}
	return nil
}

type NewPendingOwner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts           *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	CurrentOwner []byte                 `protobuf:"bytes,2,opt,name=CurrentOwner,proto3" json:"CurrentOwner,omitempty"` //	address
	PendingOwner []byte                 `protobuf:"bytes,3,opt,name=PendingOwner,proto3" json:"PendingOwner,omitempty"` //	address
}

func (x *NewPendingOwner) Reset() {
	*x = NewPendingOwner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TUSD_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewPendingOwner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewPendingOwner) ProtoMessage() {}

func (x *NewPendingOwner) ProtoReflect() protoreflect.Message {
	mi := &file_TUSD_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewPendingOwner.ProtoReflect.Descriptor instead.
func (*NewPendingOwner) Descriptor() ([]byte, []int) {
	return file_TUSD_proto_rawDescGZIP(), []int{2}
}

func (x *NewPendingOwner) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *NewPendingOwner) GetCurrentOwner() []byte {
	if x != nil {
		return x.CurrentOwner
	}
	return nil
}

func (x *NewPendingOwner) GetPendingOwner() []byte {
	if x != nil {
		return x.PendingOwner
	}
	return nil
}

var File_TUSD_proto protoreflect.FileDescriptor

var file_TUSD_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x54, 0x55, 0x53, 0x44, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x54, 0x55,
	0x53, 0x44, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x5e, 0x0a, 0x08, 0x55, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x64, 0x12,
	0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x26, 0x0a, 0x0e, 0x49,
	0x6d, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0e, 0x49, 0x6d, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x89, 0x01, 0x0a, 0x19, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x4f, 0x77, 0x6e,
	0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x72, 0x65,
	0x64, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x24, 0x0a,
	0x0d, 0x50, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x50, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x4f, 0x77,
	0x6e, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x4e, 0x65, 0x77, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x4e, 0x65, 0x77, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x22,
	0x85, 0x01, 0x0a, 0x0f, 0x4e, 0x65, 0x77, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x4f, 0x77,
	0x6e, 0x65, 0x72, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12,
	0x22, 0x0a, 0x0c, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x4f, 0x77,
	0x6e, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x0c, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x4f, 0x77,
	0x6e, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x50, 0x65, 0x6e, 0x64, 0x69,
	0x6e, 0x67, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x42, 0x37, 0x5a, 0x35, 0x62, 0x6c, 0x65, 0x70, 0x2e,
	0x61, 0x69, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x73, 0x2f, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x64, 0x61, 0x6f, 0x2f, 0x73, 0x6d, 0x61, 0x72,
	0x74, 0x2d, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x2f, 0x54, 0x55, 0x53, 0x44,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_TUSD_proto_rawDescOnce sync.Once
	file_TUSD_proto_rawDescData = file_TUSD_proto_rawDesc
)

func file_TUSD_proto_rawDescGZIP() []byte {
	file_TUSD_proto_rawDescOnce.Do(func() {
		file_TUSD_proto_rawDescData = protoimpl.X.CompressGZIP(file_TUSD_proto_rawDescData)
	})
	return file_TUSD_proto_rawDescData
}

var file_TUSD_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_TUSD_proto_goTypes = []interface{}{
	(*Upgraded)(nil),                  // 0: TUSD.Upgraded
	(*ProxyOwnershipTransferred)(nil), // 1: TUSD.ProxyOwnershipTransferred
	(*NewPendingOwner)(nil),           // 2: TUSD.NewPendingOwner
	(*timestamppb.Timestamp)(nil),     // 3: google.protobuf.Timestamp
}
var file_TUSD_proto_depIdxs = []int32{
	3, // 0: TUSD.Upgraded.ts:type_name -> google.protobuf.Timestamp
	3, // 1: TUSD.ProxyOwnershipTransferred.ts:type_name -> google.protobuf.Timestamp
	3, // 2: TUSD.NewPendingOwner.ts:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_TUSD_proto_init() }
func file_TUSD_proto_init() {
	if File_TUSD_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_TUSD_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Upgraded); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TUSD_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProxyOwnershipTransferred); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TUSD_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewPendingOwner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_TUSD_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_TUSD_proto_goTypes,
		DependencyIndexes: file_TUSD_proto_depIdxs,
		MessageInfos:      file_TUSD_proto_msgTypes,
	}.Build()
	File_TUSD_proto = out.File
	file_TUSD_proto_rawDesc = nil
	file_TUSD_proto_goTypes = nil
	file_TUSD_proto_depIdxs = nil
}
