// Code generated - DO NOT EDIT.
// This file is a generated protocol buffer definition and any manual changes will be lost.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: MCDESM/MCDESM.proto

package MCDESM

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Deny struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts  *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Usr []byte                 `protobuf:"bytes,2,opt,name=Usr,proto3" json:"Usr,omitempty"` //	address
}

func (x *Deny) Reset() {
	*x = Deny{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MCDESM_MCDESM_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Deny) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deny) ProtoMessage() {}

func (x *Deny) ProtoReflect() protoreflect.Message {
	mi := &file_MCDESM_MCDESM_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deny.ProtoReflect.Descriptor instead.
func (*Deny) Descriptor() ([]byte, []int) {
	return file_MCDESM_MCDESM_proto_rawDescGZIP(), []int{0}
}

func (x *Deny) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *Deny) GetUsr() []byte {
	if x != nil {
		return x.Usr
	}
	return nil
}

type DenyProxy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Base  []byte                 `protobuf:"bytes,2,opt,name=Base,proto3" json:"Base,omitempty"`   //	address
	Pause []byte                 `protobuf:"bytes,3,opt,name=Pause,proto3" json:"Pause,omitempty"` //	address
}

func (x *DenyProxy) Reset() {
	*x = DenyProxy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MCDESM_MCDESM_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DenyProxy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DenyProxy) ProtoMessage() {}

func (x *DenyProxy) ProtoReflect() protoreflect.Message {
	mi := &file_MCDESM_MCDESM_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DenyProxy.ProtoReflect.Descriptor instead.
func (*DenyProxy) Descriptor() ([]byte, []int) {
	return file_MCDESM_MCDESM_proto_rawDescGZIP(), []int{1}
}

func (x *DenyProxy) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *DenyProxy) GetBase() []byte {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *DenyProxy) GetPause() []byte {
	if x != nil {
		return x.Pause
	}
	return nil
}

type File struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts   *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	What []byte                 `protobuf:"bytes,2,opt,name=What,proto3" json:"What,omitempty"` //	bytes32
	Data []byte                 `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"` //	uint256
}

func (x *File) Reset() {
	*x = File{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MCDESM_MCDESM_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_MCDESM_MCDESM_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_MCDESM_MCDESM_proto_rawDescGZIP(), []int{2}
}

func (x *File) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *File) GetWhat() []byte {
	if x != nil {
		return x.What
	}
	return nil
}

func (x *File) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type File0 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts   *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	What []byte                 `protobuf:"bytes,2,opt,name=What,proto3" json:"What,omitempty"` //	bytes32
	Data []byte                 `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"` //	address
}

func (x *File0) Reset() {
	*x = File0{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MCDESM_MCDESM_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *File0) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File0) ProtoMessage() {}

func (x *File0) ProtoReflect() protoreflect.Message {
	mi := &file_MCDESM_MCDESM_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File0.ProtoReflect.Descriptor instead.
func (*File0) Descriptor() ([]byte, []int) {
	return file_MCDESM_MCDESM_proto_rawDescGZIP(), []int{3}
}

func (x *File0) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *File0) GetWhat() []byte {
	if x != nil {
		return x.What
	}
	return nil
}

func (x *File0) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Fire struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
}

func (x *Fire) Reset() {
	*x = Fire{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MCDESM_MCDESM_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Fire) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fire) ProtoMessage() {}

func (x *Fire) ProtoReflect() protoreflect.Message {
	mi := &file_MCDESM_MCDESM_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fire.ProtoReflect.Descriptor instead.
func (*Fire) Descriptor() ([]byte, []int) {
	return file_MCDESM_MCDESM_proto_rawDescGZIP(), []int{4}
}

func (x *Fire) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

type Join struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts  *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Usr []byte                 `protobuf:"bytes,2,opt,name=Usr,proto3" json:"Usr,omitempty"` //	address
	Wad []byte                 `protobuf:"bytes,3,opt,name=Wad,proto3" json:"Wad,omitempty"` //	uint256
}

func (x *Join) Reset() {
	*x = Join{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MCDESM_MCDESM_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Join) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Join) ProtoMessage() {}

func (x *Join) ProtoReflect() protoreflect.Message {
	mi := &file_MCDESM_MCDESM_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Join.ProtoReflect.Descriptor instead.
func (*Join) Descriptor() ([]byte, []int) {
	return file_MCDESM_MCDESM_proto_rawDescGZIP(), []int{5}
}

func (x *Join) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *Join) GetUsr() []byte {
	if x != nil {
		return x.Usr
	}
	return nil
}

func (x *Join) GetWad() []byte {
	if x != nil {
		return x.Wad
	}
	return nil
}

type Rely struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts  *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Usr []byte                 `protobuf:"bytes,2,opt,name=Usr,proto3" json:"Usr,omitempty"` //	address
}

func (x *Rely) Reset() {
	*x = Rely{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MCDESM_MCDESM_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rely) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rely) ProtoMessage() {}

func (x *Rely) ProtoReflect() protoreflect.Message {
	mi := &file_MCDESM_MCDESM_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rely.ProtoReflect.Descriptor instead.
func (*Rely) Descriptor() ([]byte, []int) {
	return file_MCDESM_MCDESM_proto_rawDescGZIP(), []int{6}
}

func (x *Rely) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *Rely) GetUsr() []byte {
	if x != nil {
		return x.Usr
	}
	return nil
}

var File_MCDESM_MCDESM_proto protoreflect.FileDescriptor

var file_MCDESM_MCDESM_proto_rawDesc = []byte{
	0x0a, 0x13, 0x4d, 0x43, 0x44, 0x45, 0x53, 0x4d, 0x2f, 0x4d, 0x43, 0x44, 0x45, 0x53, 0x4d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x4d, 0x43, 0x44, 0x45, 0x53, 0x4d, 0x1a, 0x1f, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x44,
	0x0a, 0x04, 0x44, 0x65, 0x6e, 0x79, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02,
	0x74, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x73, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x03, 0x55, 0x73, 0x72, 0x22, 0x61, 0x0a, 0x09, 0x44, 0x65, 0x6e, 0x79, 0x50, 0x72, 0x6f, 0x78,
	0x79, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x42, 0x61, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x42, 0x61, 0x73,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x61, 0x75, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x05, 0x50, 0x61, 0x75, 0x73, 0x65, 0x22, 0x5a, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x12,
	0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x57,
	0x68, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x57, 0x68, 0x61, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44,
	0x61, 0x74, 0x61, 0x22, 0x5b, 0x0a, 0x05, 0x46, 0x69, 0x6c, 0x65, 0x30, 0x12, 0x2a, 0x0a, 0x02,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x57, 0x68, 0x61, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x57, 0x68, 0x61, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61,
	0x22, 0x32, 0x0a, 0x04, 0x46, 0x69, 0x72, 0x65, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x02, 0x74, 0x73, 0x22, 0x56, 0x0a, 0x04, 0x4a, 0x6f, 0x69, 0x6e, 0x12, 0x2a, 0x0a, 0x02,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x73, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x55, 0x73, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x57, 0x61,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x57, 0x61, 0x64, 0x22, 0x44, 0x0a, 0x04,
	0x52, 0x65, 0x6c, 0x79, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73,
	0x12, 0x10, 0x0a, 0x03, 0x55, 0x73, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x55,
	0x73, 0x72, 0x42, 0x39, 0x5a, 0x37, 0x62, 0x6c, 0x65, 0x70, 0x2e, 0x61, 0x69, 0x2f, 0x64, 0x61,
	0x74, 0x61, 0x2f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2f, 0x6d, 0x61,
	0x6b, 0x65, 0x72, 0x64, 0x61, 0x6f, 0x2f, 0x73, 0x6d, 0x61, 0x72, 0x74, 0x2d, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x2f, 0x4d, 0x43, 0x44, 0x45, 0x53, 0x4d, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_MCDESM_MCDESM_proto_rawDescOnce sync.Once
	file_MCDESM_MCDESM_proto_rawDescData = file_MCDESM_MCDESM_proto_rawDesc
)

func file_MCDESM_MCDESM_proto_rawDescGZIP() []byte {
	file_MCDESM_MCDESM_proto_rawDescOnce.Do(func() {
		file_MCDESM_MCDESM_proto_rawDescData = protoimpl.X.CompressGZIP(file_MCDESM_MCDESM_proto_rawDescData)
	})
	return file_MCDESM_MCDESM_proto_rawDescData
}

var file_MCDESM_MCDESM_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_MCDESM_MCDESM_proto_goTypes = []interface{}{
	(*Deny)(nil),                  // 0: MCDESM.Deny
	(*DenyProxy)(nil),             // 1: MCDESM.DenyProxy
	(*File)(nil),                  // 2: MCDESM.File
	(*File0)(nil),                 // 3: MCDESM.File0
	(*Fire)(nil),                  // 4: MCDESM.Fire
	(*Join)(nil),                  // 5: MCDESM.Join
	(*Rely)(nil),                  // 6: MCDESM.Rely
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_MCDESM_MCDESM_proto_depIdxs = []int32{
	7, // 0: MCDESM.Deny.ts:type_name -> google.protobuf.Timestamp
	7, // 1: MCDESM.DenyProxy.ts:type_name -> google.protobuf.Timestamp
	7, // 2: MCDESM.File.ts:type_name -> google.protobuf.Timestamp
	7, // 3: MCDESM.File0.ts:type_name -> google.protobuf.Timestamp
	7, // 4: MCDESM.Fire.ts:type_name -> google.protobuf.Timestamp
	7, // 5: MCDESM.Join.ts:type_name -> google.protobuf.Timestamp
	7, // 6: MCDESM.Rely.ts:type_name -> google.protobuf.Timestamp
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_MCDESM_MCDESM_proto_init() }
func file_MCDESM_MCDESM_proto_init() {
	if File_MCDESM_MCDESM_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_MCDESM_MCDESM_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Deny); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MCDESM_MCDESM_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DenyProxy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MCDESM_MCDESM_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*File); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MCDESM_MCDESM_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*File0); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MCDESM_MCDESM_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Fire); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MCDESM_MCDESM_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Join); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MCDESM_MCDESM_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rely); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_MCDESM_MCDESM_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_MCDESM_MCDESM_proto_goTypes,
		DependencyIndexes: file_MCDESM_MCDESM_proto_depIdxs,
		MessageInfos:      file_MCDESM_MCDESM_proto_msgTypes,
	}.Build()
	File_MCDESM_MCDESM_proto = out.File
	file_MCDESM_MCDESM_proto_rawDesc = nil
	file_MCDESM_MCDESM_proto_goTypes = nil
	file_MCDESM_MCDESM_proto_depIdxs = nil
}
