// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: flowserviceaccount.proto

package flowserviceaccount

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionFeeUpdated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	BlockNumber uint64                 `protobuf:"varint,2,opt,name=blockNumber,proto3" json:"blockNumber,omitempty"`
	TxID        []byte                 `protobuf:"bytes,3,opt,name=txID,proto3" json:"txID,omitempty"`
	LogIndex    uint64                 `protobuf:"varint,4,opt,name=logIndex,proto3" json:"logIndex,omitempty"`
	NewFee      float64                `protobuf:"fixed64,5,opt,name=newFee,proto3" json:"newFee,omitempty"`
}

func (x *TransactionFeeUpdated) Reset() {
	*x = TransactionFeeUpdated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flowserviceaccount_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransactionFeeUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionFeeUpdated) ProtoMessage() {}

func (x *TransactionFeeUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_flowserviceaccount_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionFeeUpdated.ProtoReflect.Descriptor instead.
func (*TransactionFeeUpdated) Descriptor() ([]byte, []int) {
	return file_flowserviceaccount_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionFeeUpdated) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *TransactionFeeUpdated) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *TransactionFeeUpdated) GetTxID() []byte {
	if x != nil {
		return x.TxID
	}
	return nil
}

func (x *TransactionFeeUpdated) GetLogIndex() uint64 {
	if x != nil {
		return x.LogIndex
	}
	return 0
}

func (x *TransactionFeeUpdated) GetNewFee() float64 {
	if x != nil {
		return x.NewFee
	}
	return 0
}

type AccountCreationFeeUpdated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	BlockNumber uint64                 `protobuf:"varint,2,opt,name=blockNumber,proto3" json:"blockNumber,omitempty"`
	TxID        []byte                 `protobuf:"bytes,3,opt,name=txID,proto3" json:"txID,omitempty"`
	LogIndex    uint64                 `protobuf:"varint,4,opt,name=logIndex,proto3" json:"logIndex,omitempty"`
	NewFee      float64                `protobuf:"fixed64,5,opt,name=newFee,proto3" json:"newFee,omitempty"`
}

func (x *AccountCreationFeeUpdated) Reset() {
	*x = AccountCreationFeeUpdated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flowserviceaccount_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountCreationFeeUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountCreationFeeUpdated) ProtoMessage() {}

func (x *AccountCreationFeeUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_flowserviceaccount_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountCreationFeeUpdated.ProtoReflect.Descriptor instead.
func (*AccountCreationFeeUpdated) Descriptor() ([]byte, []int) {
	return file_flowserviceaccount_proto_rawDescGZIP(), []int{1}
}

func (x *AccountCreationFeeUpdated) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *AccountCreationFeeUpdated) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *AccountCreationFeeUpdated) GetTxID() []byte {
	if x != nil {
		return x.TxID
	}
	return nil
}

func (x *AccountCreationFeeUpdated) GetLogIndex() uint64 {
	if x != nil {
		return x.LogIndex
	}
	return 0
}

func (x *AccountCreationFeeUpdated) GetNewFee() float64 {
	if x != nil {
		return x.NewFee
	}
	return 0
}

type AccountCreatorAdded struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts             *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	BlockNumber    uint64                 `protobuf:"varint,2,opt,name=blockNumber,proto3" json:"blockNumber,omitempty"`
	TxID           []byte                 `protobuf:"bytes,3,opt,name=txID,proto3" json:"txID,omitempty"`
	LogIndex       uint64                 `protobuf:"varint,4,opt,name=logIndex,proto3" json:"logIndex,omitempty"`
	AccountCreator []byte                 `protobuf:"bytes,5,opt,name=accountCreator,proto3" json:"accountCreator,omitempty"`
}

func (x *AccountCreatorAdded) Reset() {
	*x = AccountCreatorAdded{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flowserviceaccount_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountCreatorAdded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountCreatorAdded) ProtoMessage() {}

func (x *AccountCreatorAdded) ProtoReflect() protoreflect.Message {
	mi := &file_flowserviceaccount_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountCreatorAdded.ProtoReflect.Descriptor instead.
func (*AccountCreatorAdded) Descriptor() ([]byte, []int) {
	return file_flowserviceaccount_proto_rawDescGZIP(), []int{2}
}

func (x *AccountCreatorAdded) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *AccountCreatorAdded) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *AccountCreatorAdded) GetTxID() []byte {
	if x != nil {
		return x.TxID
	}
	return nil
}

func (x *AccountCreatorAdded) GetLogIndex() uint64 {
	if x != nil {
		return x.LogIndex
	}
	return 0
}

func (x *AccountCreatorAdded) GetAccountCreator() []byte {
	if x != nil {
		return x.AccountCreator
	}
	return nil
}

type AccountCreatorRemoved struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts             *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	BlockNumber    uint64                 `protobuf:"varint,2,opt,name=blockNumber,proto3" json:"blockNumber,omitempty"`
	TxID           []byte                 `protobuf:"bytes,3,opt,name=txID,proto3" json:"txID,omitempty"`
	LogIndex       uint64                 `protobuf:"varint,4,opt,name=logIndex,proto3" json:"logIndex,omitempty"`
	AccountCreator []byte                 `protobuf:"bytes,5,opt,name=accountCreator,proto3" json:"accountCreator,omitempty"`
}

func (x *AccountCreatorRemoved) Reset() {
	*x = AccountCreatorRemoved{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flowserviceaccount_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountCreatorRemoved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountCreatorRemoved) ProtoMessage() {}

func (x *AccountCreatorRemoved) ProtoReflect() protoreflect.Message {
	mi := &file_flowserviceaccount_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountCreatorRemoved.ProtoReflect.Descriptor instead.
func (*AccountCreatorRemoved) Descriptor() ([]byte, []int) {
	return file_flowserviceaccount_proto_rawDescGZIP(), []int{3}
}

func (x *AccountCreatorRemoved) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *AccountCreatorRemoved) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *AccountCreatorRemoved) GetTxID() []byte {
	if x != nil {
		return x.TxID
	}
	return nil
}

func (x *AccountCreatorRemoved) GetLogIndex() uint64 {
	if x != nil {
		return x.LogIndex
	}
	return 0
}

func (x *AccountCreatorRemoved) GetAccountCreator() []byte {
	if x != nil {
		return x.AccountCreator
	}
	return nil
}

type IsAccountCreationRestrictedUpdated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts           *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	BlockNumber  uint64                 `protobuf:"varint,2,opt,name=blockNumber,proto3" json:"blockNumber,omitempty"`
	TxID         []byte                 `protobuf:"bytes,3,opt,name=txID,proto3" json:"txID,omitempty"`
	LogIndex     uint64                 `protobuf:"varint,4,opt,name=logIndex,proto3" json:"logIndex,omitempty"`
	IsRestricted bool                   `protobuf:"varint,5,opt,name=isRestricted,proto3" json:"isRestricted,omitempty"`
}

func (x *IsAccountCreationRestrictedUpdated) Reset() {
	*x = IsAccountCreationRestrictedUpdated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flowserviceaccount_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsAccountCreationRestrictedUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsAccountCreationRestrictedUpdated) ProtoMessage() {}

func (x *IsAccountCreationRestrictedUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_flowserviceaccount_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsAccountCreationRestrictedUpdated.ProtoReflect.Descriptor instead.
func (*IsAccountCreationRestrictedUpdated) Descriptor() ([]byte, []int) {
	return file_flowserviceaccount_proto_rawDescGZIP(), []int{4}
}

func (x *IsAccountCreationRestrictedUpdated) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *IsAccountCreationRestrictedUpdated) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *IsAccountCreationRestrictedUpdated) GetTxID() []byte {
	if x != nil {
		return x.TxID
	}
	return nil
}

func (x *IsAccountCreationRestrictedUpdated) GetLogIndex() uint64 {
	if x != nil {
		return x.LogIndex
	}
	return 0
}

func (x *IsAccountCreationRestrictedUpdated) GetIsRestricted() bool {
	if x != nil {
		return x.IsRestricted
	}
	return false
}

var File_flowserviceaccount_proto protoreflect.FileDescriptor

var file_flowserviceaccount_proto_rawDesc = []byte{
	0x0a, 0x18, 0x66, 0x6c, 0x6f, 0x77, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x66, 0x6c, 0x6f, 0x77,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x1a, 0x1f,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xad, 0x01, 0x0a, 0x15, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x46,
	0x65, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x62, 0x6c, 0x6f, 0x63,
	0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x78, 0x49, 0x44, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x74, 0x78, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x6c,
	0x6f, 0x67, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x6c,
	0x6f, 0x67, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x65, 0x77, 0x46, 0x65,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x6e, 0x65, 0x77, 0x46, 0x65, 0x65, 0x22,
	0xb1, 0x01, 0x0a, 0x19, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x46, 0x65, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x12, 0x2a, 0x0a,
	0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x78, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x74, 0x78, 0x49, 0x44, 0x12,
	0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x67, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x08, 0x6c, 0x6f, 0x67, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x16, 0x0a, 0x06, 0x6e,
	0x65, 0x77, 0x46, 0x65, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x6e, 0x65, 0x77,
	0x46, 0x65, 0x65, 0x22, 0xbb, 0x01, 0x0a, 0x13, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x41, 0x64, 0x64, 0x65, 0x64, 0x12, 0x2a, 0x0a, 0x02, 0x74,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x62, 0x6c, 0x6f, 0x63, 0x6b,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x78, 0x49,
	0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x74, 0x78, 0x49, 0x44, 0x12, 0x1a, 0x0a,
	0x08, 0x6c, 0x6f, 0x67, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x08, 0x6c, 0x6f, 0x67, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x26, 0x0a, 0x0e, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x0e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x6f,
	0x72, 0x22, 0xbd, 0x01, 0x0a, 0x15, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x12, 0x2a, 0x0a, 0x02, 0x74,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x62, 0x6c, 0x6f, 0x63, 0x6b,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x78, 0x49,
	0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x74, 0x78, 0x49, 0x44, 0x12, 0x1a, 0x0a,
	0x08, 0x6c, 0x6f, 0x67, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x08, 0x6c, 0x6f, 0x67, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x26, 0x0a, 0x0e, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x0e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x6f,
	0x72, 0x22, 0xc6, 0x01, 0x0a, 0x22, 0x49, 0x73, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x65,
	0x64, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x02, 0x74, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x62, 0x6c, 0x6f, 0x63, 0x6b,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x78, 0x49, 0x44, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x74, 0x78, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f,
	0x67, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x6c, 0x6f,
	0x67, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x22, 0x0a, 0x0c, 0x69, 0x73, 0x52, 0x65, 0x73, 0x74,
	0x72, 0x69, 0x63, 0x74, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x69, 0x73,
	0x52, 0x65, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x65, 0x64, 0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x61, 0x6b, 0x6a, 0x69, 0x2d, 0x6e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x73, 0x2f, 0x66, 0x6c, 0x6f, 0x77, 0x2f, 0x66, 0x6c, 0x6f, 0x77, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_flowserviceaccount_proto_rawDescOnce sync.Once
	file_flowserviceaccount_proto_rawDescData = file_flowserviceaccount_proto_rawDesc
)

func file_flowserviceaccount_proto_rawDescGZIP() []byte {
	file_flowserviceaccount_proto_rawDescOnce.Do(func() {
		file_flowserviceaccount_proto_rawDescData = protoimpl.X.CompressGZIP(file_flowserviceaccount_proto_rawDescData)
	})
	return file_flowserviceaccount_proto_rawDescData
}

var file_flowserviceaccount_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_flowserviceaccount_proto_goTypes = []interface{}{
	(*TransactionFeeUpdated)(nil),              // 0: flowserviceaccount.TransactionFeeUpdated
	(*AccountCreationFeeUpdated)(nil),          // 1: flowserviceaccount.AccountCreationFeeUpdated
	(*AccountCreatorAdded)(nil),                // 2: flowserviceaccount.AccountCreatorAdded
	(*AccountCreatorRemoved)(nil),              // 3: flowserviceaccount.AccountCreatorRemoved
	(*IsAccountCreationRestrictedUpdated)(nil), // 4: flowserviceaccount.IsAccountCreationRestrictedUpdated
	(*timestamppb.Timestamp)(nil),              // 5: google.protobuf.Timestamp
}
var file_flowserviceaccount_proto_depIdxs = []int32{
	5, // 0: flowserviceaccount.TransactionFeeUpdated.ts:type_name -> google.protobuf.Timestamp
	5, // 1: flowserviceaccount.AccountCreationFeeUpdated.ts:type_name -> google.protobuf.Timestamp
	5, // 2: flowserviceaccount.AccountCreatorAdded.ts:type_name -> google.protobuf.Timestamp
	5, // 3: flowserviceaccount.AccountCreatorRemoved.ts:type_name -> google.protobuf.Timestamp
	5, // 4: flowserviceaccount.IsAccountCreationRestrictedUpdated.ts:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_flowserviceaccount_proto_init() }
func file_flowserviceaccount_proto_init() {
	if File_flowserviceaccount_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_flowserviceaccount_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransactionFeeUpdated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flowserviceaccount_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountCreationFeeUpdated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flowserviceaccount_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountCreatorAdded); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flowserviceaccount_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountCreatorRemoved); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flowserviceaccount_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsAccountCreationRestrictedUpdated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_flowserviceaccount_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_flowserviceaccount_proto_goTypes,
		DependencyIndexes: file_flowserviceaccount_proto_depIdxs,
		MessageInfos:      file_flowserviceaccount_proto_msgTypes,
	}.Build()
	File_flowserviceaccount_proto = out.File
	file_flowserviceaccount_proto_rawDesc = nil
	file_flowserviceaccount_proto_goTypes = nil
	file_flowserviceaccount_proto_depIdxs = nil
}
