syntax = "proto3";

package pair;

import "google/protobuf/timestamp.proto";
import "lotus/lotus.proto";

option go_package = "github.com/trylotus/connectors/pancakeswapv2/pair";

message Approval {
  option (lotus.composite).index = {
    unique: true
    type: INDEX_TYPE_ORDERED
    fields: [
      "block_hash",
      "log_index",
      "ts"
    ]
  };

  google.protobuf.Timestamp ts = 1;
  uint64 block_number = 2 [(lotus.index) = {type: INDEX_TYPE_ORDERED}];
  bytes block_hash = 3 [(lotus.bytes) = {format: FORMAT_TYPE_HEX}]; // Hash
  bytes tx_hash = 4 [
    (lotus.bytes) = {format: FORMAT_TYPE_HEX},
    (lotus.index) = {type: INDEX_TYPE_ORDERED}
  ]; // Hash
  uint64 log_index = 5;
  bytes pair = 6 [(lotus.bytes) = {format: FORMAT_TYPE_HEX}]; // Address
  bytes owner = 7 [(lotus.bytes) = {format: FORMAT_TYPE_HEX}]; // Address
  bytes spender = 8 [(lotus.bytes) = {format: FORMAT_TYPE_HEX}]; // Address
  string value = 9 [(lotus.numeric) = {}];
}

message Burn {
  option (lotus.composite).index = {
    unique: true
    type: INDEX_TYPE_ORDERED
    fields: [
      "block_hash",
      "log_index",
      "ts"
    ]
  };

  google.protobuf.Timestamp ts = 1;
  uint64 block_number = 2 [(lotus.index) = {type: INDEX_TYPE_ORDERED}];
  bytes block_hash = 3 [(lotus.bytes) = {format: FORMAT_TYPE_HEX}]; // Hash
  bytes tx_hash = 4 [
    (lotus.bytes) = {format: FORMAT_TYPE_HEX},
    (lotus.index) = {type: INDEX_TYPE_ORDERED}
  ]; // Hash
  uint64 log_index = 5;
  bytes pair = 6 [(lotus.bytes) = {format: FORMAT_TYPE_HEX}]; // Address
  bytes sender = 7 [(lotus.bytes) = {format: FORMAT_TYPE_HEX}]; // Address
  string amount0 = 8 [(lotus.numeric) = {}];
  string amount1 = 9 [(lotus.numeric) = {}];
  bytes to = 10 [(lotus.bytes) = {format: FORMAT_TYPE_HEX}]; // Address
}

message Mint {
  option (lotus.composite).index = {
    unique: true
    type: INDEX_TYPE_ORDERED
    fields: [
      "block_hash",
      "log_index",
      "ts"
    ]
  };

  google.protobuf.Timestamp ts = 1;
  uint64 block_number = 2 [(lotus.index) = {type: INDEX_TYPE_ORDERED}];
  bytes block_hash = 3 [(lotus.bytes) = {format: FORMAT_TYPE_HEX}]; // Hash
  bytes tx_hash = 4 [
    (lotus.bytes) = {format: FORMAT_TYPE_HEX},
    (lotus.index) = {type: INDEX_TYPE_ORDERED}
  ]; // Hash
  uint64 log_index = 5;
  bytes pair = 6 [(lotus.bytes) = {format: FORMAT_TYPE_HEX}]; // Address
  bytes sender = 7 [(lotus.bytes) = {format: FORMAT_TYPE_HEX}]; // Address
  string amount0 = 8 [(lotus.numeric) = {}];
  string amount1 = 9 [(lotus.numeric) = {}];
}

message Swap {
  option (lotus.composite).index = {
    unique: true
    type: INDEX_TYPE_ORDERED
    fields: [
      "block_hash",
      "log_index",
      "ts"
    ]
  };

  google.protobuf.Timestamp ts = 1;
  uint64 block_number = 2 [(lotus.index) = {type: INDEX_TYPE_ORDERED}];
  bytes block_hash = 3 [(lotus.bytes) = {format: FORMAT_TYPE_HEX}]; // Hash
  bytes tx_hash = 4 [
    (lotus.bytes) = {format: FORMAT_TYPE_HEX},
    (lotus.index) = {type: INDEX_TYPE_ORDERED}
  ]; // Hash
  uint64 log_index = 5;
  bytes pair = 6 [(lotus.bytes) = {format: FORMAT_TYPE_HEX}]; // Address
  bytes sender = 7 [(lotus.bytes) = {format: FORMAT_TYPE_HEX}]; // Address
  string amount0_in = 8 [(lotus.numeric) = {}];
  string amount1_in = 9 [(lotus.numeric) = {}];
  string amount0_out = 10 [(lotus.numeric) = {}];
  string amount1_out = 11 [(lotus.numeric) = {}];
  bytes to = 12 [(lotus.bytes) = {format: FORMAT_TYPE_HEX}]; // Address
}

message Sync {
  option (lotus.composite).index = {
    unique: true
    type: INDEX_TYPE_ORDERED
    fields: [
      "block_hash",
      "log_index",
      "ts"
    ]
  };

  google.protobuf.Timestamp ts = 1;
  uint64 block_number = 2 [(lotus.index) = {type: INDEX_TYPE_ORDERED}];
  bytes block_hash = 3 [(lotus.bytes) = {format: FORMAT_TYPE_HEX}]; // Hash
  bytes tx_hash = 4 [
    (lotus.bytes) = {format: FORMAT_TYPE_HEX},
    (lotus.index) = {type: INDEX_TYPE_ORDERED}
  ]; // Hash
  uint64 log_index = 5;
  bytes pair = 6 [(lotus.bytes) = {format: FORMAT_TYPE_HEX}]; // Address
  string reserve0 = 7 [(lotus.numeric) = {}];
  string reserve1 = 8 [(lotus.numeric) = {}];
}

message Transfer {
  option (lotus.composite).index = {
    unique: true
    type: INDEX_TYPE_ORDERED
    fields: [
      "block_hash",
      "log_index",
      "ts"
    ]
  };

  google.protobuf.Timestamp ts = 1;
  uint64 block_number = 2 [(lotus.index) = {type: INDEX_TYPE_ORDERED}];
  bytes block_hash = 3 [(lotus.bytes) = {format: FORMAT_TYPE_HEX}]; // Hash
  bytes tx_hash = 4 [
    (lotus.bytes) = {format: FORMAT_TYPE_HEX},
    (lotus.index) = {type: INDEX_TYPE_ORDERED}
  ]; // Hash
  uint64 log_index = 5;
  bytes pair = 6 [(lotus.bytes) = {format: FORMAT_TYPE_HEX}]; // Address
  bytes from = 7 [(lotus.bytes) = {format: FORMAT_TYPE_HEX}]; // Address
  bytes to = 8 [(lotus.bytes) = {format: FORMAT_TYPE_HEX}]; // Address
  string value = 9 [(lotus.numeric) = {}];
}
