package usercontract0

import (
	"fmt"
	"strings"

	"github.com/ethereum/go-ethereum/accounts/abi"
	ethcommon "github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"
	"github.com/rs/zerolog/log"
	"github.com/trylotus/go-connector/common"
	"github.com/trylotus/go-connector/source/evm"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/known/timestamppb"
)

type SmartContract struct {
	Addr ethcommon.Address
	Abi  abi.ABI
}

var _ evm.SmartContract = (*SmartContract)(nil)

func NewContract(address ethcommon.Address) *SmartContract {
	contractAbi, err := abi.JSON(strings.NewReader(Usercontract0MetaData.ABI))
	if err != nil {
		log.Fatal().Err(err).Msg("failed to read contract ABI")
	}
	return &SmartContract{Addr: address, Abi: contractAbi}
}

func (c *SmartContract) Address() ethcommon.Address {
	return c.Addr
}

func (c *SmartContract) Message(vLog types.Log, ts *timestamppb.Timestamp) (proto.Message, error) {
	ev, err := c.Abi.EventByID(vLog.Topics[0])
	if err != nil {
		return nil, fmt.Errorf("no event with id %s: %w", vLog.Topics[0].Hex(), err)
	}
	switch ev.Name {

/* Code generated by https://github.com/trylotus/connector-bot. DO NOT EDIT */



case "NewMutualLike":
	event := new(Usercontract0NewMutualLike)
	if err := common.UnpackLog(c.Abi, event, ev.Name, vLog); err != nil {
		return nil, fmt.Errorf("error unpacking event: %s", ev.Name)
	}
	protoMsg := &NewMutualLike{
		Ts:          ts,
		BlockNumber: vLog.BlockNumber,
		TxHash:      vLog.TxHash.Bytes(),
		LogIndex:       uint64(vLog.Index),

		MyId: event.MyId.String(),
		TargetId: event.TargetId.String(),
	}


	return protoMsg, nil


case "Post":
	event := new(Usercontract0Post)
	if err := common.UnpackLog(c.Abi, event, ev.Name, vLog); err != nil {
		return nil, fmt.Errorf("error unpacking event: %s", ev.Name)
	}
	protoMsg := &Post{
		Ts:          ts,
		BlockNumber: vLog.BlockNumber,
		TxHash:      vLog.TxHash.Bytes(),
		LogIndex:       uint64(vLog.Index),

		PostId: event.PostId.String(),
		Poster: event.Poster.Bytes(),
	}


	return protoMsg, nil


case "RoleGranted":
	event := new(Usercontract0RoleGranted)
	if err := common.UnpackLog(c.Abi, event, ev.Name, vLog); err != nil {
		return nil, fmt.Errorf("error unpacking event: %s", ev.Name)
	}
	protoMsg := &RoleGranted{
		Ts:          ts,
		BlockNumber: vLog.BlockNumber,
		TxHash:      vLog.TxHash.Bytes(),
		LogIndex:       uint64(vLog.Index),

		Account: event.Account.Bytes(),
		Role: event.Role[:],
		Sender: event.Sender.Bytes(),
	}


	return protoMsg, nil


case "RoleRevoked":
	event := new(Usercontract0RoleRevoked)
	if err := common.UnpackLog(c.Abi, event, ev.Name, vLog); err != nil {
		return nil, fmt.Errorf("error unpacking event: %s", ev.Name)
	}
	protoMsg := &RoleRevoked{
		Ts:          ts,
		BlockNumber: vLog.BlockNumber,
		TxHash:      vLog.TxHash.Bytes(),
		LogIndex:       uint64(vLog.Index),

		Account: event.Account.Bytes(),
		Role: event.Role[:],
		Sender: event.Sender.Bytes(),
	}


	return protoMsg, nil


case "SBTUpdated":
	event := new(Usercontract0SBTUpdated)
	if err := common.UnpackLog(c.Abi, event, ev.Name, vLog); err != nil {
		return nil, fmt.Errorf("error unpacking event: %s", ev.Name)
	}
	protoMsg := &SBTUpdated{
		Ts:          ts,
		BlockNumber: vLog.BlockNumber,
		TxHash:      vLog.TxHash.Bytes(),
		LogIndex:       uint64(vLog.Index),

		PostId: event.PostId.String(),
	}


	return protoMsg, nil


case "Streak":
	event := new(Usercontract0Streak)
	if err := common.UnpackLog(c.Abi, event, ev.Name, vLog); err != nil {
		return nil, fmt.Errorf("error unpacking event: %s", ev.Name)
	}
	protoMsg := &Streak{
		Ts:          ts,
		BlockNumber: vLog.BlockNumber,
		TxHash:      vLog.TxHash.Bytes(),
		LogIndex:       uint64(vLog.Index),

		Streak: event.Streak.String(),
		UserId: event.UserId.String(),
	}


	return protoMsg, nil


case "Initialized":
	event := new(Usercontract0Initialized)
	if err := common.UnpackLog(c.Abi, event, ev.Name, vLog); err != nil {
		return nil, fmt.Errorf("error unpacking event: %s", ev.Name)
	}
	protoMsg := &Initialized{
		Ts:          ts,
		BlockNumber: vLog.BlockNumber,
		TxHash:      vLog.TxHash.Bytes(),
		LogIndex:       uint64(vLog.Index),

		Version: uint64(event.Version),
	}


	return protoMsg, nil


case "NewGoodVibes":
	event := new(Usercontract0NewGoodVibes)
	if err := common.UnpackLog(c.Abi, event, ev.Name, vLog); err != nil {
		return nil, fmt.Errorf("error unpacking event: %s", ev.Name)
	}
	protoMsg := &NewGoodVibes{
		Ts:          ts,
		BlockNumber: vLog.BlockNumber,
		TxHash:      vLog.TxHash.Bytes(),
		LogIndex:       uint64(vLog.Index),

		PostId: event.PostId.String(),
	}


	return protoMsg, nil


case "SaveStreak":
	event := new(Usercontract0SaveStreak)
	if err := common.UnpackLog(c.Abi, event, ev.Name, vLog); err != nil {
		return nil, fmt.Errorf("error unpacking event: %s", ev.Name)
	}
	protoMsg := &SaveStreak{
		Ts:          ts,
		BlockNumber: vLog.BlockNumber,
		TxHash:      vLog.TxHash.Bytes(),
		LogIndex:       uint64(vLog.Index),

		Streak: event.Streak.String(),
		UserId: event.UserId.String(),
	}


	return protoMsg, nil


case "Swiped":
	event := new(Usercontract0Swiped)
	if err := common.UnpackLog(c.Abi, event, ev.Name, vLog); err != nil {
		return nil, fmt.Errorf("error unpacking event: %s", ev.Name)
	}
	protoMsg := &Swiped{
		Ts:          ts,
		BlockNumber: vLog.BlockNumber,
		TxHash:      vLog.TxHash.Bytes(),
		LogIndex:       uint64(vLog.Index),

		CardId: event.CardId.String(),
		Sender: event.Sender.Bytes(),
		SwipedUserId: event.SwipedUserId.String(),
	}


	return protoMsg, nil


case "PaidDM":
	event := new(Usercontract0PaidDM)
	if err := common.UnpackLog(c.Abi, event, ev.Name, vLog); err != nil {
		return nil, fmt.Errorf("error unpacking event: %s", ev.Name)
	}
	protoMsg := &PaidDM{
		Ts:          ts,
		BlockNumber: vLog.BlockNumber,
		TxHash:      vLog.TxHash.Bytes(),
		LogIndex:       uint64(vLog.Index),

		Amount: event.Amount.String(),
		Denom: event.Denom.String(),
		UserId: event.UserId.String(),
	}


	return protoMsg, nil


case "RoleAdminChanged":
	event := new(Usercontract0RoleAdminChanged)
	if err := common.UnpackLog(c.Abi, event, ev.Name, vLog); err != nil {
		return nil, fmt.Errorf("error unpacking event: %s", ev.Name)
	}
	protoMsg := &RoleAdminChanged{
		Ts:          ts,
		BlockNumber: vLog.BlockNumber,
		TxHash:      vLog.TxHash.Bytes(),
		LogIndex:       uint64(vLog.Index),

		NewAdminRole: event.NewAdminRole[:],
		PreviousAdminRole: event.PreviousAdminRole[:],
		Role: event.Role[:],
	}


	return protoMsg, nil



/* Code generated by https://github.com/trylotus/connector-bot. DO NOT EDIT */

	default:
		return nil, fmt.Errorf("invalid event: %s", ev.Name)
	}
}
