package pancake_pair

import (
	"fmt"
	"strings"

	"github.com/ethereum/go-ethereum/accounts/abi"
	ethcommon "github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"
	"github.com/rs/zerolog/log"
	"github.com/trylotus/go-connector/common"
	"github.com/trylotus/go-connector/source/evm"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/known/timestamppb"
)

type SmartContract struct {
	Addr ethcommon.Address
	Abi  abi.ABI
}

var _ evm.SmartContract = (*SmartContract)(nil)

func NewContract(address ethcommon.Address) *SmartContract {
	contractAbi, err := abi.JSON(strings.NewReader(PancakePairMetaData.ABI))
	if err != nil {
		log.Fatal().Err(err).Msg("failed to read contract ABI")
	}
	return &SmartContract{Addr: address, Abi: contractAbi}
}

func (c *SmartContract) Address() ethcommon.Address {
	return c.Addr
}

func (c *SmartContract) Message(vLog types.Log, ts *timestamppb.Timestamp) (proto.Message, error) {
	ev, err := c.Abi.EventByID(vLog.Topics[0])
	if err != nil {
		return nil, fmt.Errorf("no event with id %s: %w", vLog.Topics[0].Hex(), err)
	}
	switch ev.Name {

/* Code generated by https://github.com/trylotus/connector-bot. DO NOT EDIT */



case "Approval":
	event := new(PancakePairApproval)
	if err := common.UnpackLog(c.Abi, event, ev.Name, vLog); err != nil {
		return nil, fmt.Errorf("error unpacking event: %s", ev.Name)
	}
	protoMsg := &Approval{
		Ts:          ts,
		BlockNumber: vLog.BlockNumber,
		BlockHash:   vLog.BlockHash.Bytes(),
		TxHash:      vLog.TxHash.Bytes(),
		LogIndex:       uint64(vLog.Index),

		Owner: event.Owner.Bytes(),
		Spender: event.Spender.Bytes(),
		Value: event.Value.String(),
	}


	return protoMsg, nil


case "Burn":
	event := new(PancakePairBurn)
	if err := common.UnpackLog(c.Abi, event, ev.Name, vLog); err != nil {
		return nil, fmt.Errorf("error unpacking event: %s", ev.Name)
	}
	protoMsg := &Burn{
		Ts:          ts,
		BlockNumber: vLog.BlockNumber,
		BlockHash:   vLog.BlockHash.Bytes(),
		TxHash:      vLog.TxHash.Bytes(),
		LogIndex:       uint64(vLog.Index),

		Amount0: event.Amount0.String(),
		Amount1: event.Amount1.String(),
		Sender: event.Sender.Bytes(),
		To: event.To.Bytes(),
	}


	return protoMsg, nil


case "Mint":
	event := new(PancakePairMint)
	if err := common.UnpackLog(c.Abi, event, ev.Name, vLog); err != nil {
		return nil, fmt.Errorf("error unpacking event: %s", ev.Name)
	}
	protoMsg := &Mint{
		Ts:          ts,
		BlockNumber: vLog.BlockNumber,
		BlockHash:   vLog.BlockHash.Bytes(),
		TxHash:      vLog.TxHash.Bytes(),
		LogIndex:       uint64(vLog.Index),

		Amount0: event.Amount0.String(),
		Amount1: event.Amount1.String(),
		Sender: event.Sender.Bytes(),
	}


	return protoMsg, nil


case "Swap":
	event := new(PancakePairSwap)
	if err := common.UnpackLog(c.Abi, event, ev.Name, vLog); err != nil {
		return nil, fmt.Errorf("error unpacking event: %s", ev.Name)
	}
	protoMsg := &Swap{
		Ts:          ts,
		BlockNumber: vLog.BlockNumber,
		BlockHash:   vLog.BlockHash.Bytes(),
		TxHash:      vLog.TxHash.Bytes(),
		LogIndex:       uint64(vLog.Index),

		Amount0In: event.Amount0In.String(),
		Amount0Out: event.Amount0Out.String(),
		Amount1In: event.Amount1In.String(),
		Amount1Out: event.Amount1Out.String(),
		Sender: event.Sender.Bytes(),
		To: event.To.Bytes(),
	}


	return protoMsg, nil


case "Sync":
	event := new(PancakePairSync)
	if err := common.UnpackLog(c.Abi, event, ev.Name, vLog); err != nil {
		return nil, fmt.Errorf("error unpacking event: %s", ev.Name)
	}
	protoMsg := &Sync{
		Ts:          ts,
		BlockNumber: vLog.BlockNumber,
		BlockHash:   vLog.BlockHash.Bytes(),
		TxHash:      vLog.TxHash.Bytes(),
		LogIndex:       uint64(vLog.Index),

		Reserve0: event.Reserve0.String(),
		Reserve1: event.Reserve1.String(),
	}


	return protoMsg, nil


case "Transfer":
	event := new(PancakePairTransfer)
	if err := common.UnpackLog(c.Abi, event, ev.Name, vLog); err != nil {
		return nil, fmt.Errorf("error unpacking event: %s", ev.Name)
	}
	protoMsg := &Transfer{
		Ts:          ts,
		BlockNumber: vLog.BlockNumber,
		BlockHash:   vLog.BlockHash.Bytes(),
		TxHash:      vLog.TxHash.Bytes(),
		LogIndex:       uint64(vLog.Index),

		From: event.From.Bytes(),
		To: event.To.Bytes(),
		Value: event.Value.String(),
	}


	return protoMsg, nil



/* Code generated by https://github.com/trylotus/connector-bot. DO NOT EDIT */

	default:
		return nil, fmt.Errorf("invalid event: %s", ev.Name)
	}
}
