// Code generated - DO NOT EDIT.
// This file is a generated protocol buffer definition and any manual changes will be lost.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: FlipperMom/FlipperMom.proto

package FlipperMom

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Deny struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts   *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Flip []byte                 `protobuf:"bytes,2,opt,name=Flip,proto3" json:"Flip,omitempty"` //	address
	Cat  []byte                 `protobuf:"bytes,3,opt,name=Cat,proto3" json:"Cat,omitempty"`   //	address
}

func (x *Deny) Reset() {
	*x = Deny{}
	if protoimpl.UnsafeEnabled {
		mi := &file_FlipperMom_FlipperMom_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Deny) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deny) ProtoMessage() {}

func (x *Deny) ProtoReflect() protoreflect.Message {
	mi := &file_FlipperMom_FlipperMom_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deny.ProtoReflect.Descriptor instead.
func (*Deny) Descriptor() ([]byte, []int) {
	return file_FlipperMom_FlipperMom_proto_rawDescGZIP(), []int{0}
}

func (x *Deny) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *Deny) GetFlip() []byte {
	if x != nil {
		return x.Flip
	}
	return nil
}

func (x *Deny) GetCat() []byte {
	if x != nil {
		return x.Cat
	}
	return nil
}

type Rely struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts   *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Flip []byte                 `protobuf:"bytes,2,opt,name=Flip,proto3" json:"Flip,omitempty"` //	address
	Usr  []byte                 `protobuf:"bytes,3,opt,name=Usr,proto3" json:"Usr,omitempty"`   //	address
}

func (x *Rely) Reset() {
	*x = Rely{}
	if protoimpl.UnsafeEnabled {
		mi := &file_FlipperMom_FlipperMom_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rely) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rely) ProtoMessage() {}

func (x *Rely) ProtoReflect() protoreflect.Message {
	mi := &file_FlipperMom_FlipperMom_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rely.ProtoReflect.Descriptor instead.
func (*Rely) Descriptor() ([]byte, []int) {
	return file_FlipperMom_FlipperMom_proto_rawDescGZIP(), []int{1}
}

func (x *Rely) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *Rely) GetFlip() []byte {
	if x != nil {
		return x.Flip
	}
	return nil
}

func (x *Rely) GetUsr() []byte {
	if x != nil {
		return x.Usr
	}
	return nil
}

type SetAuthority struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts           *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	OldAuthority []byte                 `protobuf:"bytes,2,opt,name=OldAuthority,proto3" json:"OldAuthority,omitempty"` //	address
	NewAuthority []byte                 `protobuf:"bytes,3,opt,name=NewAuthority,proto3" json:"NewAuthority,omitempty"` //	address
}

func (x *SetAuthority) Reset() {
	*x = SetAuthority{}
	if protoimpl.UnsafeEnabled {
		mi := &file_FlipperMom_FlipperMom_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetAuthority) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAuthority) ProtoMessage() {}

func (x *SetAuthority) ProtoReflect() protoreflect.Message {
	mi := &file_FlipperMom_FlipperMom_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAuthority.ProtoReflect.Descriptor instead.
func (*SetAuthority) Descriptor() ([]byte, []int) {
	return file_FlipperMom_FlipperMom_proto_rawDescGZIP(), []int{2}
}

func (x *SetAuthority) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *SetAuthority) GetOldAuthority() []byte {
	if x != nil {
		return x.OldAuthority
	}
	return nil
}

func (x *SetAuthority) GetNewAuthority() []byte {
	if x != nil {
		return x.NewAuthority
	}
	return nil
}

type SetOwner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts       *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	OldOwner []byte                 `protobuf:"bytes,2,opt,name=OldOwner,proto3" json:"OldOwner,omitempty"` //	address
	NewOwner []byte                 `protobuf:"bytes,3,opt,name=NewOwner,proto3" json:"NewOwner,omitempty"` //	address
}

func (x *SetOwner) Reset() {
	*x = SetOwner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_FlipperMom_FlipperMom_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetOwner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOwner) ProtoMessage() {}

func (x *SetOwner) ProtoReflect() protoreflect.Message {
	mi := &file_FlipperMom_FlipperMom_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOwner.ProtoReflect.Descriptor instead.
func (*SetOwner) Descriptor() ([]byte, []int) {
	return file_FlipperMom_FlipperMom_proto_rawDescGZIP(), []int{3}
}

func (x *SetOwner) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *SetOwner) GetOldOwner() []byte {
	if x != nil {
		return x.OldOwner
	}
	return nil
}

func (x *SetOwner) GetNewOwner() []byte {
	if x != nil {
		return x.NewOwner
	}
	return nil
}

var File_FlipperMom_FlipperMom_proto protoreflect.FileDescriptor

var file_FlipperMom_FlipperMom_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x46, 0x6c, 0x69, 0x70, 0x70, 0x65, 0x72, 0x4d, 0x6f, 0x6d, 0x2f, 0x46, 0x6c, 0x69,
	0x70, 0x70, 0x65, 0x72, 0x4d, 0x6f, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x46,
	0x6c, 0x69, 0x70, 0x70, 0x65, 0x72, 0x4d, 0x6f, 0x6d, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x58, 0x0a, 0x04, 0x44, 0x65,
	0x6e, 0x79, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x46, 0x6c, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x46, 0x6c,
	0x69, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x43, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x03, 0x43, 0x61, 0x74, 0x22, 0x58, 0x0a, 0x04, 0x52, 0x65, 0x6c, 0x79, 0x12, 0x2a, 0x0a, 0x02,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x46, 0x6c, 0x69, 0x70,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x46, 0x6c, 0x69, 0x70, 0x12, 0x10, 0x0a, 0x03,
	0x55, 0x73, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x55, 0x73, 0x72, 0x22, 0x82,
	0x01, 0x0a, 0x0c, 0x53, 0x65, 0x74, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12,
	0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x4f,
	0x6c, 0x64, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x0c, 0x4f, 0x6c, 0x64, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12,
	0x22, 0x0a, 0x0c, 0x4e, 0x65, 0x77, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x4e, 0x65, 0x77, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x69, 0x74, 0x79, 0x22, 0x6e, 0x0a, 0x08, 0x53, 0x65, 0x74, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x12,
	0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x4f,
	0x6c, 0x64, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x4f,
	0x6c, 0x64, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x4e, 0x65, 0x77, 0x4f, 0x77,
	0x6e, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x4e, 0x65, 0x77, 0x4f, 0x77,
	0x6e, 0x65, 0x72, 0x42, 0x3d, 0x5a, 0x3b, 0x62, 0x6c, 0x65, 0x70, 0x2e, 0x61, 0x69, 0x2f, 0x64,
	0x61, 0x74, 0x61, 0x2f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2f, 0x6d,
	0x61, 0x6b, 0x65, 0x72, 0x64, 0x61, 0x6f, 0x2f, 0x73, 0x6d, 0x61, 0x72, 0x74, 0x2d, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x2f, 0x46, 0x6c, 0x69, 0x70, 0x70, 0x65, 0x72, 0x4d,
	0x6f, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_FlipperMom_FlipperMom_proto_rawDescOnce sync.Once
	file_FlipperMom_FlipperMom_proto_rawDescData = file_FlipperMom_FlipperMom_proto_rawDesc
)

func file_FlipperMom_FlipperMom_proto_rawDescGZIP() []byte {
	file_FlipperMom_FlipperMom_proto_rawDescOnce.Do(func() {
		file_FlipperMom_FlipperMom_proto_rawDescData = protoimpl.X.CompressGZIP(file_FlipperMom_FlipperMom_proto_rawDescData)
	})
	return file_FlipperMom_FlipperMom_proto_rawDescData
}

var file_FlipperMom_FlipperMom_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_FlipperMom_FlipperMom_proto_goTypes = []interface{}{
	(*Deny)(nil),                  // 0: FlipperMom.Deny
	(*Rely)(nil),                  // 1: FlipperMom.Rely
	(*SetAuthority)(nil),          // 2: FlipperMom.SetAuthority
	(*SetOwner)(nil),              // 3: FlipperMom.SetOwner
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_FlipperMom_FlipperMom_proto_depIdxs = []int32{
	4, // 0: FlipperMom.Deny.ts:type_name -> google.protobuf.Timestamp
	4, // 1: FlipperMom.Rely.ts:type_name -> google.protobuf.Timestamp
	4, // 2: FlipperMom.SetAuthority.ts:type_name -> google.protobuf.Timestamp
	4, // 3: FlipperMom.SetOwner.ts:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_FlipperMom_FlipperMom_proto_init() }
func file_FlipperMom_FlipperMom_proto_init() {
	if File_FlipperMom_FlipperMom_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_FlipperMom_FlipperMom_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Deny); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_FlipperMom_FlipperMom_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rely); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_FlipperMom_FlipperMom_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetAuthority); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_FlipperMom_FlipperMom_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetOwner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_FlipperMom_FlipperMom_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_FlipperMom_FlipperMom_proto_goTypes,
		DependencyIndexes: file_FlipperMom_FlipperMom_proto_depIdxs,
		MessageInfos:      file_FlipperMom_FlipperMom_proto_msgTypes,
	}.Build()
	File_FlipperMom_FlipperMom_proto = out.File
	file_FlipperMom_FlipperMom_proto_rawDesc = nil
	file_FlipperMom_FlipperMom_proto_goTypes = nil
	file_FlipperMom_FlipperMom_proto_depIdxs = nil
}
