// Code generated - DO NOT EDIT.
// This file is a generated protocol buffer definition and any manual changes will be lost.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: DSR_MANAGER.proto

package DSR_MANAGER

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Exit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts  *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Dst []byte                 `protobuf:"bytes,2,opt,name=Dst,proto3" json:"Dst,omitempty"` //	address
	Wad []byte                 `protobuf:"bytes,3,opt,name=Wad,proto3" json:"Wad,omitempty"` //	uint256
}

func (x *Exit) Reset() {
	*x = Exit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_DSR_MANAGER_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Exit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exit) ProtoMessage() {}

func (x *Exit) ProtoReflect() protoreflect.Message {
	mi := &file_DSR_MANAGER_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exit.ProtoReflect.Descriptor instead.
func (*Exit) Descriptor() ([]byte, []int) {
	return file_DSR_MANAGER_proto_rawDescGZIP(), []int{0}
}

func (x *Exit) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *Exit) GetDst() []byte {
	if x != nil {
		return x.Dst
	}
	return nil
}

func (x *Exit) GetWad() []byte {
	if x != nil {
		return x.Wad
	}
	return nil
}

type Join struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts  *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Dst []byte                 `protobuf:"bytes,2,opt,name=Dst,proto3" json:"Dst,omitempty"` //	address
	Wad []byte                 `protobuf:"bytes,3,opt,name=Wad,proto3" json:"Wad,omitempty"` //	uint256
}

func (x *Join) Reset() {
	*x = Join{}
	if protoimpl.UnsafeEnabled {
		mi := &file_DSR_MANAGER_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Join) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Join) ProtoMessage() {}

func (x *Join) ProtoReflect() protoreflect.Message {
	mi := &file_DSR_MANAGER_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Join.ProtoReflect.Descriptor instead.
func (*Join) Descriptor() ([]byte, []int) {
	return file_DSR_MANAGER_proto_rawDescGZIP(), []int{1}
}

func (x *Join) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *Join) GetDst() []byte {
	if x != nil {
		return x.Dst
	}
	return nil
}

func (x *Join) GetWad() []byte {
	if x != nil {
		return x.Wad
	}
	return nil
}

var File_DSR_MANAGER_proto protoreflect.FileDescriptor

var file_DSR_MANAGER_proto_rawDesc = []byte{
	0x0a, 0x11, 0x44, 0x53, 0x52, 0x5f, 0x4d, 0x41, 0x4e, 0x41, 0x47, 0x45, 0x52, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x44, 0x53, 0x52, 0x5f, 0x4d, 0x41, 0x4e, 0x41, 0x47, 0x45, 0x52,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x56, 0x0a, 0x04, 0x45, 0x78, 0x69, 0x74, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x44, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x03, 0x44, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x57, 0x61, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x57, 0x61, 0x64, 0x22, 0x56, 0x0a, 0x04, 0x4a, 0x6f, 0x69,
	0x6e, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x10, 0x0a,
	0x03, 0x44, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x44, 0x73, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x57, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x57, 0x61,
	0x64, 0x42, 0x3e, 0x5a, 0x3c, 0x62, 0x6c, 0x65, 0x70, 0x2e, 0x61, 0x69, 0x2f, 0x64, 0x61, 0x74,
	0x61, 0x2f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2f, 0x6d, 0x61, 0x6b,
	0x65, 0x72, 0x64, 0x61, 0x6f, 0x2f, 0x73, 0x6d, 0x61, 0x72, 0x74, 0x2d, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x73, 0x2f, 0x44, 0x53, 0x52, 0x5f, 0x4d, 0x41, 0x4e, 0x41, 0x47, 0x45,
	0x52, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_DSR_MANAGER_proto_rawDescOnce sync.Once
	file_DSR_MANAGER_proto_rawDescData = file_DSR_MANAGER_proto_rawDesc
)

func file_DSR_MANAGER_proto_rawDescGZIP() []byte {
	file_DSR_MANAGER_proto_rawDescOnce.Do(func() {
		file_DSR_MANAGER_proto_rawDescData = protoimpl.X.CompressGZIP(file_DSR_MANAGER_proto_rawDescData)
	})
	return file_DSR_MANAGER_proto_rawDescData
}

var file_DSR_MANAGER_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_DSR_MANAGER_proto_goTypes = []interface{}{
	(*Exit)(nil),                  // 0: DSR_MANAGER.Exit
	(*Join)(nil),                  // 1: DSR_MANAGER.Join
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_DSR_MANAGER_proto_depIdxs = []int32{
	2, // 0: DSR_MANAGER.Exit.ts:type_name -> google.protobuf.Timestamp
	2, // 1: DSR_MANAGER.Join.ts:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_DSR_MANAGER_proto_init() }
func file_DSR_MANAGER_proto_init() {
	if File_DSR_MANAGER_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_DSR_MANAGER_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Exit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_DSR_MANAGER_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Join); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_DSR_MANAGER_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_DSR_MANAGER_proto_goTypes,
		DependencyIndexes: file_DSR_MANAGER_proto_depIdxs,
		MessageInfos:      file_DSR_MANAGER_proto_msgTypes,
	}.Build()
	File_DSR_MANAGER_proto = out.File
	file_DSR_MANAGER_proto_rawDesc = nil
	file_DSR_MANAGER_proto_goTypes = nil
	file_DSR_MANAGER_proto_depIdxs = nil
}
