syntax = "proto3";

package factory;

import "google/protobuf/timestamp.proto";
import "lotus/lotus.proto";

option go_package = "github.com/trylotus/connectors/uniswapv3/factory";

message FeeAmountEnabled {
  option (lotus.composite).index = {
    unique: true
    fields: [
      "block_hash",
      "log_index",
      "ts"
    ]
  };

  google.protobuf.Timestamp ts = 1;
  uint64 block_number = 2 [(lotus.index) = {}];
  bytes block_hash = 3 [(lotus.bytes) = {format: FORMAT_TYPE_HEX}]; // Hash
  bytes tx_hash = 4 [
    (lotus.bytes) = {format: FORMAT_TYPE_HEX},
    (lotus.index) = {}
  ]; // Hash
  uint64 log_index = 5;
  uint32 fee = 6; // uint24
  int32 tick_spacing = 7; // int24
}

message OwnerChanged {
  option (lotus.composite).index = {
    unique: true
    fields: [
      "block_hash",
      "log_index",
      "ts"
    ]
  };

  google.protobuf.Timestamp ts = 1;
  uint64 block_number = 2 [(lotus.index) = {}];
  bytes block_hash = 3 [(lotus.bytes) = {format: FORMAT_TYPE_HEX}]; // Hash
  bytes tx_hash = 4 [
    (lotus.bytes) = {format: FORMAT_TYPE_HEX},
    (lotus.index) = {}
  ]; // Hash
  uint64 log_index = 5;
  bytes old_owner = 6 [(lotus.bytes) = {format: FORMAT_TYPE_HEX}]; // Address
  bytes new_owner = 7 [(lotus.bytes) = {format: FORMAT_TYPE_HEX}]; // Address
}

message PoolCreated {
  option (lotus.composite).index = {
    unique: true
    fields: [
      "block_hash",
      "log_index",
      "ts"
    ]
  };

  option (lotus.composite).index = {
    fields: [
      "token0",
      "token1",
      "fee"
    ]
  };

  google.protobuf.Timestamp ts = 1;
  uint64 block_number = 2 [(lotus.index) = {}];
  bytes block_hash = 3 [(lotus.bytes) = {format: FORMAT_TYPE_HEX}]; // Hash
  bytes tx_hash = 4 [
    (lotus.bytes) = {format: FORMAT_TYPE_HEX},
    (lotus.index) = {}
  ]; // Hash
  uint64 log_index = 5;
  bytes token0 = 6 [(lotus.bytes) = {format: FORMAT_TYPE_HEX}]; // Address
  bytes token1 = 7 [(lotus.bytes) = {format: FORMAT_TYPE_HEX}]; // Address
  uint32 fee = 8; // uint24
  int32 tick_spacing = 9; // int24
  bytes pool = 10 [
    (lotus.bytes) = {format: FORMAT_TYPE_HEX},
    (lotus.index) = {}
  ]; // Address
  string token0_name = 11;
  string token0_symbol = 12;
  uint32 token0_decimals = 13;
  string token1_name = 14;
  string token1_symbol = 15;
  uint32 token1_decimals = 16;
}
