// Code generated - DO NOT EDIT.
// This file is a generated protocol buffer definition and any manual changes will be lost.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.2
// source: mai.proto

package mai

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Approval struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts      *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Owner   []byte                 `protobuf:"bytes,2,opt,name=Owner,proto3" json:"Owner,omitempty"`     //	address
	Spender []byte                 `protobuf:"bytes,3,opt,name=Spender,proto3" json:"Spender,omitempty"` //	address
	Value   []byte                 `protobuf:"bytes,4,opt,name=Value,proto3" json:"Value,omitempty"`     //	uint256
}

func (x *Approval) Reset() {
	*x = Approval{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mai_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Approval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Approval) ProtoMessage() {}

func (x *Approval) ProtoReflect() protoreflect.Message {
	mi := &file_mai_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Approval.ProtoReflect.Descriptor instead.
func (*Approval) Descriptor() ([]byte, []int) {
	return file_mai_proto_rawDescGZIP(), []int{0}
}

func (x *Approval) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *Approval) GetOwner() []byte {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *Approval) GetSpender() []byte {
	if x != nil {
		return x.Spender
	}
	return nil
}

func (x *Approval) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type OwnershipTransferred struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts            *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	PreviousOwner []byte                 `protobuf:"bytes,2,opt,name=PreviousOwner,proto3" json:"PreviousOwner,omitempty"` //	address
	NewOwner      []byte                 `protobuf:"bytes,3,opt,name=NewOwner,proto3" json:"NewOwner,omitempty"`           //	address
}

func (x *OwnershipTransferred) Reset() {
	*x = OwnershipTransferred{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mai_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OwnershipTransferred) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OwnershipTransferred) ProtoMessage() {}

func (x *OwnershipTransferred) ProtoReflect() protoreflect.Message {
	mi := &file_mai_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OwnershipTransferred.ProtoReflect.Descriptor instead.
func (*OwnershipTransferred) Descriptor() ([]byte, []int) {
	return file_mai_proto_rawDescGZIP(), []int{1}
}

func (x *OwnershipTransferred) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *OwnershipTransferred) GetPreviousOwner() []byte {
	if x != nil {
		return x.PreviousOwner
	}
	return nil
}

func (x *OwnershipTransferred) GetNewOwner() []byte {
	if x != nil {
		return x.NewOwner
	}
	return nil
}

type TransferVault struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts      *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	VaultID []byte                 `protobuf:"bytes,2,opt,name=VaultID,proto3" json:"VaultID,omitempty"` //	uint256
	From    []byte                 `protobuf:"bytes,3,opt,name=From,proto3" json:"From,omitempty"`       //	address
	To      []byte                 `protobuf:"bytes,4,opt,name=To,proto3" json:"To,omitempty"`           //	address
}

func (x *TransferVault) Reset() {
	*x = TransferVault{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mai_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransferVault) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferVault) ProtoMessage() {}

func (x *TransferVault) ProtoReflect() protoreflect.Message {
	mi := &file_mai_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferVault.ProtoReflect.Descriptor instead.
func (*TransferVault) Descriptor() ([]byte, []int) {
	return file_mai_proto_rawDescGZIP(), []int{2}
}

func (x *TransferVault) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *TransferVault) GetVaultID() []byte {
	if x != nil {
		return x.VaultID
	}
	return nil
}

func (x *TransferVault) GetFrom() []byte {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *TransferVault) GetTo() []byte {
	if x != nil {
		return x.To
	}
	return nil
}

type DepositCollateral struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts      *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	VaultID []byte                 `protobuf:"bytes,2,opt,name=VaultID,proto3" json:"VaultID,omitempty"` //	uint256
	Amount  []byte                 `protobuf:"bytes,3,opt,name=Amount,proto3" json:"Amount,omitempty"`   //	uint256
}

func (x *DepositCollateral) Reset() {
	*x = DepositCollateral{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mai_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepositCollateral) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositCollateral) ProtoMessage() {}

func (x *DepositCollateral) ProtoReflect() protoreflect.Message {
	mi := &file_mai_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositCollateral.ProtoReflect.Descriptor instead.
func (*DepositCollateral) Descriptor() ([]byte, []int) {
	return file_mai_proto_rawDescGZIP(), []int{3}
}

func (x *DepositCollateral) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *DepositCollateral) GetVaultID() []byte {
	if x != nil {
		return x.VaultID
	}
	return nil
}

func (x *DepositCollateral) GetAmount() []byte {
	if x != nil {
		return x.Amount
	}
	return nil
}

type WithdrawCollateral struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts      *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	VaultID []byte                 `protobuf:"bytes,2,opt,name=VaultID,proto3" json:"VaultID,omitempty"` //	uint256
	Amount  []byte                 `protobuf:"bytes,3,opt,name=Amount,proto3" json:"Amount,omitempty"`   //	uint256
}

func (x *WithdrawCollateral) Reset() {
	*x = WithdrawCollateral{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mai_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithdrawCollateral) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawCollateral) ProtoMessage() {}

func (x *WithdrawCollateral) ProtoReflect() protoreflect.Message {
	mi := &file_mai_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawCollateral.ProtoReflect.Descriptor instead.
func (*WithdrawCollateral) Descriptor() ([]byte, []int) {
	return file_mai_proto_rawDescGZIP(), []int{4}
}

func (x *WithdrawCollateral) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *WithdrawCollateral) GetVaultID() []byte {
	if x != nil {
		return x.VaultID
	}
	return nil
}

func (x *WithdrawCollateral) GetAmount() []byte {
	if x != nil {
		return x.Amount
	}
	return nil
}

type BuyRiskyVault struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	VaultID    []byte                 `protobuf:"bytes,2,opt,name=VaultID,proto3" json:"VaultID,omitempty"`       //	uint256
	Owner      []byte                 `protobuf:"bytes,3,opt,name=Owner,proto3" json:"Owner,omitempty"`           //	address
	Buyer      []byte                 `protobuf:"bytes,4,opt,name=Buyer,proto3" json:"Buyer,omitempty"`           //	address
	AmountPaid []byte                 `protobuf:"bytes,5,opt,name=AmountPaid,proto3" json:"AmountPaid,omitempty"` //	uint256
}

func (x *BuyRiskyVault) Reset() {
	*x = BuyRiskyVault{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mai_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuyRiskyVault) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyRiskyVault) ProtoMessage() {}

func (x *BuyRiskyVault) ProtoReflect() protoreflect.Message {
	mi := &file_mai_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyRiskyVault.ProtoReflect.Descriptor instead.
func (*BuyRiskyVault) Descriptor() ([]byte, []int) {
	return file_mai_proto_rawDescGZIP(), []int{5}
}

func (x *BuyRiskyVault) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *BuyRiskyVault) GetVaultID() []byte {
	if x != nil {
		return x.VaultID
	}
	return nil
}

func (x *BuyRiskyVault) GetOwner() []byte {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *BuyRiskyVault) GetBuyer() []byte {
	if x != nil {
		return x.Buyer
	}
	return nil
}

func (x *BuyRiskyVault) GetAmountPaid() []byte {
	if x != nil {
		return x.AmountPaid
	}
	return nil
}

type Transfer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	From  []byte                 `protobuf:"bytes,2,opt,name=From,proto3" json:"From,omitempty"`   //	address
	To    []byte                 `protobuf:"bytes,3,opt,name=To,proto3" json:"To,omitempty"`       //	address
	Value []byte                 `protobuf:"bytes,4,opt,name=Value,proto3" json:"Value,omitempty"` //	uint256
}

func (x *Transfer) Reset() {
	*x = Transfer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mai_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Transfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transfer) ProtoMessage() {}

func (x *Transfer) ProtoReflect() protoreflect.Message {
	mi := &file_mai_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transfer.ProtoReflect.Descriptor instead.
func (*Transfer) Descriptor() ([]byte, []int) {
	return file_mai_proto_rawDescGZIP(), []int{6}
}

func (x *Transfer) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *Transfer) GetFrom() []byte {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *Transfer) GetTo() []byte {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *Transfer) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type CreateVault struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts      *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	VaultID []byte                 `protobuf:"bytes,2,opt,name=VaultID,proto3" json:"VaultID,omitempty"` //	uint256
	Creator []byte                 `protobuf:"bytes,3,opt,name=Creator,proto3" json:"Creator,omitempty"` //	address
}

func (x *CreateVault) Reset() {
	*x = CreateVault{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mai_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateVault) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVault) ProtoMessage() {}

func (x *CreateVault) ProtoReflect() protoreflect.Message {
	mi := &file_mai_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVault.ProtoReflect.Descriptor instead.
func (*CreateVault) Descriptor() ([]byte, []int) {
	return file_mai_proto_rawDescGZIP(), []int{7}
}

func (x *CreateVault) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *CreateVault) GetVaultID() []byte {
	if x != nil {
		return x.VaultID
	}
	return nil
}

func (x *CreateVault) GetCreator() []byte {
	if x != nil {
		return x.Creator
	}
	return nil
}

type DestroyVault struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts      *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	VaultID []byte                 `protobuf:"bytes,2,opt,name=VaultID,proto3" json:"VaultID,omitempty"` //	uint256
}

func (x *DestroyVault) Reset() {
	*x = DestroyVault{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mai_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DestroyVault) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyVault) ProtoMessage() {}

func (x *DestroyVault) ProtoReflect() protoreflect.Message {
	mi := &file_mai_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyVault.ProtoReflect.Descriptor instead.
func (*DestroyVault) Descriptor() ([]byte, []int) {
	return file_mai_proto_rawDescGZIP(), []int{8}
}

func (x *DestroyVault) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *DestroyVault) GetVaultID() []byte {
	if x != nil {
		return x.VaultID
	}
	return nil
}

type BorrowToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts      *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	VaultID []byte                 `protobuf:"bytes,2,opt,name=VaultID,proto3" json:"VaultID,omitempty"` //	uint256
	Amount  []byte                 `protobuf:"bytes,3,opt,name=Amount,proto3" json:"Amount,omitempty"`   //	uint256
}

func (x *BorrowToken) Reset() {
	*x = BorrowToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mai_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BorrowToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BorrowToken) ProtoMessage() {}

func (x *BorrowToken) ProtoReflect() protoreflect.Message {
	mi := &file_mai_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BorrowToken.ProtoReflect.Descriptor instead.
func (*BorrowToken) Descriptor() ([]byte, []int) {
	return file_mai_proto_rawDescGZIP(), []int{9}
}

func (x *BorrowToken) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *BorrowToken) GetVaultID() []byte {
	if x != nil {
		return x.VaultID
	}
	return nil
}

func (x *BorrowToken) GetAmount() []byte {
	if x != nil {
		return x.Amount
	}
	return nil
}

type PayBackToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	VaultID    []byte                 `protobuf:"bytes,2,opt,name=VaultID,proto3" json:"VaultID,omitempty"`       //	uint256
	Amount     []byte                 `protobuf:"bytes,3,opt,name=Amount,proto3" json:"Amount,omitempty"`         //	uint256
	ClosingFee []byte                 `protobuf:"bytes,4,opt,name=ClosingFee,proto3" json:"ClosingFee,omitempty"` //	uint256
}

func (x *PayBackToken) Reset() {
	*x = PayBackToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mai_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayBackToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayBackToken) ProtoMessage() {}

func (x *PayBackToken) ProtoReflect() protoreflect.Message {
	mi := &file_mai_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayBackToken.ProtoReflect.Descriptor instead.
func (*PayBackToken) Descriptor() ([]byte, []int) {
	return file_mai_proto_rawDescGZIP(), []int{10}
}

func (x *PayBackToken) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *PayBackToken) GetVaultID() []byte {
	if x != nil {
		return x.VaultID
	}
	return nil
}

func (x *PayBackToken) GetAmount() []byte {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *PayBackToken) GetClosingFee() []byte {
	if x != nil {
		return x.ClosingFee
	}
	return nil
}

var File_mai_proto protoreflect.FileDescriptor

var file_mai_proto_rawDesc = []byte{
	0x0a, 0x09, 0x6d, 0x61, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6d, 0x61, 0x69,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x7c, 0x0a, 0x08, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x12, 0x2a, 0x0a,
	0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x4f, 0x77, 0x6e,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x12,
	0x18, 0x0a, 0x07, 0x53, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x07, 0x53, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0x84, 0x01, 0x0a, 0x14, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x66, 0x65, 0x72, 0x72, 0x65, 0x64, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x02, 0x74, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x50, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73,
	0x4f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x50, 0x72, 0x65,
	0x76, 0x69, 0x6f, 0x75, 0x73, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x4e, 0x65,
	0x77, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x4e, 0x65,
	0x77, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x22, 0x79, 0x0a, 0x0d, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66,
	0x65, 0x72, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x02, 0x74, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x49, 0x44, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x49, 0x44, 0x12, 0x12, 0x0a,
	0x04, 0x46, 0x72, 0x6f, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x46, 0x72, 0x6f,
	0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x54, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x54,
	0x6f, 0x22, 0x71, 0x0a, 0x11, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x43, 0x6f, 0x6c, 0x6c,
	0x61, 0x74, 0x65, 0x72, 0x61, 0x6c, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02,
	0x74, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x07, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06,
	0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x41, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x22, 0x72, 0x0a, 0x12, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77,
	0x43, 0x6f, 0x6c, 0x6c, 0x61, 0x74, 0x65, 0x72, 0x61, 0x6c, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x49,
	0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x49, 0x44,
	0x12, 0x16, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0xa1, 0x01, 0x0a, 0x0d, 0x42, 0x75, 0x79,
	0x52, 0x69, 0x73, 0x6b, 0x79, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x49,
	0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x49, 0x44,
	0x12, 0x14, 0x0a, 0x05, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x05, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x42, 0x75, 0x79, 0x65, 0x72, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x42, 0x75, 0x79, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a,
	0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x50, 0x61, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x0a, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x50, 0x61, 0x69, 0x64, 0x22, 0x70, 0x0a, 0x08,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x02, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x46, 0x72, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x54, 0x6f, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x54, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x6d,
	0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x2a, 0x0a,
	0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x61, 0x75,
	0x6c, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x56, 0x61, 0x75, 0x6c,
	0x74, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x43, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x22, 0x54, 0x0a,
	0x0c, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x2a, 0x0a,
	0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x61, 0x75,
	0x6c, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x56, 0x61, 0x75, 0x6c,
	0x74, 0x49, 0x44, 0x22, 0x6b, 0x0a, 0x0b, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x07, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x22, 0x8c, 0x01, 0x0a, 0x0c, 0x50, 0x61, 0x79, 0x42, 0x61, 0x63, 0x6b, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x18, 0x0a,
	0x07, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07,
	0x56, 0x61, 0x75, 0x6c, 0x74, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x1e, 0x0a, 0x0a, 0x43, 0x6c, 0x6f, 0x73, 0x69, 0x6e, 0x67, 0x46, 0x65, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0a, 0x43, 0x6c, 0x6f, 0x73, 0x69, 0x6e, 0x67, 0x46, 0x65, 0x65, 0x42,
	0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x61,
	0x6b, 0x6a, 0x69, 0x2d, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x63, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2f, 0x6d, 0x61, 0x69, 0x2f, 0x73, 0x6d, 0x61, 0x72, 0x74,
	0x2d, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x2f, 0x6d, 0x61, 0x69, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mai_proto_rawDescOnce sync.Once
	file_mai_proto_rawDescData = file_mai_proto_rawDesc
)

func file_mai_proto_rawDescGZIP() []byte {
	file_mai_proto_rawDescOnce.Do(func() {
		file_mai_proto_rawDescData = protoimpl.X.CompressGZIP(file_mai_proto_rawDescData)
	})
	return file_mai_proto_rawDescData
}

var file_mai_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_mai_proto_goTypes = []interface{}{
	(*Approval)(nil),              // 0: mai.Approval
	(*OwnershipTransferred)(nil),  // 1: mai.OwnershipTransferred
	(*TransferVault)(nil),         // 2: mai.TransferVault
	(*DepositCollateral)(nil),     // 3: mai.DepositCollateral
	(*WithdrawCollateral)(nil),    // 4: mai.WithdrawCollateral
	(*BuyRiskyVault)(nil),         // 5: mai.BuyRiskyVault
	(*Transfer)(nil),              // 6: mai.Transfer
	(*CreateVault)(nil),           // 7: mai.CreateVault
	(*DestroyVault)(nil),          // 8: mai.DestroyVault
	(*BorrowToken)(nil),           // 9: mai.BorrowToken
	(*PayBackToken)(nil),          // 10: mai.PayBackToken
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_mai_proto_depIdxs = []int32{
	11, // 0: mai.Approval.ts:type_name -> google.protobuf.Timestamp
	11, // 1: mai.OwnershipTransferred.ts:type_name -> google.protobuf.Timestamp
	11, // 2: mai.TransferVault.ts:type_name -> google.protobuf.Timestamp
	11, // 3: mai.DepositCollateral.ts:type_name -> google.protobuf.Timestamp
	11, // 4: mai.WithdrawCollateral.ts:type_name -> google.protobuf.Timestamp
	11, // 5: mai.BuyRiskyVault.ts:type_name -> google.protobuf.Timestamp
	11, // 6: mai.Transfer.ts:type_name -> google.protobuf.Timestamp
	11, // 7: mai.CreateVault.ts:type_name -> google.protobuf.Timestamp
	11, // 8: mai.DestroyVault.ts:type_name -> google.protobuf.Timestamp
	11, // 9: mai.BorrowToken.ts:type_name -> google.protobuf.Timestamp
	11, // 10: mai.PayBackToken.ts:type_name -> google.protobuf.Timestamp
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_mai_proto_init() }
func file_mai_proto_init() {
	if File_mai_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mai_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Approval); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mai_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OwnershipTransferred); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mai_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransferVault); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mai_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepositCollateral); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mai_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithdrawCollateral); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mai_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuyRiskyVault); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mai_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Transfer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mai_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateVault); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mai_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DestroyVault); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mai_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BorrowToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mai_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PayBackToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mai_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mai_proto_goTypes,
		DependencyIndexes: file_mai_proto_depIdxs,
		MessageInfos:      file_mai_proto_msgTypes,
	}.Build()
	File_mai_proto = out.File
	file_mai_proto_rawDesc = nil
	file_mai_proto_goTypes = nil
	file_mai_proto_depIdxs = nil
}
