syntax = "proto3";

package factory;

import "google/protobuf/timestamp.proto";
import "lotus/lotus.proto";

option go_package = "github.com/trylotus/connectors/uniswapv2/factory";

message PairCreated {
  option (lotus.composite).index = {
    unique: true
    fields: [
      "block_hash",
      "log_index",
      "ts"
    ]
  };

  option (lotus.composite).index = {
    fields: [
      "token0",
      "token1"
    ]
  };

  google.protobuf.Timestamp ts = 1;
  uint64 block_number = 2 [(lotus.index) = {}];
  bytes block_hash = 3 [(lotus.bytes) = {format: FORMAT_TYPE_HEX}]; // Hash
  bytes tx_hash = 4 [
    (lotus.bytes) = {format: FORMAT_TYPE_HEX},
    (lotus.index) = {}
  ]; // Hash
  uint64 log_index = 5;
  bytes token0 = 6 [(lotus.bytes) = {format: FORMAT_TYPE_HEX}]; // Address
  bytes token1 = 7 [(lotus.bytes) = {format: FORMAT_TYPE_HEX}]; // Address
  bytes pair = 8 [
    (lotus.bytes) = {format: FORMAT_TYPE_HEX},
    (lotus.index) = {}
  ]; // Address
  string arg3 = 9 [(lotus.numeric) = {precision: 78}]; // uint256
  string token0_name = 10;
  string token0_symbol = 11;
  uint32 token0_decimals = 12;
  string token1_name = 13;
  string token1_symbol = 14;
  uint32 token1_decimals = 15;
}
