package makerdao

import (
	"github.com/nakji-network/connectors/makerdao/AAVE"
	"github.com/nakji-network/connectors/makerdao/ADAI"
	"github.com/nakji-network/connectors/makerdao/ARBITRUM_DAI_BRIDGE"
	"github.com/nakji-network/connectors/makerdao/ARBITRUM_ESCROW"
	"github.com/nakji-network/connectors/makerdao/ARBITRUM_GOV_RELAY"
	"github.com/nakji-network/connectors/makerdao/ARBITRUM_L2_DAI"
	"github.com/nakji-network/connectors/makerdao/ARBITRUM_L2_DAI_GATEWAY"
	"github.com/nakji-network/connectors/makerdao/ARBITRUM_L2_GOV_RELAY"
	"github.com/nakji-network/connectors/makerdao/BAL"
	"github.com/nakji-network/connectors/makerdao/BAT"
	"github.com/nakji-network/connectors/makerdao/CDP_MANAGER"
	"github.com/nakji-network/connectors/makerdao/CDP_REGISTRY"
	"github.com/nakji-network/connectors/makerdao/CHANGELOG"
	"github.com/nakji-network/connectors/makerdao/CLIPPER_MOM"
	"github.com/nakji-network/connectors/makerdao/COMP"
	"github.com/nakji-network/connectors/makerdao/CRVV1ETHSTETH"
	"github.com/nakji-network/connectors/makerdao/DIRECT_MOM"
	"github.com/nakji-network/connectors/makerdao/DSR_MANAGER"
	"github.com/nakji-network/connectors/makerdao/ETH"
	"github.com/nakji-network/connectors/makerdao/FLIPPER_MOM"
	"github.com/nakji-network/connectors/makerdao/GOV_GUARD"
	"github.com/nakji-network/connectors/makerdao/GUNIV3DAIUSDC1"
	"github.com/nakji-network/connectors/makerdao/GUNIV3DAIUSDC2"
	"github.com/nakji-network/connectors/makerdao/GUSD"
	"github.com/nakji-network/connectors/makerdao/ILK_REGISTRY"
	"github.com/nakji-network/connectors/makerdao/JOIN_FAB"
	"github.com/nakji-network/connectors/makerdao/KNC"
	"github.com/nakji-network/connectors/makerdao/LERP_FAB"
	"github.com/nakji-network/connectors/makerdao/LINK"
	"github.com/nakji-network/connectors/makerdao/LRC"
	"github.com/nakji-network/connectors/makerdao/MANA"
	"github.com/nakji-network/connectors/makerdao/MATIC"
	"github.com/nakji-network/connectors/makerdao/MCD_ADM"
	"github.com/nakji-network/connectors/makerdao/MCD_CAT"
	"github.com/nakji-network/connectors/makerdao/MCD_CROPPER"
	"github.com/nakji-network/connectors/makerdao/MCD_CROPPER_IMP"
	"github.com/nakji-network/connectors/makerdao/MCD_DAI"
	"github.com/nakji-network/connectors/makerdao/MCD_DEPLOY"
	"github.com/nakji-network/connectors/makerdao/MCD_DOG"
	"github.com/nakji-network/connectors/makerdao/MCD_END"
	"github.com/nakji-network/connectors/makerdao/MCD_ESM"
	"github.com/nakji-network/connectors/makerdao/MCD_FLAP"
	"github.com/nakji-network/connectors/makerdao/MCD_FLASH"
	"github.com/nakji-network/connectors/makerdao/MCD_FLOP"
	"github.com/nakji-network/connectors/makerdao/MCD_GOV"
	"github.com/nakji-network/connectors/makerdao/MCD_IAM_AUTO_LINE"
	"github.com/nakji-network/connectors/makerdao/MCD_JUG"
	"github.com/nakji-network/connectors/makerdao/MCD_PAUSE"
	"github.com/nakji-network/connectors/makerdao/MCD_POT"
	"github.com/nakji-network/connectors/makerdao/MCD_PSM_GUSD_A"
	"github.com/nakji-network/connectors/makerdao/MCD_PSM_PAX_A"
	"github.com/nakji-network/connectors/makerdao/MCD_PSM_USDC_A"
	"github.com/nakji-network/connectors/makerdao/MCD_SPOT"
	"github.com/nakji-network/connectors/makerdao/MCD_VAT"
	"github.com/nakji-network/connectors/makerdao/MCD_VEST_DAI"
	"github.com/nakji-network/connectors/makerdao/MCD_VEST_DAI_LEGACY"
	"github.com/nakji-network/connectors/makerdao/MCD_VEST_MKR"
	"github.com/nakji-network/connectors/makerdao/MCD_VEST_MKR_TREASURY"
	"github.com/nakji-network/connectors/makerdao/MCD_VOW"
	"github.com/nakji-network/connectors/makerdao/MIP21_LIQUIDATION_ORACLE"
	"github.com/nakji-network/connectors/makerdao/OPTIMISM_DAI_BRIDGE"
	"github.com/nakji-network/connectors/makerdao/OPTIMISM_ESCROW"
	"github.com/nakji-network/connectors/makerdao/OPTIMISM_GOV_RELAY"
	"github.com/nakji-network/connectors/makerdao/OPTIMISM_L2_DAI"
	"github.com/nakji-network/connectors/makerdao/OPTIMISM_L2_DAI_TOKEN_BRIDGE"
	"github.com/nakji-network/connectors/makerdao/OPTIMISM_L2_GOVERNANCE_RELAY"
	"github.com/nakji-network/connectors/makerdao/OSM_MOM"
	"github.com/nakji-network/connectors/makerdao/PAX"
	"github.com/nakji-network/connectors/makerdao/PAXUSD"
	"github.com/nakji-network/connectors/makerdao/PROXY_DEPLOYER"
	"github.com/nakji-network/connectors/makerdao/PROXY_FACTORY"
	"github.com/nakji-network/connectors/makerdao/RENBTC"
	"github.com/nakji-network/connectors/makerdao/RWA"
	"github.com/nakji-network/connectors/makerdao/RWA_CONDUIT"
	"github.com/nakji-network/connectors/makerdao/RWA_URN"
	"github.com/nakji-network/connectors/makerdao/STETH"
	"github.com/nakji-network/connectors/makerdao/TUSD"
	"github.com/nakji-network/connectors/makerdao/UNI"
	"github.com/nakji-network/connectors/makerdao/UNIV2"
	"github.com/nakji-network/connectors/makerdao/USDC"
	"github.com/nakji-network/connectors/makerdao/USDT"
	"github.com/nakji-network/connectors/makerdao/VOTE_DELEGATE_PROXY_FACTORY"
	"github.com/nakji-network/connectors/makerdao/VOTE_PROXY_FACTORY"
	"github.com/nakji-network/connectors/makerdao/WBTC"
	"github.com/nakji-network/connectors/makerdao/WSTETH"
	"github.com/nakji-network/connectors/makerdao/YFI"
	"github.com/nakji-network/connectors/makerdao/ZRX"

	"google.golang.org/protobuf/proto"
)

var TopicTypes = map[string]map[string]proto.Message{
	"arbitrum": {
		"nakji.makerdao.0_0_0.arbitrum_l2_dai_gateway_approve":                &ARBITRUM_L2_DAI_GATEWAY.Approve{},
		"nakji.makerdao.0_0_0.arbitrum_l2_dai_gateway_deny":                   &ARBITRUM_L2_DAI_GATEWAY.Deny{},
		"nakji.makerdao.0_0_0.arbitrum_l2_dai_gateway_rely":                   &ARBITRUM_L2_DAI_GATEWAY.Rely{},
		"nakji.makerdao.0_0_0.arbitrum_l2_gov_relay_closed":                   &ARBITRUM_L2_GOV_RELAY.Closed{},
		"nakji.makerdao.0_0_0.arbitrum_l2_gov_relay_deny":                     &ARBITRUM_L2_GOV_RELAY.Deny{},
		"nakji.makerdao.0_0_0.arbitrum_l2_gov_relay_erc20depositinitiated":    &ARBITRUM_L2_GOV_RELAY.ERC20DepositInitiated{},
		"nakji.makerdao.0_0_0.arbitrum_l2_gov_relay_erc20withdrawalfinalized": &ARBITRUM_L2_GOV_RELAY.ERC20WithdrawalFinalized{},
		"nakji.makerdao.0_0_0.arbitrum_l2_gov_relay_rely":                     &ARBITRUM_L2_GOV_RELAY.Rely{},
	},
	"ethereum": {
		"nakji.makerdao.0_0_0.aave_adminchanged":                              &AAVE.AdminChanged{},
		"nakji.makerdao.0_0_0.aave_upgraded":                                  &AAVE.Upgraded{},
		"nakji.makerdao.0_0_0.adai_upgraded":                                  &ADAI.Upgraded{},
		"nakji.makerdao.0_0_0.arbitrum_dai_bridge_closed":                     &ARBITRUM_DAI_BRIDGE.Closed{},
		"nakji.makerdao.0_0_0.arbitrum_dai_bridge_deny":                       &ARBITRUM_DAI_BRIDGE.Deny{},
		"nakji.makerdao.0_0_0.arbitrum_dai_bridge_depositinitiated":           &ARBITRUM_DAI_BRIDGE.DepositInitiated{},
		"nakji.makerdao.0_0_0.arbitrum_dai_bridge_rely":                       &ARBITRUM_DAI_BRIDGE.Rely{},
		"nakji.makerdao.0_0_0.arbitrum_dai_bridge_txtol2":                     &ARBITRUM_DAI_BRIDGE.TxToL2{},
		"nakji.makerdao.0_0_0.arbitrum_dai_bridge_withdrawalfinalized":        &ARBITRUM_DAI_BRIDGE.WithdrawalFinalized{},
		"nakji.makerdao.0_0_0.arbitrum_escrow_approve":                        &ARBITRUM_ESCROW.Approve{},
		"nakji.makerdao.0_0_0.arbitrum_escrow_deny":                           &ARBITRUM_ESCROW.Deny{},
		"nakji.makerdao.0_0_0.arbitrum_escrow_rely":                           &ARBITRUM_ESCROW.Rely{},
		"nakji.makerdao.0_0_0.arbitrum_gov_relay_deny":                        &ARBITRUM_GOV_RELAY.Deny{},
		"nakji.makerdao.0_0_0.arbitrum_gov_relay_rely":                        &ARBITRUM_GOV_RELAY.Rely{},
		"nakji.makerdao.0_0_0.arbitrum_gov_relay_txtol2":                      &ARBITRUM_GOV_RELAY.TxToL2{},
		"nakji.makerdao.0_0_0.bal_approval":                                   &BAL.Approval{},
		"nakji.makerdao.0_0_0.bal_rolegranted":                                &BAL.RoleGranted{},
		"nakji.makerdao.0_0_0.bal_rolerevoked":                                &BAL.RoleRevoked{},
		"nakji.makerdao.0_0_0.bal_snapshot":                                   &BAL.Snapshot{},
		"nakji.makerdao.0_0_0.bal_transfer":                                   &BAL.Transfer{},
		"nakji.makerdao.0_0_0.bat_approval":                                   &BAT.Approval{},
		"nakji.makerdao.0_0_0.bat_createbat":                                  &BAT.CreateBAT{},
		"nakji.makerdao.0_0_0.bat_logrefund":                                  &BAT.LogRefund{},
		"nakji.makerdao.0_0_0.bat_transfer":                                   &BAT.Transfer{},
		"nakji.makerdao.0_0_0.cdp_manager_lognote":                            &CDP_MANAGER.LogNote{},
		"nakji.makerdao.0_0_0.cdp_manager_newcdp":                             &CDP_MANAGER.NewCdp{},
		"nakji.makerdao.0_0_0.cdp_registry_newcdpregistered":                  &CDP_REGISTRY.NewCdpRegistered{},
		"nakji.makerdao.0_0_0.changelog_deny":                                 &CHANGELOG.Deny{},
		"nakji.makerdao.0_0_0.changelog_rely":                                 &CHANGELOG.Rely{},
		"nakji.makerdao.0_0_0.changelog_removeaddress":                        &CHANGELOG.RemoveAddress{},
		"nakji.makerdao.0_0_0.changelog_updateaddress":                        &CHANGELOG.UpdateAddress{},
		"nakji.makerdao.0_0_0.changelog_updateipfs":                           &CHANGELOG.UpdateIPFS{},
		"nakji.makerdao.0_0_0.changelog_updatesha256sum":                      &CHANGELOG.UpdateSha256Sum{},
		"nakji.makerdao.0_0_0.changelog_updateversion":                        &CHANGELOG.UpdateVersion{},
		"nakji.makerdao.0_0_0.clipper_mom_setauthority":                       &CLIPPER_MOM.SetAuthority{},
		"nakji.makerdao.0_0_0.clipper_mom_setbreaker":                         &CLIPPER_MOM.SetBreaker{},
		"nakji.makerdao.0_0_0.clipper_mom_setowner":                           &CLIPPER_MOM.SetOwner{},
		"nakji.makerdao.0_0_0.comp_approval":                                  &COMP.Approval{},
		"nakji.makerdao.0_0_0.comp_delegatechanged":                           &COMP.DelegateChanged{},
		"nakji.makerdao.0_0_0.comp_delegatevoteschanged":                      &COMP.DelegateVotesChanged{},
		"nakji.makerdao.0_0_0.comp_transfer":                                  &COMP.Transfer{},
		"nakji.makerdao.0_0_0.crvv1ethsteth_approval":                         &CRVV1ETHSTETH.Approval{},
		"nakji.makerdao.0_0_0.crvv1ethsteth_transfer":                         &CRVV1ETHSTETH.Transfer{},
		"nakji.makerdao.0_0_0.direct_mom_disable":                             &DIRECT_MOM.Disable{},
		"nakji.makerdao.0_0_0.direct_mom_setauthority":                        &DIRECT_MOM.SetAuthority{},
		"nakji.makerdao.0_0_0.direct_mom_setowner":                            &DIRECT_MOM.SetOwner{},
		"nakji.makerdao.0_0_0.dsr_manager_exit":                               &DSR_MANAGER.Exit{},
		"nakji.makerdao.0_0_0.dsr_manager_join":                               &DSR_MANAGER.Join{},
		"nakji.makerdao.0_0_0.eth_approval":                                   &ETH.Approval{},
		"nakji.makerdao.0_0_0.eth_deposit":                                    &ETH.Deposit{},
		"nakji.makerdao.0_0_0.eth_transfer":                                   &ETH.Transfer{},
		"nakji.makerdao.0_0_0.eth_withdrawal":                                 &ETH.Withdrawal{},
		"nakji.makerdao.0_0_0.flipper_mom_deny":                               &FLIPPER_MOM.Deny{},
		"nakji.makerdao.0_0_0.flipper_mom_rely":                               &FLIPPER_MOM.Rely{},
		"nakji.makerdao.0_0_0.flipper_mom_setauthority":                       &FLIPPER_MOM.SetAuthority{},
		"nakji.makerdao.0_0_0.flipper_mom_setowner":                           &FLIPPER_MOM.SetOwner{},
		"nakji.makerdao.0_0_0.gov_guard_logdeny":                              &GOV_GUARD.LogDeny{},
		"nakji.makerdao.0_0_0.gov_guard_logrely":                              &GOV_GUARD.LogRely{},
		"nakji.makerdao.0_0_0.gov_guard_logsetroot":                           &GOV_GUARD.LogSetRoot{},
		"nakji.makerdao.0_0_0.guniv3daiusdc1_proxyadmintransferred":           &GUNIV3DAIUSDC1.ProxyAdminTransferred{},
		"nakji.makerdao.0_0_0.guniv3daiusdc1_proxyimplementationupdated":      &GUNIV3DAIUSDC1.ProxyImplementationUpdated{},
		"nakji.makerdao.0_0_0.guniv3daiusdc2_proxyadmintransferred":           &GUNIV3DAIUSDC2.ProxyAdminTransferred{},
		"nakji.makerdao.0_0_0.guniv3daiusdc2_proxyimplementationupdated":      &GUNIV3DAIUSDC2.ProxyImplementationUpdated{},
		"nakji.makerdao.0_0_0.gusd_approval":                                  &GUSD.Approval{},
		"nakji.makerdao.0_0_0.gusd_custodianchangeconfirmed":                  &GUSD.CustodianChangeConfirmed{},
		"nakji.makerdao.0_0_0.gusd_custodianchangerequested":                  &GUSD.CustodianChangeRequested{},
		"nakji.makerdao.0_0_0.gusd_implchangeconfirmed":                       &GUSD.ImplChangeConfirmed{},
		"nakji.makerdao.0_0_0.gusd_implchangerequested":                       &GUSD.ImplChangeRequested{},
		"nakji.makerdao.0_0_0.gusd_transfer":                                  &GUSD.Transfer{},
		"nakji.makerdao.0_0_0.ilk_registry_addilk":                            &ILK_REGISTRY.AddIlk{},
		"nakji.makerdao.0_0_0.ilk_registry_deny":                              &ILK_REGISTRY.Deny{},
		"nakji.makerdao.0_0_0.ilk_registry_file":                              &ILK_REGISTRY.File{},
		"nakji.makerdao.0_0_0.ilk_registry_file0":                             &ILK_REGISTRY.File0{},
		"nakji.makerdao.0_0_0.ilk_registry_file1":                             &ILK_REGISTRY.File1{},
		"nakji.makerdao.0_0_0.ilk_registry_file2":                             &ILK_REGISTRY.File2{},
		"nakji.makerdao.0_0_0.ilk_registry_nameerror":                         &ILK_REGISTRY.NameError{},
		"nakji.makerdao.0_0_0.ilk_registry_rely":                              &ILK_REGISTRY.Rely{},
		"nakji.makerdao.0_0_0.ilk_registry_removeilk":                         &ILK_REGISTRY.RemoveIlk{},
		"nakji.makerdao.0_0_0.ilk_registry_symbolerror":                       &ILK_REGISTRY.SymbolError{},
		"nakji.makerdao.0_0_0.ilk_registry_updateilk":                         &ILK_REGISTRY.UpdateIlk{},
		"nakji.makerdao.0_0_0.join_fab_newjoin":                               &JOIN_FAB.NewJoin{},
		"nakji.makerdao.0_0_0.knc_approval":                                   &KNC.Approval{},
		"nakji.makerdao.0_0_0.knc_burn":                                       &KNC.Burn{},
		"nakji.makerdao.0_0_0.knc_transfer":                                   &KNC.Transfer{},
		"nakji.makerdao.0_0_0.lerp_fab_deny":                                  &LERP_FAB.Deny{},
		"nakji.makerdao.0_0_0.lerp_fab_lerpfinished":                          &LERP_FAB.LerpFinished{},
		"nakji.makerdao.0_0_0.lerp_fab_newilklerp":                            &LERP_FAB.NewIlkLerp{},
		"nakji.makerdao.0_0_0.lerp_fab_newlerp":                               &LERP_FAB.NewLerp{},
		"nakji.makerdao.0_0_0.lerp_fab_rely":                                  &LERP_FAB.Rely{},
		"nakji.makerdao.0_0_0.link_approval":                                  &LINK.Approval{},
		"nakji.makerdao.0_0_0.link_transfer":                                  &LINK.Transfer{},
		"nakji.makerdao.0_0_0.lrc_approval":                                   &LRC.Approval{},
		"nakji.makerdao.0_0_0.lrc_burn":                                       &LRC.Burn{},
		"nakji.makerdao.0_0_0.lrc_transfer":                                   &LRC.Transfer{},
		"nakji.makerdao.0_0_0.mana_approval":                                  &MANA.Approval{},
		"nakji.makerdao.0_0_0.mana_burn":                                      &MANA.Burn{},
		"nakji.makerdao.0_0_0.mana_mint":                                      &MANA.Mint{},
		"nakji.makerdao.0_0_0.mana_mintfinished":                              &MANA.MintFinished{},
		"nakji.makerdao.0_0_0.mana_pause":                                     &MANA.Pause{},
		"nakji.makerdao.0_0_0.mana_transfer":                                  &MANA.Transfer{},
		"nakji.makerdao.0_0_0.mana_unpause":                                   &MANA.Unpause{},
		"nakji.makerdao.0_0_0.matic_approval":                                 &MATIC.Approval{},
		"nakji.makerdao.0_0_0.matic_paused":                                   &MATIC.Paused{},
		"nakji.makerdao.0_0_0.matic_pauseradded":                              &MATIC.PauserAdded{},
		"nakji.makerdao.0_0_0.matic_pauserremoved":                            &MATIC.PauserRemoved{},
		"nakji.makerdao.0_0_0.matic_transfer":                                 &MATIC.Transfer{},
		"nakji.makerdao.0_0_0.matic_unpaused":                                 &MATIC.Unpaused{},
		"nakji.makerdao.0_0_0.mcd_adm_etch":                                   &MCD_ADM.Etch{},
		"nakji.makerdao.0_0_0.mcd_adm_lognote":                                &MCD_ADM.LogNote{},
		"nakji.makerdao.0_0_0.mcd_adm_logsetauthority":                        &MCD_ADM.LogSetAuthority{},
		"nakji.makerdao.0_0_0.mcd_adm_logsetowner":                            &MCD_ADM.LogSetOwner{},
		"nakji.makerdao.0_0_0.mcd_cat_bite":                                   &MCD_CAT.Bite{},
		"nakji.makerdao.0_0_0.mcd_cat_lognote":                                &MCD_CAT.LogNote{},
		"nakji.makerdao.0_0_0.mcd_cropper_deny":                               &MCD_CROPPER.Deny{},
		"nakji.makerdao.0_0_0.mcd_cropper_imp_hope":                           &MCD_CROPPER_IMP.Hope{},
		"nakji.makerdao.0_0_0.mcd_cropper_imp_newproxy":                       &MCD_CROPPER_IMP.NewProxy{},
		"nakji.makerdao.0_0_0.mcd_cropper_imp_nope":                           &MCD_CROPPER_IMP.Nope{},
		"nakji.makerdao.0_0_0.mcd_cropper_rely":                               &MCD_CROPPER.Rely{},
		"nakji.makerdao.0_0_0.mcd_cropper_setimplementation":                  &MCD_CROPPER.SetImplementation{},
		"nakji.makerdao.0_0_0.mcd_dai_approval":                               &MCD_DAI.Approval{},
		"nakji.makerdao.0_0_0.mcd_dai_lognote":                                &MCD_DAI.LogNote{},
		"nakji.makerdao.0_0_0.mcd_dai_transfer":                               &MCD_DAI.Transfer{},
		"nakji.makerdao.0_0_0.mcd_deploy_logsetauthority":                     &MCD_DEPLOY.LogSetAuthority{},
		"nakji.makerdao.0_0_0.mcd_deploy_logsetowner":                         &MCD_DEPLOY.LogSetOwner{},
		"nakji.makerdao.0_0_0.mcd_dog_bark":                                   &MCD_DOG.Bark{},
		"nakji.makerdao.0_0_0.mcd_dog_cage":                                   &MCD_DOG.Cage{},
		"nakji.makerdao.0_0_0.mcd_dog_deny":                                   &MCD_DOG.Deny{},
		"nakji.makerdao.0_0_0.mcd_dog_digs":                                   &MCD_DOG.Digs{},
		"nakji.makerdao.0_0_0.mcd_dog_file":                                   &MCD_DOG.File{},
		"nakji.makerdao.0_0_0.mcd_dog_file0":                                  &MCD_DOG.File0{},
		"nakji.makerdao.0_0_0.mcd_dog_file1":                                  &MCD_DOG.File1{},
		"nakji.makerdao.0_0_0.mcd_dog_file2":                                  &MCD_DOG.File2{},
		"nakji.makerdao.0_0_0.mcd_dog_rely":                                   &MCD_DOG.Rely{},
		"nakji.makerdao.0_0_0.mcd_end_cage":                                   &MCD_END.Cage{},
		"nakji.makerdao.0_0_0.mcd_end_cage0":                                  &MCD_END.Cage0{},
		"nakji.makerdao.0_0_0.mcd_end_cash":                                   &MCD_END.Cash{},
		"nakji.makerdao.0_0_0.mcd_end_deny":                                   &MCD_END.Deny{},
		"nakji.makerdao.0_0_0.mcd_end_file":                                   &MCD_END.File{},
		"nakji.makerdao.0_0_0.mcd_end_file0":                                  &MCD_END.File0{},
		"nakji.makerdao.0_0_0.mcd_end_flow":                                   &MCD_END.Flow{},
		"nakji.makerdao.0_0_0.mcd_end_free":                                   &MCD_END.Free{},
		"nakji.makerdao.0_0_0.mcd_end_pack":                                   &MCD_END.Pack{},
		"nakji.makerdao.0_0_0.mcd_end_rely":                                   &MCD_END.Rely{},
		"nakji.makerdao.0_0_0.mcd_end_skim":                                   &MCD_END.Skim{},
		"nakji.makerdao.0_0_0.mcd_end_skip":                                   &MCD_END.Skip{},
		"nakji.makerdao.0_0_0.mcd_end_snip":                                   &MCD_END.Snip{},
		"nakji.makerdao.0_0_0.mcd_end_thaw":                                   &MCD_END.Thaw{},
		"nakji.makerdao.0_0_0.mcd_esm_deny":                                   &MCD_ESM.Deny{},
		"nakji.makerdao.0_0_0.mcd_esm_denyproxy":                              &MCD_ESM.DenyProxy{},
		"nakji.makerdao.0_0_0.mcd_esm_file":                                   &MCD_ESM.File{},
		"nakji.makerdao.0_0_0.mcd_esm_file0":                                  &MCD_ESM.File0{},
		"nakji.makerdao.0_0_0.mcd_esm_fire":                                   &MCD_ESM.Fire{},
		"nakji.makerdao.0_0_0.mcd_esm_join":                                   &MCD_ESM.Join{},
		"nakji.makerdao.0_0_0.mcd_esm_rely":                                   &MCD_ESM.Rely{},
		"nakji.makerdao.0_0_0.mcd_flap_kick":                                  &MCD_FLAP.Kick{},
		"nakji.makerdao.0_0_0.mcd_flap_lognote":                               &MCD_FLAP.LogNote{},
		"nakji.makerdao.0_0_0.mcd_flash_deny":                                 &MCD_FLASH.Deny{},
		"nakji.makerdao.0_0_0.mcd_flash_file":                                 &MCD_FLASH.File{},
		"nakji.makerdao.0_0_0.mcd_flash_flashloan":                            &MCD_FLASH.FlashLoan{},
		"nakji.makerdao.0_0_0.mcd_flash_rely":                                 &MCD_FLASH.Rely{},
		"nakji.makerdao.0_0_0.mcd_flash_vatdaiflashloan":                      &MCD_FLASH.VatDaiFlashLoan{},
		"nakji.makerdao.0_0_0.mcd_flop_kick":                                  &MCD_FLOP.Kick{},
		"nakji.makerdao.0_0_0.mcd_flop_lognote":                               &MCD_FLOP.LogNote{},
		"nakji.makerdao.0_0_0.mcd_gov_approval":                               &MCD_GOV.Approval{},
		"nakji.makerdao.0_0_0.mcd_gov_burn":                                   &MCD_GOV.Burn{},
		"nakji.makerdao.0_0_0.mcd_gov_lognote":                                &MCD_GOV.LogNote{},
		"nakji.makerdao.0_0_0.mcd_gov_logsetauthority":                        &MCD_GOV.LogSetAuthority{},
		"nakji.makerdao.0_0_0.mcd_gov_logsetowner":                            &MCD_GOV.LogSetOwner{},
		"nakji.makerdao.0_0_0.mcd_gov_mint":                                   &MCD_GOV.Mint{},
		"nakji.makerdao.0_0_0.mcd_gov_transfer":                               &MCD_GOV.Transfer{},
		"nakji.makerdao.0_0_0.mcd_iam_auto_line_deny":                         &MCD_IAM_AUTO_LINE.Deny{},
		"nakji.makerdao.0_0_0.mcd_iam_auto_line_exec":                         &MCD_IAM_AUTO_LINE.Exec{},
		"nakji.makerdao.0_0_0.mcd_iam_auto_line_rely":                         &MCD_IAM_AUTO_LINE.Rely{},
		"nakji.makerdao.0_0_0.mcd_iam_auto_line_remove":                       &MCD_IAM_AUTO_LINE.Remove{},
		"nakji.makerdao.0_0_0.mcd_iam_auto_line_setup":                        &MCD_IAM_AUTO_LINE.Setup{},
		"nakji.makerdao.0_0_0.mcd_jug_lognote":                                &MCD_JUG.LogNote{},
		"nakji.makerdao.0_0_0.mcd_pause_lognote":                              &MCD_PAUSE.LogNote{},
		"nakji.makerdao.0_0_0.mcd_pause_logsetauthority":                      &MCD_PAUSE.LogSetAuthority{},
		"nakji.makerdao.0_0_0.mcd_pause_logsetowner":                          &MCD_PAUSE.LogSetOwner{},
		"nakji.makerdao.0_0_0.mcd_pot_lognote":                                &MCD_POT.LogNote{},
		"nakji.makerdao.0_0_0.mcd_psm_gusd_a_buygem":                          &MCD_PSM_GUSD_A.BuyGem{},
		"nakji.makerdao.0_0_0.mcd_psm_gusd_a_deny":                            &MCD_PSM_GUSD_A.Deny{},
		"nakji.makerdao.0_0_0.mcd_psm_gusd_a_file":                            &MCD_PSM_GUSD_A.File{},
		"nakji.makerdao.0_0_0.mcd_psm_gusd_a_rely":                            &MCD_PSM_GUSD_A.Rely{},
		"nakji.makerdao.0_0_0.mcd_psm_gusd_a_sellgem":                         &MCD_PSM_GUSD_A.SellGem{},
		"nakji.makerdao.0_0_0.mcd_psm_pax_a_buygem":                           &MCD_PSM_PAX_A.BuyGem{},
		"nakji.makerdao.0_0_0.mcd_psm_pax_a_deny":                             &MCD_PSM_PAX_A.Deny{},
		"nakji.makerdao.0_0_0.mcd_psm_pax_a_file":                             &MCD_PSM_PAX_A.File{},
		"nakji.makerdao.0_0_0.mcd_psm_pax_a_rely":                             &MCD_PSM_PAX_A.Rely{},
		"nakji.makerdao.0_0_0.mcd_psm_pax_a_sellgem":                          &MCD_PSM_PAX_A.SellGem{},
		"nakji.makerdao.0_0_0.mcd_psm_usdc_a_buygem":                          &MCD_PSM_USDC_A.BuyGem{},
		"nakji.makerdao.0_0_0.mcd_psm_usdc_a_deny":                            &MCD_PSM_USDC_A.Deny{},
		"nakji.makerdao.0_0_0.mcd_psm_usdc_a_file":                            &MCD_PSM_USDC_A.File{},
		"nakji.makerdao.0_0_0.mcd_psm_usdc_a_rely":                            &MCD_PSM_USDC_A.Rely{},
		"nakji.makerdao.0_0_0.mcd_psm_usdc_a_sellgem":                         &MCD_PSM_USDC_A.SellGem{},
		"nakji.makerdao.0_0_0.mcd_spot_lognote":                               &MCD_SPOT.LogNote{},
		"nakji.makerdao.0_0_0.mcd_spot_poke":                                  &MCD_SPOT.Poke{},
		"nakji.makerdao.0_0_0.mcd_vat_lognote":                                &MCD_VAT.LogNote{},
		"nakji.makerdao.0_0_0.mcd_vest_dai_deny":                              &MCD_VEST_DAI.Deny{},
		"nakji.makerdao.0_0_0.mcd_vest_dai_file":                              &MCD_VEST_DAI.File{},
		"nakji.makerdao.0_0_0.mcd_vest_dai_init":                              &MCD_VEST_DAI.Init{},
		"nakji.makerdao.0_0_0.mcd_vest_dai_legacy_deny":                       &MCD_VEST_DAI_LEGACY.Deny{},
		"nakji.makerdao.0_0_0.mcd_vest_dai_legacy_file":                       &MCD_VEST_DAI_LEGACY.File{},
		"nakji.makerdao.0_0_0.mcd_vest_dai_legacy_init":                       &MCD_VEST_DAI_LEGACY.Init{},
		"nakji.makerdao.0_0_0.mcd_vest_dai_legacy_move":                       &MCD_VEST_DAI_LEGACY.Move{},
		"nakji.makerdao.0_0_0.mcd_vest_dai_legacy_rely":                       &MCD_VEST_DAI_LEGACY.Rely{},
		"nakji.makerdao.0_0_0.mcd_vest_dai_legacy_restrict":                   &MCD_VEST_DAI_LEGACY.Restrict{},
		"nakji.makerdao.0_0_0.mcd_vest_dai_legacy_unrestrict":                 &MCD_VEST_DAI_LEGACY.Unrestrict{},
		"nakji.makerdao.0_0_0.mcd_vest_dai_legacy_vest":                       &MCD_VEST_DAI_LEGACY.Vest{},
		"nakji.makerdao.0_0_0.mcd_vest_dai_legacy_yank":                       &MCD_VEST_DAI_LEGACY.Yank{},
		"nakji.makerdao.0_0_0.mcd_vest_dai_move":                              &MCD_VEST_DAI.Move{},
		"nakji.makerdao.0_0_0.mcd_vest_dai_rely":                              &MCD_VEST_DAI.Rely{},
		"nakji.makerdao.0_0_0.mcd_vest_dai_restrict":                          &MCD_VEST_DAI.Restrict{},
		"nakji.makerdao.0_0_0.mcd_vest_dai_unrestrict":                        &MCD_VEST_DAI.Unrestrict{},
		"nakji.makerdao.0_0_0.mcd_vest_dai_vest":                              &MCD_VEST_DAI.Vest{},
		"nakji.makerdao.0_0_0.mcd_vest_dai_yank":                              &MCD_VEST_DAI.Yank{},
		"nakji.makerdao.0_0_0.mcd_vest_mkr_deny":                              &MCD_VEST_MKR.Deny{},
		"nakji.makerdao.0_0_0.mcd_vest_mkr_file":                              &MCD_VEST_MKR.File{},
		"nakji.makerdao.0_0_0.mcd_vest_mkr_init":                              &MCD_VEST_MKR.Init{},
		"nakji.makerdao.0_0_0.mcd_vest_mkr_move":                              &MCD_VEST_MKR.Move{},
		"nakji.makerdao.0_0_0.mcd_vest_mkr_rely":                              &MCD_VEST_MKR.Rely{},
		"nakji.makerdao.0_0_0.mcd_vest_mkr_restrict":                          &MCD_VEST_MKR.Restrict{},
		"nakji.makerdao.0_0_0.mcd_vest_mkr_treasury_deny":                     &MCD_VEST_MKR_TREASURY.Deny{},
		"nakji.makerdao.0_0_0.mcd_vest_mkr_treasury_file":                     &MCD_VEST_MKR_TREASURY.File{},
		"nakji.makerdao.0_0_0.mcd_vest_mkr_treasury_init":                     &MCD_VEST_MKR_TREASURY.Init{},
		"nakji.makerdao.0_0_0.mcd_vest_mkr_treasury_move":                     &MCD_VEST_MKR_TREASURY.Move{},
		"nakji.makerdao.0_0_0.mcd_vest_mkr_treasury_rely":                     &MCD_VEST_MKR_TREASURY.Rely{},
		"nakji.makerdao.0_0_0.mcd_vest_mkr_treasury_restrict":                 &MCD_VEST_MKR_TREASURY.Restrict{},
		"nakji.makerdao.0_0_0.mcd_vest_mkr_treasury_unrestrict":               &MCD_VEST_MKR_TREASURY.Unrestrict{},
		"nakji.makerdao.0_0_0.mcd_vest_mkr_treasury_vest":                     &MCD_VEST_MKR_TREASURY.Vest{},
		"nakji.makerdao.0_0_0.mcd_vest_mkr_treasury_yank":                     &MCD_VEST_MKR_TREASURY.Yank{},
		"nakji.makerdao.0_0_0.mcd_vest_mkr_unrestrict":                        &MCD_VEST_MKR.Unrestrict{},
		"nakji.makerdao.0_0_0.mcd_vest_mkr_vest":                              &MCD_VEST_MKR.Vest{},
		"nakji.makerdao.0_0_0.mcd_vest_mkr_yank":                              &MCD_VEST_MKR.Yank{},
		"nakji.makerdao.0_0_0.mcd_vow_lognote":                                &MCD_VOW.LogNote{},
		"nakji.makerdao.0_0_0.mip21_liquidation_oracle_bump":                  &MIP21_LIQUIDATION_ORACLE.Bump{},
		"nakji.makerdao.0_0_0.mip21_liquidation_oracle_cull":                  &MIP21_LIQUIDATION_ORACLE.Cull{},
		"nakji.makerdao.0_0_0.mip21_liquidation_oracle_cure":                  &MIP21_LIQUIDATION_ORACLE.Cure{},
		"nakji.makerdao.0_0_0.mip21_liquidation_oracle_deny":                  &MIP21_LIQUIDATION_ORACLE.Deny{},
		"nakji.makerdao.0_0_0.mip21_liquidation_oracle_file":                  &MIP21_LIQUIDATION_ORACLE.File{},
		"nakji.makerdao.0_0_0.mip21_liquidation_oracle_init":                  &MIP21_LIQUIDATION_ORACLE.Init{},
		"nakji.makerdao.0_0_0.mip21_liquidation_oracle_rely":                  &MIP21_LIQUIDATION_ORACLE.Rely{},
		"nakji.makerdao.0_0_0.mip21_liquidation_oracle_tell":                  &MIP21_LIQUIDATION_ORACLE.Tell{},
		"nakji.makerdao.0_0_0.optimism_dai_bridge_closed":                     &OPTIMISM_DAI_BRIDGE.Closed{},
		"nakji.makerdao.0_0_0.optimism_dai_bridge_deny":                       &OPTIMISM_DAI_BRIDGE.Deny{},
		"nakji.makerdao.0_0_0.optimism_dai_bridge_erc20depositinitiated":      &OPTIMISM_DAI_BRIDGE.ERC20DepositInitiated{},
		"nakji.makerdao.0_0_0.optimism_dai_bridge_erc20withdrawalfinalized":   &OPTIMISM_DAI_BRIDGE.ERC20WithdrawalFinalized{},
		"nakji.makerdao.0_0_0.optimism_dai_bridge_rely":                       &OPTIMISM_DAI_BRIDGE.Rely{},
		"nakji.makerdao.0_0_0.optimism_escrow_approve":                        &OPTIMISM_ESCROW.Approve{},
		"nakji.makerdao.0_0_0.optimism_escrow_deny":                           &OPTIMISM_ESCROW.Deny{},
		"nakji.makerdao.0_0_0.optimism_escrow_rely":                           &OPTIMISM_ESCROW.Rely{},
		"nakji.makerdao.0_0_0.optimism_gov_relay_deny":                        &OPTIMISM_GOV_RELAY.Deny{},
		"nakji.makerdao.0_0_0.optimism_gov_relay_rely":                        &OPTIMISM_GOV_RELAY.Rely{},
		"nakji.makerdao.0_0_0.osm_mom_lognote":                                &OSM_MOM.LogNote{},
		"nakji.makerdao.0_0_0.pax_adminchanged":                               &PAX.AdminChanged{},
		"nakji.makerdao.0_0_0.pax_upgraded":                                   &PAX.Upgraded{},
		"nakji.makerdao.0_0_0.paxusd_adminchanged":                            &PAXUSD.AdminChanged{},
		"nakji.makerdao.0_0_0.paxusd_upgraded":                                &PAXUSD.Upgraded{},
		"nakji.makerdao.0_0_0.proxy_deployer_lognote":                         &PROXY_DEPLOYER.LogNote{},
		"nakji.makerdao.0_0_0.proxy_deployer_logsetauthority":                 &PROXY_DEPLOYER.LogSetAuthority{},
		"nakji.makerdao.0_0_0.proxy_deployer_logsetowner":                     &PROXY_DEPLOYER.LogSetOwner{},
		"nakji.makerdao.0_0_0.proxy_factory_created":                          &PROXY_FACTORY.Created{},
		"nakji.makerdao.0_0_0.renbtc_adminchanged":                            &RENBTC.AdminChanged{},
		"nakji.makerdao.0_0_0.renbtc_upgraded":                                &RENBTC.Upgraded{},
		"nakji.makerdao.0_0_0.rwa_approval":                                   &RWA.Approval{},
		"nakji.makerdao.0_0_0.rwa_conduit_cage":                               &RWA_CONDUIT.Cage{},
		"nakji.makerdao.0_0_0.rwa_conduit_cull":                               &RWA_CONDUIT.Cull{},
		"nakji.makerdao.0_0_0.rwa_conduit_deny":                               &RWA_CONDUIT.Deny{},
		"nakji.makerdao.0_0_0.rwa_conduit_draw":                               &RWA_CONDUIT.Draw{},
		"nakji.makerdao.0_0_0.rwa_conduit_exit":                               &RWA_CONDUIT.Exit{},
		"nakji.makerdao.0_0_0.rwa_conduit_file":                               &RWA_CONDUIT.File{},
		"nakji.makerdao.0_0_0.rwa_conduit_join":                               &RWA_CONDUIT.Join{},
		"nakji.makerdao.0_0_0.rwa_conduit_migrate":                            &RWA_CONDUIT.Migrate{},
		"nakji.makerdao.0_0_0.rwa_conduit_recover":                            &RWA_CONDUIT.Recover{},
		"nakji.makerdao.0_0_0.rwa_conduit_rely":                               &RWA_CONDUIT.Rely{},
		"nakji.makerdao.0_0_0.rwa_conduit_tell":                               &RWA_CONDUIT.Tell{},
		"nakji.makerdao.0_0_0.rwa_conduit_unwind":                             &RWA_CONDUIT.Unwind{},
		"nakji.makerdao.0_0_0.rwa_conduit_wipe":                               &RWA_CONDUIT.Wipe{},
		"nakji.makerdao.0_0_0.rwa_transfer":                                   &RWA.Transfer{},
		"nakji.makerdao.0_0_0.rwa_urn_deny":                                   &RWA_URN.Deny{},
		"nakji.makerdao.0_0_0.rwa_urn_draw":                                   &RWA_URN.Draw{},
		"nakji.makerdao.0_0_0.rwa_urn_file":                                   &RWA_URN.File{},
		"nakji.makerdao.0_0_0.rwa_urn_free":                                   &RWA_URN.Free{},
		"nakji.makerdao.0_0_0.rwa_urn_hope":                                   &RWA_URN.Hope{},
		"nakji.makerdao.0_0_0.rwa_urn_lock":                                   &RWA_URN.Lock{},
		"nakji.makerdao.0_0_0.rwa_urn_nope":                                   &RWA_URN.Nope{},
		"nakji.makerdao.0_0_0.rwa_urn_quit":                                   &RWA_URN.Quit{},
		"nakji.makerdao.0_0_0.rwa_urn_rely":                                   &RWA_URN.Rely{},
		"nakji.makerdao.0_0_0.rwa_urn_wipe":                                   &RWA_URN.Wipe{},
		"nakji.makerdao.0_0_0.steth_proxydeposit":                             &STETH.ProxyDeposit{},
		"nakji.makerdao.0_0_0.tusd_newpendingowner":                           &TUSD.NewPendingOwner{},
		"nakji.makerdao.0_0_0.tusd_proxyownershiptransferred":                 &TUSD.ProxyOwnershipTransferred{},
		"nakji.makerdao.0_0_0.tusd_upgraded":                                  &TUSD.Upgraded{},
		"nakji.makerdao.0_0_0.uni_approval":                                   &UNI.Approval{},
		"nakji.makerdao.0_0_0.uni_delegatechanged":                            &UNI.DelegateChanged{},
		"nakji.makerdao.0_0_0.uni_delegatevoteschanged":                       &UNI.DelegateVotesChanged{},
		"nakji.makerdao.0_0_0.uni_minterchanged":                              &UNI.MinterChanged{},
		"nakji.makerdao.0_0_0.uni_transfer":                                   &UNI.Transfer{},
		"nakji.makerdao.0_0_0.univ2_approval":                                 &UNIV2.Approval{},
		"nakji.makerdao.0_0_0.univ2_burn":                                     &UNIV2.Burn{},
		"nakji.makerdao.0_0_0.univ2_mint":                                     &UNIV2.Mint{},
		"nakji.makerdao.0_0_0.univ2_swap":                                     &UNIV2.Swap{},
		"nakji.makerdao.0_0_0.univ2_sync":                                     &UNIV2.Sync{},
		"nakji.makerdao.0_0_0.univ2_transfer":                                 &UNIV2.Transfer{},
		"nakji.makerdao.0_0_0.usdc_adminchanged":                              &USDC.AdminChanged{},
		"nakji.makerdao.0_0_0.usdc_upgraded":                                  &USDC.Upgraded{},
		"nakji.makerdao.0_0_0.usdt_addedblacklist":                            &USDT.AddedBlackList{},
		"nakji.makerdao.0_0_0.usdt_approval":                                  &USDT.Approval{},
		"nakji.makerdao.0_0_0.usdt_deprecate":                                 &USDT.Deprecate{},
		"nakji.makerdao.0_0_0.usdt_destroyedblackfunds":                       &USDT.DestroyedBlackFunds{},
		"nakji.makerdao.0_0_0.usdt_issue":                                     &USDT.Issue{},
		"nakji.makerdao.0_0_0.usdt_params":                                    &USDT.Params{},
		"nakji.makerdao.0_0_0.usdt_pause":                                     &USDT.Pause{},
		"nakji.makerdao.0_0_0.usdt_redeem":                                    &USDT.Redeem{},
		"nakji.makerdao.0_0_0.usdt_removedblacklist":                          &USDT.RemovedBlackList{},
		"nakji.makerdao.0_0_0.usdt_transfer":                                  &USDT.Transfer{},
		"nakji.makerdao.0_0_0.usdt_unpause":                                   &USDT.Unpause{},
		"nakji.makerdao.0_0_0.vote_delegate_proxy_factory_createvotedelegate": &VOTE_DELEGATE_PROXY_FACTORY.CreateVoteDelegate{},
		"nakji.makerdao.0_0_0.vote_proxy_factory_linkconfirmed":               &VOTE_PROXY_FACTORY.LinkConfirmed{},
		"nakji.makerdao.0_0_0.vote_proxy_factory_linkrequested":               &VOTE_PROXY_FACTORY.LinkRequested{},
		"nakji.makerdao.0_0_0.wbtc_approval":                                  &WBTC.Approval{},
		"nakji.makerdao.0_0_0.wbtc_burn":                                      &WBTC.Burn{},
		"nakji.makerdao.0_0_0.wbtc_mint":                                      &WBTC.Mint{},
		"nakji.makerdao.0_0_0.wbtc_mintfinished":                              &WBTC.MintFinished{},
		"nakji.makerdao.0_0_0.wbtc_ownershiprenounced":                        &WBTC.OwnershipRenounced{},
		"nakji.makerdao.0_0_0.wbtc_ownershiptransferred":                      &WBTC.OwnershipTransferred{},
		"nakji.makerdao.0_0_0.wbtc_pause":                                     &WBTC.Pause{},
		"nakji.makerdao.0_0_0.wbtc_transfer":                                  &WBTC.Transfer{},
		"nakji.makerdao.0_0_0.wbtc_unpause":                                   &WBTC.Unpause{},
		"nakji.makerdao.0_0_0.wsteth_approval":                                &WSTETH.Approval{},
		"nakji.makerdao.0_0_0.wsteth_transfer":                                &WSTETH.Transfer{},
		"nakji.makerdao.0_0_0.yfi_approval":                                   &YFI.Approval{},
		"nakji.makerdao.0_0_0.yfi_transfer":                                   &YFI.Transfer{},
		"nakji.makerdao.0_0_0.zrx_approval":                                   &ZRX.Approval{},
		"nakji.makerdao.0_0_0.zrx_transfer":                                   &ZRX.Transfer{},
	},
	"optimism": {
		"nakji.makerdao.0_0_0.optimism_l2_dai_token_bridge_approve":                  &OPTIMISM_L2_DAI_TOKEN_BRIDGE.Approve{},
		"nakji.makerdao.0_0_0.optimism_l2_dai_token_bridge_deny":                     &OPTIMISM_L2_DAI_TOKEN_BRIDGE.Deny{},
		"nakji.makerdao.0_0_0.optimism_l2_dai_token_bridge_rely":                     &OPTIMISM_L2_DAI_TOKEN_BRIDGE.Rely{},
		"nakji.makerdao.0_0_0.optimism_l2_governance_relay_closed":                   &OPTIMISM_L2_GOVERNANCE_RELAY.Closed{},
		"nakji.makerdao.0_0_0.optimism_l2_governance_relay_deny":                     &OPTIMISM_L2_GOVERNANCE_RELAY.Deny{},
		"nakji.makerdao.0_0_0.optimism_l2_governance_relay_erc20depositinitiated":    &OPTIMISM_L2_GOVERNANCE_RELAY.ERC20DepositInitiated{},
		"nakji.makerdao.0_0_0.optimism_l2_governance_relay_erc20withdrawalfinalized": &OPTIMISM_L2_GOVERNANCE_RELAY.ERC20WithdrawalFinalized{},
		"nakji.makerdao.0_0_0.optimism_l2_governance_relay_rely":                     &OPTIMISM_L2_GOVERNANCE_RELAY.Rely{},
	},
}

var ABIs = map[string]string{
	"AAVE":                         AAVE.AAVEABI,
	"ADAI":                         ADAI.ADAIABI,
	"ARBITRUM_DAI_BRIDGE":          ARBITRUM_DAI_BRIDGE.ARBITRUMDAIBRIDGEABI,
	"ARBITRUM_ESCROW":              ARBITRUM_ESCROW.ARBITRUMESCROWABI,
	"ARBITRUM_GOV_RELAY":           ARBITRUM_GOV_RELAY.ARBITRUMGOVRELAYABI,
	"ARBITRUM_L2_DAI":              ARBITRUM_L2_DAI.ARBITRUML2DAIABI,
	"ARBITRUM_L2_DAI_GATEWAY":      ARBITRUM_L2_DAI_GATEWAY.ARBITRUML2DAIGATEWAYABI,
	"ARBITRUM_L2_GOV_RELAY":        ARBITRUM_L2_GOV_RELAY.ARBITRUML2GOVRELAYABI,
	"BAL":                          BAL.BALABI,
	"BAT":                          BAT.BATABI,
	"CDP_MANAGER":                  CDP_MANAGER.CDPMANAGERABI,
	"CDP_REGISTRY":                 CDP_REGISTRY.CDPREGISTRYABI,
	"CHANGELOG":                    CHANGELOG.CHANGELOGABI,
	"CLIPPER_MOM":                  CLIPPER_MOM.CLIPPERMOMABI,
	"COMP":                         COMP.COMPABI,
	"CRVV1ETHSTETH":                CRVV1ETHSTETH.CRVV1ETHSTETHABI,
	"DIRECT_MOM":                   DIRECT_MOM.DIRECTMOMABI,
	"DSR_MANAGER":                  DSR_MANAGER.DSRMANAGERABI,
	"ETH":                          ETH.ETHABI,
	"FLIPPER_MOM":                  FLIPPER_MOM.FLIPPERMOMABI,
	"GOV_GUARD":                    GOV_GUARD.GOVGUARDABI,
	"GUNIV3DAIUSDC1":               GUNIV3DAIUSDC1.GUNIV3DAIUSDC1ABI,
	"GUNIV3DAIUSDC2":               GUNIV3DAIUSDC2.GUNIV3DAIUSDC2ABI,
	"GUSD":                         GUSD.GUSDABI,
	"ILK_REGISTRY":                 ILK_REGISTRY.ILKREGISTRYABI,
	"JOIN_FAB":                     JOIN_FAB.JOINFABABI,
	"KNC":                          KNC.KNCABI,
	"LERP_FAB":                     LERP_FAB.LERPFABABI,
	"LINK":                         LINK.LINKABI,
	"LRC":                          LRC.LRCABI,
	"MANA":                         MANA.MANAABI,
	"MATIC":                        MATIC.MATICABI,
	"MCD_ADM":                      MCD_ADM.MCDADMABI,
	"MCD_CAT":                      MCD_CAT.MCDCATABI,
	"MCD_CROPPER":                  MCD_CROPPER.MCDCROPPERABI,
	"MCD_CROPPER_IMP":              MCD_CROPPER_IMP.MCDCROPPERIMPABI,
	"MCD_DAI":                      MCD_DAI.MCDDAIABI,
	"MCD_DEPLOY":                   MCD_DEPLOY.MCDDEPLOYABI,
	"MCD_DOG":                      MCD_DOG.MCDDOGABI,
	"MCD_END":                      MCD_END.MCDENDABI,
	"MCD_ESM":                      MCD_ESM.MCDESMABI,
	"MCD_FLAP":                     MCD_FLAP.MCDFLAPABI,
	"MCD_FLASH":                    MCD_FLASH.MCDFLASHABI,
	"MCD_FLOP":                     MCD_FLOP.MCDFLOPABI,
	"MCD_GOV":                      MCD_GOV.MCDGOVABI,
	"MCD_IAM_AUTO_LINE":            MCD_IAM_AUTO_LINE.MCDIAMAUTOLINEABI,
	"MCD_JUG":                      MCD_JUG.MCDJUGABI,
	"MCD_PAUSE":                    MCD_PAUSE.MCDPAUSEABI,
	"MCD_POT":                      MCD_POT.MCDPOTABI,
	"MCD_PSM_GUSD_A":               MCD_PSM_GUSD_A.MCDPSMGUSDAABI,
	"MCD_PSM_PAX_A":                MCD_PSM_PAX_A.MCDPSMPAXAABI,
	"MCD_PSM_USDC_A":               MCD_PSM_USDC_A.MCDPSMUSDCAABI,
	"MCD_SPOT":                     MCD_SPOT.MCDSPOTABI,
	"MCD_VAT":                      MCD_VAT.MCDVATABI,
	"MCD_VEST_DAI":                 MCD_VEST_DAI.MCDVESTDAIABI,
	"MCD_VEST_DAI_LEGACY":          MCD_VEST_DAI_LEGACY.MCDVESTDAILEGACYABI,
	"MCD_VEST_MKR":                 MCD_VEST_MKR.MCDVESTMKRABI,
	"MCD_VEST_MKR_TREASURY":        MCD_VEST_MKR_TREASURY.MCDVESTMKRTREASURYABI,
	"MCD_VOW":                      MCD_VOW.MCDVOWABI,
	"MIP21_LIQUIDATION_ORACLE":     MIP21_LIQUIDATION_ORACLE.MIP21LIQUIDATIONORACLEABI,
	"OPTIMISM_DAI_BRIDGE":          OPTIMISM_DAI_BRIDGE.OPTIMISMDAIBRIDGEABI,
	"OPTIMISM_ESCROW":              OPTIMISM_ESCROW.OPTIMISMESCROWABI,
	"OPTIMISM_GOV_RELAY":           OPTIMISM_GOV_RELAY.OPTIMISMGOVRELAYABI,
	"OPTIMISM_L2_DAI":              OPTIMISM_L2_DAI.OPTIMISML2DAIABI,
	"OPTIMISM_L2_DAI_TOKEN_BRIDGE": OPTIMISM_L2_DAI_TOKEN_BRIDGE.OPTIMISML2DAITOKENBRIDGEABI,
	"OPTIMISM_L2_GOVERNANCE_RELAY": OPTIMISM_L2_GOVERNANCE_RELAY.OPTIMISML2GOVERNANCERELAYABI,
	"OSM_MOM":                      OSM_MOM.OSMMOMABI,
	"PAX":                          PAX.PAXABI,
	"PAXUSD":                       PAXUSD.PAXUSDABI,
	"PROXY_DEPLOYER":               PROXY_DEPLOYER.PROXYDEPLOYERABI,
	"PROXY_FACTORY":                PROXY_FACTORY.PROXYFACTORYABI,
	"RENBTC":                       RENBTC.RENBTCABI,
	"RWA":                          RWA.RWAABI,
	"RWA_CONDUIT":                  RWA_CONDUIT.RWACONDUITABI,
	"RWA_URN":                      RWA_URN.RWAURNABI,
	"STETH":                        STETH.STETHABI,
	"TUSD":                         TUSD.TUSDABI,
	"UNI":                          UNI.UNIABI,
	"UNIV2":                        UNIV2.UNIV2ABI,
	"USDC":                         USDC.USDCABI,
	"USDT":                         USDT.USDTABI,
	"VOTE_DELEGATE_PROXY_FACTORY":  VOTE_DELEGATE_PROXY_FACTORY.VOTEDELEGATEPROXYFACTORYABI,
	"VOTE_PROXY_FACTORY":           VOTE_PROXY_FACTORY.VOTEPROXYFACTORYABI,
	"WBTC":                         WBTC.WBTCABI,
	"WSTETH":                       WSTETH.WSTETHABI,
	"YFI":                          YFI.YFIABI,
	"ZRX":                          ZRX.ZRXABI,
}
