// Code generated - DO NOT EDIT.
// This file is a generated protocol buffer definition and any manual changes will be lost.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: ILK_REGISTRY.proto

package ILK_REGISTRY

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type File0 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts   *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Ilk  []byte                 `protobuf:"bytes,2,opt,name=Ilk,proto3" json:"Ilk,omitempty"`   //	bytes32
	What []byte                 `protobuf:"bytes,3,opt,name=What,proto3" json:"What,omitempty"` //	bytes32
	Data []byte                 `protobuf:"bytes,4,opt,name=Data,proto3" json:"Data,omitempty"` //	address
}

func (x *File0) Reset() {
	*x = File0{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ILK_REGISTRY_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *File0) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File0) ProtoMessage() {}

func (x *File0) ProtoReflect() protoreflect.Message {
	mi := &file_ILK_REGISTRY_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File0.ProtoReflect.Descriptor instead.
func (*File0) Descriptor() ([]byte, []int) {
	return file_ILK_REGISTRY_proto_rawDescGZIP(), []int{0}
}

func (x *File0) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *File0) GetIlk() []byte {
	if x != nil {
		return x.Ilk
	}
	return nil
}

func (x *File0) GetWhat() []byte {
	if x != nil {
		return x.What
	}
	return nil
}

func (x *File0) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type NameError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts  *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Ilk []byte                 `protobuf:"bytes,2,opt,name=Ilk,proto3" json:"Ilk,omitempty"` //	bytes32
}

func (x *NameError) Reset() {
	*x = NameError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ILK_REGISTRY_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NameError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameError) ProtoMessage() {}

func (x *NameError) ProtoReflect() protoreflect.Message {
	mi := &file_ILK_REGISTRY_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameError.ProtoReflect.Descriptor instead.
func (*NameError) Descriptor() ([]byte, []int) {
	return file_ILK_REGISTRY_proto_rawDescGZIP(), []int{1}
}

func (x *NameError) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *NameError) GetIlk() []byte {
	if x != nil {
		return x.Ilk
	}
	return nil
}

type RemoveIlk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts  *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Ilk []byte                 `protobuf:"bytes,2,opt,name=Ilk,proto3" json:"Ilk,omitempty"` //	bytes32
}

func (x *RemoveIlk) Reset() {
	*x = RemoveIlk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ILK_REGISTRY_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveIlk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveIlk) ProtoMessage() {}

func (x *RemoveIlk) ProtoReflect() protoreflect.Message {
	mi := &file_ILK_REGISTRY_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveIlk.ProtoReflect.Descriptor instead.
func (*RemoveIlk) Descriptor() ([]byte, []int) {
	return file_ILK_REGISTRY_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveIlk) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *RemoveIlk) GetIlk() []byte {
	if x != nil {
		return x.Ilk
	}
	return nil
}

type UpdateIlk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts  *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Ilk []byte                 `protobuf:"bytes,2,opt,name=Ilk,proto3" json:"Ilk,omitempty"` //	bytes32
}

func (x *UpdateIlk) Reset() {
	*x = UpdateIlk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ILK_REGISTRY_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateIlk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIlk) ProtoMessage() {}

func (x *UpdateIlk) ProtoReflect() protoreflect.Message {
	mi := &file_ILK_REGISTRY_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIlk.ProtoReflect.Descriptor instead.
func (*UpdateIlk) Descriptor() ([]byte, []int) {
	return file_ILK_REGISTRY_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateIlk) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *UpdateIlk) GetIlk() []byte {
	if x != nil {
		return x.Ilk
	}
	return nil
}

type AddIlk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts  *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Ilk []byte                 `protobuf:"bytes,2,opt,name=Ilk,proto3" json:"Ilk,omitempty"` //	bytes32
}

func (x *AddIlk) Reset() {
	*x = AddIlk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ILK_REGISTRY_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddIlk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddIlk) ProtoMessage() {}

func (x *AddIlk) ProtoReflect() protoreflect.Message {
	mi := &file_ILK_REGISTRY_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddIlk.ProtoReflect.Descriptor instead.
func (*AddIlk) Descriptor() ([]byte, []int) {
	return file_ILK_REGISTRY_proto_rawDescGZIP(), []int{4}
}

func (x *AddIlk) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *AddIlk) GetIlk() []byte {
	if x != nil {
		return x.Ilk
	}
	return nil
}

type File struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts   *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	What []byte                 `protobuf:"bytes,2,opt,name=What,proto3" json:"What,omitempty"` //	bytes32
	Data []byte                 `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"` //	address
}

func (x *File) Reset() {
	*x = File{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ILK_REGISTRY_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_ILK_REGISTRY_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_ILK_REGISTRY_proto_rawDescGZIP(), []int{5}
}

func (x *File) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *File) GetWhat() []byte {
	if x != nil {
		return x.What
	}
	return nil
}

func (x *File) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type File1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts   *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Ilk  []byte                 `protobuf:"bytes,2,opt,name=Ilk,proto3" json:"Ilk,omitempty"`   //	bytes32
	What []byte                 `protobuf:"bytes,3,opt,name=What,proto3" json:"What,omitempty"` //	bytes32
	Data []byte                 `protobuf:"bytes,4,opt,name=Data,proto3" json:"Data,omitempty"` //	uint256
}

func (x *File1) Reset() {
	*x = File1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ILK_REGISTRY_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *File1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File1) ProtoMessage() {}

func (x *File1) ProtoReflect() protoreflect.Message {
	mi := &file_ILK_REGISTRY_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File1.ProtoReflect.Descriptor instead.
func (*File1) Descriptor() ([]byte, []int) {
	return file_ILK_REGISTRY_proto_rawDescGZIP(), []int{6}
}

func (x *File1) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *File1) GetIlk() []byte {
	if x != nil {
		return x.Ilk
	}
	return nil
}

func (x *File1) GetWhat() []byte {
	if x != nil {
		return x.What
	}
	return nil
}

func (x *File1) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type File2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts   *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Ilk  []byte                 `protobuf:"bytes,2,opt,name=Ilk,proto3" json:"Ilk,omitempty"`   //	bytes32
	What []byte                 `protobuf:"bytes,3,opt,name=What,proto3" json:"What,omitempty"` //	bytes32
	Data string                 `protobuf:"bytes,4,opt,name=Data,proto3" json:"Data,omitempty"` //	string
}

func (x *File2) Reset() {
	*x = File2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ILK_REGISTRY_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *File2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File2) ProtoMessage() {}

func (x *File2) ProtoReflect() protoreflect.Message {
	mi := &file_ILK_REGISTRY_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File2.ProtoReflect.Descriptor instead.
func (*File2) Descriptor() ([]byte, []int) {
	return file_ILK_REGISTRY_proto_rawDescGZIP(), []int{7}
}

func (x *File2) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *File2) GetIlk() []byte {
	if x != nil {
		return x.Ilk
	}
	return nil
}

func (x *File2) GetWhat() []byte {
	if x != nil {
		return x.What
	}
	return nil
}

func (x *File2) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type Rely struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts  *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Usr []byte                 `protobuf:"bytes,2,opt,name=Usr,proto3" json:"Usr,omitempty"` //	address
}

func (x *Rely) Reset() {
	*x = Rely{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ILK_REGISTRY_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rely) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rely) ProtoMessage() {}

func (x *Rely) ProtoReflect() protoreflect.Message {
	mi := &file_ILK_REGISTRY_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rely.ProtoReflect.Descriptor instead.
func (*Rely) Descriptor() ([]byte, []int) {
	return file_ILK_REGISTRY_proto_rawDescGZIP(), []int{8}
}

func (x *Rely) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *Rely) GetUsr() []byte {
	if x != nil {
		return x.Usr
	}
	return nil
}

type SymbolError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts  *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Ilk []byte                 `protobuf:"bytes,2,opt,name=Ilk,proto3" json:"Ilk,omitempty"` //	bytes32
}

func (x *SymbolError) Reset() {
	*x = SymbolError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ILK_REGISTRY_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SymbolError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SymbolError) ProtoMessage() {}

func (x *SymbolError) ProtoReflect() protoreflect.Message {
	mi := &file_ILK_REGISTRY_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SymbolError.ProtoReflect.Descriptor instead.
func (*SymbolError) Descriptor() ([]byte, []int) {
	return file_ILK_REGISTRY_proto_rawDescGZIP(), []int{9}
}

func (x *SymbolError) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *SymbolError) GetIlk() []byte {
	if x != nil {
		return x.Ilk
	}
	return nil
}

type Deny struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts  *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Usr []byte                 `protobuf:"bytes,2,opt,name=Usr,proto3" json:"Usr,omitempty"` //	address
}

func (x *Deny) Reset() {
	*x = Deny{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ILK_REGISTRY_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Deny) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deny) ProtoMessage() {}

func (x *Deny) ProtoReflect() protoreflect.Message {
	mi := &file_ILK_REGISTRY_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deny.ProtoReflect.Descriptor instead.
func (*Deny) Descriptor() ([]byte, []int) {
	return file_ILK_REGISTRY_proto_rawDescGZIP(), []int{10}
}

func (x *Deny) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *Deny) GetUsr() []byte {
	if x != nil {
		return x.Usr
	}
	return nil
}

var File_ILK_REGISTRY_proto protoreflect.FileDescriptor

var file_ILK_REGISTRY_proto_rawDesc = []byte{
	0x0a, 0x12, 0x49, 0x4c, 0x4b, 0x5f, 0x52, 0x45, 0x47, 0x49, 0x53, 0x54, 0x52, 0x59, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x49, 0x4c, 0x4b, 0x5f, 0x52, 0x45, 0x47, 0x49, 0x53, 0x54,
	0x52, 0x59, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x6d, 0x0a, 0x05, 0x46, 0x69, 0x6c, 0x65, 0x30, 0x12, 0x2a, 0x0a, 0x02,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x49, 0x6c, 0x6b, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x49, 0x6c, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x57, 0x68,
	0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x57, 0x68, 0x61, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61,
	0x74, 0x61, 0x22, 0x49, 0x0a, 0x09, 0x4e, 0x61, 0x6d, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12,
	0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x49,
	0x6c, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x49, 0x6c, 0x6b, 0x22, 0x49, 0x0a,
	0x09, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x49, 0x6c, 0x6b, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x49, 0x6c, 0x6b, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x03, 0x49, 0x6c, 0x6b, 0x22, 0x49, 0x0a, 0x09, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x49, 0x6c, 0x6b, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74,
	0x73, 0x12, 0x10, 0x0a, 0x03, 0x49, 0x6c, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03,
	0x49, 0x6c, 0x6b, 0x22, 0x46, 0x0a, 0x06, 0x41, 0x64, 0x64, 0x49, 0x6c, 0x6b, 0x12, 0x2a, 0x0a,
	0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x49, 0x6c, 0x6b,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x49, 0x6c, 0x6b, 0x22, 0x5a, 0x0a, 0x04, 0x46,
	0x69, 0x6c, 0x65, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x57, 0x68, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x57,
	0x68, 0x61, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x6d, 0x0a, 0x05, 0x46, 0x69, 0x6c, 0x65, 0x31,
	0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x10, 0x0a, 0x03,
	0x49, 0x6c, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x49, 0x6c, 0x6b, 0x12, 0x12,
	0x0a, 0x04, 0x57, 0x68, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x57, 0x68,
	0x61, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x6d, 0x0a, 0x05, 0x46, 0x69, 0x6c, 0x65, 0x32, 0x12,
	0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x49,
	0x6c, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x49, 0x6c, 0x6b, 0x12, 0x12, 0x0a,
	0x04, 0x57, 0x68, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x57, 0x68, 0x61,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x44, 0x0a, 0x04, 0x52, 0x65, 0x6c, 0x79, 0x12, 0x2a, 0x0a,
	0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x73, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x55, 0x73, 0x72, 0x22, 0x4b, 0x0a, 0x0b, 0x53,
	0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x49, 0x6c, 0x6b, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x03, 0x49, 0x6c, 0x6b, 0x22, 0x44, 0x0a, 0x04, 0x44, 0x65, 0x6e, 0x79,
	0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x10, 0x0a, 0x03,
	0x55, 0x73, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x55, 0x73, 0x72, 0x42, 0x3f,
	0x5a, 0x3d, 0x62, 0x6c, 0x65, 0x70, 0x2e, 0x61, 0x69, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x63,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2f, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x64,
	0x61, 0x6f, 0x2f, 0x73, 0x6d, 0x61, 0x72, 0x74, 0x2d, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x73, 0x2f, 0x49, 0x4c, 0x4b, 0x5f, 0x52, 0x45, 0x47, 0x49, 0x53, 0x54, 0x52, 0x59, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ILK_REGISTRY_proto_rawDescOnce sync.Once
	file_ILK_REGISTRY_proto_rawDescData = file_ILK_REGISTRY_proto_rawDesc
)

func file_ILK_REGISTRY_proto_rawDescGZIP() []byte {
	file_ILK_REGISTRY_proto_rawDescOnce.Do(func() {
		file_ILK_REGISTRY_proto_rawDescData = protoimpl.X.CompressGZIP(file_ILK_REGISTRY_proto_rawDescData)
	})
	return file_ILK_REGISTRY_proto_rawDescData
}

var file_ILK_REGISTRY_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_ILK_REGISTRY_proto_goTypes = []interface{}{
	(*File0)(nil),                 // 0: ILK_REGISTRY.File0
	(*NameError)(nil),             // 1: ILK_REGISTRY.NameError
	(*RemoveIlk)(nil),             // 2: ILK_REGISTRY.RemoveIlk
	(*UpdateIlk)(nil),             // 3: ILK_REGISTRY.UpdateIlk
	(*AddIlk)(nil),                // 4: ILK_REGISTRY.AddIlk
	(*File)(nil),                  // 5: ILK_REGISTRY.File
	(*File1)(nil),                 // 6: ILK_REGISTRY.File1
	(*File2)(nil),                 // 7: ILK_REGISTRY.File2
	(*Rely)(nil),                  // 8: ILK_REGISTRY.Rely
	(*SymbolError)(nil),           // 9: ILK_REGISTRY.SymbolError
	(*Deny)(nil),                  // 10: ILK_REGISTRY.Deny
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_ILK_REGISTRY_proto_depIdxs = []int32{
	11, // 0: ILK_REGISTRY.File0.ts:type_name -> google.protobuf.Timestamp
	11, // 1: ILK_REGISTRY.NameError.ts:type_name -> google.protobuf.Timestamp
	11, // 2: ILK_REGISTRY.RemoveIlk.ts:type_name -> google.protobuf.Timestamp
	11, // 3: ILK_REGISTRY.UpdateIlk.ts:type_name -> google.protobuf.Timestamp
	11, // 4: ILK_REGISTRY.AddIlk.ts:type_name -> google.protobuf.Timestamp
	11, // 5: ILK_REGISTRY.File.ts:type_name -> google.protobuf.Timestamp
	11, // 6: ILK_REGISTRY.File1.ts:type_name -> google.protobuf.Timestamp
	11, // 7: ILK_REGISTRY.File2.ts:type_name -> google.protobuf.Timestamp
	11, // 8: ILK_REGISTRY.Rely.ts:type_name -> google.protobuf.Timestamp
	11, // 9: ILK_REGISTRY.SymbolError.ts:type_name -> google.protobuf.Timestamp
	11, // 10: ILK_REGISTRY.Deny.ts:type_name -> google.protobuf.Timestamp
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_ILK_REGISTRY_proto_init() }
func file_ILK_REGISTRY_proto_init() {
	if File_ILK_REGISTRY_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ILK_REGISTRY_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*File0); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ILK_REGISTRY_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NameError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ILK_REGISTRY_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveIlk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ILK_REGISTRY_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateIlk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ILK_REGISTRY_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddIlk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ILK_REGISTRY_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*File); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ILK_REGISTRY_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*File1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ILK_REGISTRY_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*File2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ILK_REGISTRY_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rely); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ILK_REGISTRY_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SymbolError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ILK_REGISTRY_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Deny); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ILK_REGISTRY_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ILK_REGISTRY_proto_goTypes,
		DependencyIndexes: file_ILK_REGISTRY_proto_depIdxs,
		MessageInfos:      file_ILK_REGISTRY_proto_msgTypes,
	}.Build()
	File_ILK_REGISTRY_proto = out.File
	file_ILK_REGISTRY_proto_rawDesc = nil
	file_ILK_REGISTRY_proto_goTypes = nil
	file_ILK_REGISTRY_proto_depIdxs = nil
}
