// Code generated by connectorgen - Edit as necessary.
package nft

import (
	"github.com/nakji-network/ethnft-connector/erc1155"
	"github.com/nakji-network/ethnft-connector/erc721"
	"google.golang.org/protobuf/proto"
)

var TopicTypes = map[string]proto.Message{
	"nakji.nft.0_0_0.erc1155.approvalforall": &erc1155.ApprovalForAll{},
	"nakji.nft.0_0_0.erc1155.transferbatch":  &erc1155.TransferBatch{},
	"nakji.nft.0_0_0.erc1155.transfersingle": &erc1155.TransferSingle{},
	"nakji.nft.0_0_0.erc1155.uri":            &erc1155.URI{},
	"nakji.nft.0_0_0.erc721.approval":        &erc721.Approval{},
	"nakji.nft.0_0_0.erc721.approvalforall":  &erc721.ApprovalForAll{},
	"nakji.nft.0_0_0.erc721.transfer":        &erc721.Transfer{},
}
