syntax = "proto3";

package pumpfun;

import "google/protobuf/timestamp.proto";
import "lotus/lotus.proto";

message CreateEvent {
  option (lotus.composite).index = {
    unique: true
    fields: [
      "tx_hash",
      "log_index",
      "ts"
    ]
  };

  google.protobuf.Timestamp ts = 1;
  string tx_hash = 2;
  uint32 log_index = 3;
  string name = 4;
  string symbol = 5;
  string uri = 6;
  string mint = 7 [(lotus.index) = {}];
  string bonding_curve = 8;
  string user = 9;
}

message TradeEvent {
  option (lotus.composite).index = {
    unique: true
    fields: [
      "tx_hash",
      "log_index",
      "ts"
    ]
  };

  option (lotus.composite).index = {
    fields: [
      "mint",
      "ts"
    ]
  };

  google.protobuf.Timestamp ts = 1;
  string tx_hash = 2;
  uint32 log_index = 3;
  string mint = 4;
  string sol_amount = 5 [(lotus.numeric) = {}];
  string token_amount = 6 [(lotus.numeric) = {}];
  bool is_buy = 7;
  string user = 8;
  string virtual_sol_reserves = 9 [(lotus.numeric) = {}];
  string virtual_token_reserves = 10 [(lotus.numeric) = {}];
}

message CompleteEvent {
  option (lotus.composite).index = {
    unique: true
    fields: [
      "tx_hash",
      "log_index",
      "ts"
    ]
  };

  option (lotus.composite).index = {
    fields: [
      "mint",
      "ts"
    ]
  };

  google.protobuf.Timestamp ts = 1;
  string tx_hash = 2;
  uint32 log_index = 3;
  string user = 4;
  string mint = 5;
  string bonding_curve = 6;
}

message SetParamsEvent {
  option (lotus.composite).index = {
    unique: true
    fields: [
      "tx_hash",
      "log_index",
      "ts"
    ]
  };

  google.protobuf.Timestamp ts = 1;
  string tx_hash = 2;
  uint32 log_index = 3;
  string fee_recipient = 4;
  string initial_virtual_token_reserves = 5 [(lotus.numeric) = {}];
  string initial_virtual_sol_reserves = 6 [(lotus.numeric) = {}];
  string initial_real_token_reserves = 7 [(lotus.numeric) = {}];
  string token_total_supply = 8 [(lotus.numeric) = {}];
  uint64 fee_basis_points = 9;
}

message Trade5min {
  option (lotus.view) = {
    topic: "lotus.pumpfun.0_0_0.pumpfun_TradeEvent"
    materialized: true
    refresh_interval: '5 min'
    options: ["timescaledb.continuous"]
    group_by: [
      "t",
      "mint"
    ]
    where: "token_amount > 0 and sol_amount > 0"
  };

  option (lotus.composite).index = {
    fields: [
      "mint",
      "t"
    ]
  };

  google.protobuf.Timestamp t = 1 [(lotus.projection) = "time_bucket('5 min', ts)"];
  string mint = 2 [(lotus.projection) = "mint"];
  string open_price = 3 [
    (lotus.projection) = "first(sol_amount / token_amount, ts)",
    (lotus.numeric) = {}
  ];
  string high_price = 4 [
    (lotus.projection) = "max(sol_amount / token_amount)",
    (lotus.numeric) = {}
  ];
  string low_price = 5 [
    (lotus.projection) = "min(sol_amount / token_amount)",
    (lotus.numeric) = {}
  ];
  string close_price = 6 [
    (lotus.projection) = "last(sol_amount / token_amount, ts)",
    (lotus.numeric) = {}
  ];
  int64 makers = 7 [(lotus.projection) = "count(distinct \"user\")"];
  int64 txns_buy = 8 [(lotus.projection) = "sum(case when is_buy then 1 else 0 end)"];
  int64 txns_sell = 9 [(lotus.projection) = "sum(case when is_buy then 0 else 1 end)"];
  string volume_token_buy = 10 [
    (lotus.projection) = "sum(case when is_buy then token_amount else 0 end)",
    (lotus.numeric) = {}
  ];
  string volume_token_sell = 11 [
    (lotus.projection) = "sum(case when is_buy then 0 else token_amount end)",
    (lotus.numeric) = {}
  ];
  string volume_sol_buy = 12 [
    (lotus.projection) = "sum(case when is_buy then 0 else sol_amount end)",
    (lotus.numeric) = {}
  ];
  string volume_sol_sell = 13 [
    (lotus.projection) = "sum(case when is_buy then sol_amount else 0 end)",
    (lotus.numeric) = {}
  ];
}

message Trade1h {
  option (lotus.view) = {
    topic: "lotus.pumpfun.0_0_0.pumpfun_TradeEvent"
    materialized: true
    refresh_interval: '30 min'
    options: ["timescaledb.continuous"]
    group_by: [
      "t",
      "mint"
    ]
    where: "token_amount > 0 and sol_amount > 0"
  };

  option (lotus.composite).index = {
    fields: [
      "mint",
      "t"
    ]
  };

  google.protobuf.Timestamp t = 1 [(lotus.projection) = "time_bucket('1 hour', ts)"];
  string mint = 2 [(lotus.projection) = "mint"];
  string open_price = 3 [
    (lotus.projection) = "first(sol_amount / token_amount, ts)",
    (lotus.numeric) = {}
  ];
  string high_price = 4 [
    (lotus.projection) = "max(sol_amount / token_amount)",
    (lotus.numeric) = {}
  ];
  string low_price = 5 [
    (lotus.projection) = "min(sol_amount / token_amount)",
    (lotus.numeric) = {}
  ];
  string close_price = 6 [
    (lotus.projection) = "last(sol_amount / token_amount, ts)",
    (lotus.numeric) = {}
  ];
  int64 makers = 7 [(lotus.projection) = "count(distinct \"user\")"];
  int64 txns_buy = 8 [(lotus.projection) = "sum(case when is_buy then 1 else 0 end)"];
  int64 txns_sell = 9 [(lotus.projection) = "sum(case when is_buy then 0 else 1 end)"];
  string volume_token_buy = 10 [
    (lotus.projection) = "sum(case when is_buy then token_amount else 0 end)",
    (lotus.numeric) = {}
  ];
  string volume_token_sell = 11 [
    (lotus.projection) = "sum(case when is_buy then 0 else token_amount end)",
    (lotus.numeric) = {}
  ];
  string volume_sol_buy = 12 [
    (lotus.projection) = "sum(case when is_buy then 0 else sol_amount end)",
    (lotus.numeric) = {}
  ];
  string volume_sol_sell = 13 [
    (lotus.projection) = "sum(case when is_buy then sol_amount else 0 end)",
    (lotus.numeric) = {}
  ];
}

message Trade6h {
  option (lotus.view) = {
    topic: "lotus.pumpfun.0_0_0.pumpfun_TradeEvent"
    materialized: true
    refresh_interval: '1 hour'
    options: ["timescaledb.continuous"]
    group_by: [
      "t",
      "mint"
    ]
    where: "token_amount > 0 and sol_amount > 0"
  };

  option (lotus.composite).index = {
    fields: [
      "mint",
      "t"
    ]
  };

  google.protobuf.Timestamp t = 1 [(lotus.projection) = "time_bucket('6 hour', ts)"];
  string mint = 2 [(lotus.projection) = "mint"];
  string open_price = 3 [
    (lotus.projection) = "first(sol_amount / token_amount, ts)",
    (lotus.numeric) = {}
  ];
  string high_price = 4 [
    (lotus.projection) = "max(sol_amount / token_amount)",
    (lotus.numeric) = {}
  ];
  string low_price = 5 [
    (lotus.projection) = "min(sol_amount / token_amount)",
    (lotus.numeric) = {}
  ];
  string close_price = 6 [
    (lotus.projection) = "last(sol_amount / token_amount, ts)",
    (lotus.numeric) = {}
  ];
  int64 makers = 7 [(lotus.projection) = "count(distinct \"user\")"];
  int64 txns_buy = 8 [(lotus.projection) = "sum(case when is_buy then 1 else 0 end)"];
  int64 txns_sell = 9 [(lotus.projection) = "sum(case when is_buy then 0 else 1 end)"];
  string volume_token_buy = 10 [
    (lotus.projection) = "sum(case when is_buy then token_amount else 0 end)",
    (lotus.numeric) = {}
  ];
  string volume_token_sell = 11 [
    (lotus.projection) = "sum(case when is_buy then 0 else token_amount end)",
    (lotus.numeric) = {}
  ];
  string volume_sol_buy = 12 [
    (lotus.projection) = "sum(case when is_buy then 0 else sol_amount end)",
    (lotus.numeric) = {}
  ];
  string volume_sol_sell = 13 [
    (lotus.projection) = "sum(case when is_buy then sol_amount else 0 end)",
    (lotus.numeric) = {}
  ];
}

message Trade1d {
  option (lotus.view) = {
    topic: "lotus.pumpfun.0_0_0.pumpfun_TradeEvent"
    materialized: true
    refresh_interval: '1 hour'
    options: ["timescaledb.continuous"]
    group_by: [
      "t",
      "mint"
    ]
    where: "token_amount > 0 and sol_amount > 0"
  };

  option (lotus.composite).index = {
    fields: [
      "mint",
      "t"
    ]
  };

  google.protobuf.Timestamp t = 1 [(lotus.projection) = "time_bucket('1 day', ts)"];
  string mint = 2 [(lotus.projection) = "mint"];
  string open_price = 3 [
    (lotus.projection) = "first(sol_amount / token_amount, ts)",
    (lotus.numeric) = {}
  ];
  string high_price = 4 [
    (lotus.projection) = "max(sol_amount / token_amount)",
    (lotus.numeric) = {}
  ];
  string low_price = 5 [
    (lotus.projection) = "min(sol_amount / token_amount)",
    (lotus.numeric) = {}
  ];
  string close_price = 6 [
    (lotus.projection) = "last(sol_amount / token_amount, ts)",
    (lotus.numeric) = {}
  ];
  int64 makers = 7 [(lotus.projection) = "count(distinct \"user\")"];
  int64 txns_buy = 8 [(lotus.projection) = "sum(case when is_buy then 1 else 0 end)"];
  int64 txns_sell = 9 [(lotus.projection) = "sum(case when is_buy then 0 else 1 end)"];
  string volume_token_buy = 10 [
    (lotus.projection) = "sum(case when is_buy then token_amount else 0 end)",
    (lotus.numeric) = {}
  ];
  string volume_token_sell = 11 [
    (lotus.projection) = "sum(case when is_buy then 0 else token_amount end)",
    (lotus.numeric) = {}
  ];
  string volume_sol_buy = 12 [
    (lotus.projection) = "sum(case when is_buy then 0 else sol_amount end)",
    (lotus.numeric) = {}
  ];
  string volume_sol_sell = 13 [
    (lotus.projection) = "sum(case when is_buy then sol_amount else 0 end)",
    (lotus.numeric) = {}
  ];
}

message Trade1mon {
  option (lotus.view) = {
    topic: "lotus.pumpfun.0_0_0.pumpfun_TradeEvent"
    materialized: true
    refresh_interval: '1 hour'
    options: ["timescaledb.continuous"]
    group_by: [
      "t",
      "mint"
    ]
    where: "token_amount > 0 and sol_amount > 0"
  };

  option (lotus.composite).index = {
    fields: [
      "mint",
      "t"
    ]
  };

  google.protobuf.Timestamp t = 1 [(lotus.projection) = "time_bucket('1 month', ts)"];
  string mint = 2 [(lotus.projection) = "mint"];
  string open_price = 3 [
    (lotus.projection) = "first(sol_amount / token_amount, ts)",
    (lotus.numeric) = {}
  ];
  string high_price = 4 [
    (lotus.projection) = "max(sol_amount / token_amount)",
    (lotus.numeric) = {}
  ];
  string low_price = 5 [
    (lotus.projection) = "min(sol_amount / token_amount)",
    (lotus.numeric) = {}
  ];
  string close_price = 6 [
    (lotus.projection) = "last(sol_amount / token_amount, ts)",
    (lotus.numeric) = {}
  ];
  int64 makers = 7 [(lotus.projection) = "count(distinct \"user\")"];
  int64 txns_buy = 8 [(lotus.projection) = "sum(case when is_buy then 1 else 0 end)"];
  int64 txns_sell = 9 [(lotus.projection) = "sum(case when is_buy then 0 else 1 end)"];
  string volume_token_buy = 10 [
    (lotus.projection) = "sum(case when is_buy then token_amount else 0 end)",
    (lotus.numeric) = {}
  ];
  string volume_token_sell = 11 [
    (lotus.projection) = "sum(case when is_buy then 0 else token_amount end)",
    (lotus.numeric) = {}
  ];
  string volume_sol_buy = 12 [
    (lotus.projection) = "sum(case when is_buy then 0 else sol_amount end)",
    (lotus.numeric) = {}
  ];
  string volume_sol_sell = 13 [
    (lotus.projection) = "sum(case when is_buy then sol_amount else 0 end)",
    (lotus.numeric) = {}
  ];
}

message Trade1y {
  option (lotus.view) = {
    topic: "lotus.pumpfun.0_0_0.pumpfun_TradeEvent"
    materialized: true
    refresh_interval: '1 hour'
    options: ["timescaledb.continuous"]
    group_by: [
      "t",
      "mint"
    ]
    where: "token_amount > 0 and sol_amount > 0"
  };

  option (lotus.composite).index = {
    fields: [
      "mint",
      "t"
    ]
  };

  google.protobuf.Timestamp t = 1 [(lotus.projection) = "time_bucket('1 year', ts)"];
  string mint = 2 [(lotus.projection) = "mint"];
  string open_price = 3 [
    (lotus.projection) = "first(sol_amount / token_amount, ts)",
    (lotus.numeric) = {}
  ];
  string high_price = 4 [
    (lotus.projection) = "max(sol_amount / token_amount)",
    (lotus.numeric) = {}
  ];
  string low_price = 5 [
    (lotus.projection) = "min(sol_amount / token_amount)",
    (lotus.numeric) = {}
  ];
  string close_price = 6 [
    (lotus.projection) = "last(sol_amount / token_amount, ts)",
    (lotus.numeric) = {}
  ];
  int64 makers = 7 [(lotus.projection) = "count(distinct \"user\")"];
  int64 txns_buy = 8 [(lotus.projection) = "sum(case when is_buy then 1 else 0 end)"];
  int64 txns_sell = 9 [(lotus.projection) = "sum(case when is_buy then 0 else 1 end)"];
  string volume_token_buy = 10 [
    (lotus.projection) = "sum(case when is_buy then token_amount else 0 end)",
    (lotus.numeric) = {}
  ];
  string volume_token_sell = 11 [
    (lotus.projection) = "sum(case when is_buy then 0 else token_amount end)",
    (lotus.numeric) = {}
  ];
  string volume_sol_buy = 12 [
    (lotus.projection) = "sum(case when is_buy then 0 else sol_amount end)",
    (lotus.numeric) = {}
  ];
  string volume_sol_sell = 13 [
    (lotus.projection) = "sum(case when is_buy then sol_amount else 0 end)",
    (lotus.numeric) = {}
  ];
}
